"""Build the daily usability audit Excel report for 2026-06-10.

Sheets:
  Summary, website-auditor.io, kevinarmstrong.io, fundermatch.org,
  PRs opened, Owner exceptions, Regression-Tracking.

Data collected via live HTTP probes against production (curl) and direct
inspection of the cloned repos (SpikeyCoder/chaos_tester @ 7411659,
SpikeyCoder/my_website @ 835bb35, SpikeyCoder/funder-finder @ 8459de4)
on 2026-06-10.

Generated by the daily-usability-audit scheduled task (2026-06-10 run).
"""
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = Workbook()

HEADER_FILL = PatternFill(start_color="1F2937", end_color="1F2937", fill_type="solid")
HEADER_FONT = Font(bold=True, color="FFFFFF", size=11, name="Arial")
BODY_FONT = Font(name="Arial", size=10)
PASS_FILL = PatternFill(start_color="D1FAE5", end_color="D1FAE5", fill_type="solid")
FAIL_FILL = PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid")
WARN_FILL = PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid")
SKIP_FILL = PatternFill(start_color="E5E7EB", end_color="E5E7EB", fill_type="solid")
INFO_FILL = PatternFill(start_color="DBEAFE", end_color="DBEAFE", fill_type="solid")
PARTIAL_FILL = PatternFill(start_color="FED7AA", end_color="FED7AA", fill_type="solid")
THIN = Side(border_style="thin", color="D1D5DB")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
LEFT = Alignment(horizontal="left", vertical="top", wrap_text=True)


def style_header(ws, row=1):
    for c in ws[row]:
        c.fill = HEADER_FILL
        c.font = HEADER_FONT
        c.alignment = CENTER
        c.border = BORDER


def set_widths(ws, widths):
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w


def status_fill(s):
    s = (s or "").lower()
    if s == "pass":
        return PASS_FILL
    if s == "fail":
        return FAIL_FILL
    if s in ("warn", "warning"):
        return WARN_FILL
    if s in ("skip",):
        return SKIP_FILL
    if s in ("info",):
        return INFO_FILL
    if s == "partial":
        return PARTIAL_FILL
    return None


def write_tests(ws, tests):
    ws.append(["Test ID", "Category", "Test", "Status", "Severity", "Notes"])
    style_header(ws)
    for row in tests:
        ws.append(list(row))
        last_row = ws.max_row
        fill = status_fill(row[3])
        for ci in range(1, 7):
            cell = ws.cell(row=last_row, column=ci)
            cell.alignment = LEFT
            cell.border = BORDER
            cell.font = BODY_FONT
            if fill is not None:
                cell.fill = fill
    set_widths(ws, [14, 22, 60, 10, 10, 80])
    ws.freeze_panes = "A2"


# ============================================================
# WEBSITE-AUDITOR.IO  (chaos_tester @ 7411659)
# ============================================================
WAO_TESTS = [
    # First Impressions (12)
    ("WAO-FI-001", "First Impressions", "Homepage explains product (AI visibility + security + perf)", "pass", "-", "Live GET / returns 200; <title> 'Free Website Audit Tool — AI Visibility, Security & Performance Scanner | Website Auditor'; description covers AI visibility, broken links, security, performance, ChatGPT, no-login."),
    ("WAO-FI-002", "First Impressions", "Value proposition immediately obvious", "pass", "-", "Hero 'Does ChatGPT recommend your business?' + URL input + 'Check my site' button above the fold."),
    ("WAO-FI-003", "First Impressions", "Primary CTA clear and compelling", "pass", "-", "'Check my site' submit button anchors the hero form; 'View Sample Report' secondary CTA card surfaces sample-report."),
    ("WAO-FI-004", "First Impressions", "GET / responds quickly through Cloudflare edge", "pass", "-", "HTTP/2 200 from Cloudflare edge; cf-cache-status DYNAMIC; cf-ray a070582278ab535a-SEA; small HTML payload."),
    ("WAO-FI-005", "First Impressions", "Visual hierarchy (one H1, multiple H2/H3)", "pass", "-", "1 H1 (hero question); 2 H2 ('What We Check' + 'Ready to Improve Your Website?'); 7 H3 feature cards incl. API upsell."),
    ("WAO-FI-006", "First Impressions", "Trust signals on homepage", "pass", "-", "Industry strip + 2 testimonials (Jake Morrison/Morrison Dental, Sarah Patel/Freelance) + sample-report preview card retained."),
    ("WAO-FI-007", "First Impressions", "Navigation intuitive (3 top-level items)", "pass", "-", "Sample Report / API / Contact — short, jargon-free, anchored by site title."),
    ("WAO-FI-008", "First Impressions", "Hero works on mobile (viewport meta correct)", "pass", "-", "<meta viewport='width=device-width, initial-scale=1.0'> + hamburger #navToggle with aria-controls=mainNav."),
    ("WAO-FI-009", "First Impressions", "No broken images on home", "pass", "-", "Hero is inline SVG; logo.svg + favicon.svg both 200."),
    ("WAO-FI-010", "First Impressions", "Default body font readable", "pass", "-", "Inter @ 16px base; JetBrains Mono for code; preconnect to fonts.googleapis.com + fonts.gstatic.com."),
    ("WAO-FI-011", "First Impressions", "Hero Gartner claim is honest / non-misleading", "warn", "P3", "Owner-info per task spec. Hero still cites 'By 2028, 50% of customers will find your competitors through AI according to Gartner'. Owner exception — kept as directional marketing forecast. Inline style refactored to CSS class (commit 0e2aab7)."),
    ("WAO-FI-012", "First Impressions", "Above-the-fold CTA reachable without scroll", "pass", "-", "URL input + Check-my-site button inside .landing-hero render above the fold at 1280×800."),

    # Accessibility (18)
    ("WAO-AX-001", "Accessibility", "Skip-to-main-content link present", "pass", "-", "<a href='#main-content' class='skip-link'>Skip to main content</a> is the first focusable element in base.html."),
    ("WAO-AX-002", "Accessibility", "lang attribute set on <html>", "pass", "-", "<html lang='en'> in base.html."),
    ("WAO-AX-003", "Accessibility", "Landmarks (main + nav + header + footer)", "pass", "-", "<main id='main-content'>, <nav id='mainNav' aria-label='Main navigation'>, <header>, <footer> — all present and correctly identified."),
    ("WAO-AX-004", "Accessibility", "Hamburger button has aria-label + aria-expanded", "pass", "-", "<button class='hamburger' id='navToggle' aria-label='Toggle navigation menu' aria-expanded='false'>."),
    ("WAO-AX-005", "Accessibility", "Logo img has empty alt + aria-hidden (decorative)", "pass", "-", "<img src='/static/logo.svg' alt='' class='site-logo' aria-hidden='true' fetchpriority='high'> — brand text adjacent."),
    ("WAO-AX-006", "Accessibility", "URL input has aria-label", "pass", "-", "<input type='url' id='base_url' name='base_url' aria-label='Website URL to audit'>."),
    ("WAO-AX-007", "Accessibility", "AI custom-query inputs have aria-label (regression)", "pass", "-", "Commit ce2fc5f #101: aria-label added to custom-ai-query inputs (WAO-AX 2026-05-28)."),
    ("WAO-AX-008", "Accessibility", "Sample-report action buttons have aria-label", "pass", "-", "pill-share / pill-pdf / pill-schedule buttons each carry aria-label ('Share report' / 'Export PDF' / 'Schedule Retest')."),
    ("WAO-AX-009", "Accessibility", "All inline SVGs marked aria-hidden + focusable=false", "pass", "-", "Verified across templates/dashboard.html, templates/sample_report.html — decorative SVGs do not steal focus."),
    ("WAO-AX-010", "Accessibility", "Audit CTA hint announced to AT (aria-live polite)", "pass", "-", "<div id='audit-cta-hint' aria-live='polite'> announces 'Enter your business name below…' updates without focus change."),
    ("WAO-AX-011", "Accessibility", "Detected-name override row aria-live=polite", "pass", "-", "<div id='biz-name-confirmed' aria-live='polite'> + <div id='biz-name-override' aria-live='polite'> communicate detection state changes."),
    ("WAO-AX-012", "Accessibility", "city-error has role=alert for SR", "pass", "-", "<p id='city-error' role='alert'>Please enter a city to continue…</p>"),
    ("WAO-AX-013", "Accessibility", "Color contrast on hero / nav passes WCAG AA", "pass", "-", "Dark theme: white (#fff) on #0f172a ≈ 15:1; indigo-600 (#4f46e5) on white ≈ 6.0:1 per WCAG-fix comment in dashboard.css line 25."),
    ("WAO-AX-014", "Accessibility", "axe-core surface check on / (landmarks, contrast, role)", "pass", "-", "Static HTML inspection: 1 H1, single <main>, single <nav>, single <header>, single <footer>; no role conflicts; no missing label on inputs."),
    ("WAO-AX-015", "Accessibility", "axe-core surface check on /sample-report", "pass", "-", "Static inspection: report-top-bar uses aria-label on every action; back-link has aria-label; semantic h1 'Audit Report'."),
    ("WAO-AX-016", "Accessibility", "axe-core surface check on /contact", "pass", "-", "Contact page extends base.html → inherits skip-link, landmarks, theme-color, color-scheme."),
    ("WAO-AX-017", "Accessibility", "color-scheme meta declared (dark light)", "pass", "-", "base.html line 7: <meta name='color-scheme' content='dark light'> — OS form controls + scrollbars render in correct mode."),
    ("WAO-AX-018", "Accessibility", "AI recommendations rendered with semantic <strong> (regression)", "pass", "-", "Commit 20f6f6e: use <strong> tag for recommendation titles; font-weight alone wasn't visible in SR/visual."),

    # Forms & Inputs (11)
    ("WAO-FM-001", "Forms & Inputs", "URL input rejects malformed URLs", "pass", "-", "type='url' enforces RFC 3986 shape; required attribute prevents empty submit; aria-label='Website URL to audit'."),
    ("WAO-FM-002", "Forms & Inputs", "Validation error messages helpful", "pass", "-", "audit-cta-hint surfaces context-aware copy: 'Enter your business name and city below to run your audit' / 'Enter your business name…' / 'Enter your business city…'."),
    ("WAO-FM-003", "Forms & Inputs", "Required fields visibly marked", "pass", "-", "City field shows '<span class=\"u-color-error\">*</span><span class=\"sr-only\">(required)</span>' — color + SR text."),
    ("WAO-FM-004", "Forms & Inputs", "Form submission shows progress feedback", "pass", "-", "Loading-indicator overlay (#loading-indicator) renders below the search bar with spinner + text; uses absolute positioning to avoid layout shift."),
    ("WAO-FM-005", "Forms & Inputs", "Auto-fill behavior respects placeholders", "pass", "-", "URL input uses inputmode='url' equivalent (type='url'); city input has autocomplete='off' to avoid stale state."),
    ("WAO-FM-006", "Forms & Inputs", "Input types match content (url, text)", "pass", "-", "type='url' for base_url; type='text' for business name + city."),
    ("WAO-FM-007", "Forms & Inputs", "Placeholder text useful", "pass", "-", "'e.g. Acme Web Design' for business name; 'e.g. Seattle, WA' for city."),
    ("WAO-FM-008", "Forms & Inputs", "User can recover from rate-limit error", "pass", "-", "showRateLimitMessage() displays body.message, hideAuditSpinner re-enables button after 429."),
    ("WAO-FM-009", "Forms & Inputs", "REGRESSION: 'Not the right business?' toggle re-enables Check-my-site", "pass", "P1-regression", "Commit 2b7b7bc: 'fix: remove lingering u-cursor-disabled class on audit button re-enable'. enableAuditBtn() now strips both the disabled state AND the class. Verified in static/js/dashboard.js line 64-72."),
    ("WAO-FM-010", "Forms & Inputs", "REGRESSION: loading state uses CSS spinner (no hourglass emoji, no layout shift)", "pass", "P1-regression", "Commit db3be5c (usability 2026-05-30): 'replace hourglass emoji with CSS spinner on PDF download'. dashboard.css line 32-42 defines .btn-spinner pure CSS rotation; no emoji in showAuditSpinner(); u-cursor-disabled enforces min-width 160px to prevent shift."),
    ("WAO-FM-011", "Forms & Inputs", "Contact form on /contact submits via Web3Forms", "pass", "-", "Static inspection of templates/contact.html: form action posts JSON to api.web3forms.com; access_key embedded; honeypot field present."),

    # Navigation & IA (12)
    ("WAO-NV-001", "Navigation & IA", "All declared nav links 200", "pass", "-", "Live: / 200, /sample-report 200, /contact 200."),
    ("WAO-NV-002", "Navigation & IA", "/api shows API docs (not 404)", "warn", "P2", "Live GET /api-docs returns 404 (route path is /api, not /api-docs). Header link 'API' uses href='/api' — that returns 200. Distinct path /api-docs not registered."),
    ("WAO-NV-003", "Navigation & IA", "Sample-report deep-links work", "pass", "-", "<a href='/sample-report#audit-summary'> anchor patterns render correctly."),
    ("WAO-NV-004", "Navigation & IA", "Footer GitHub link uses rel='noopener'", "pass", "-", "<a href='https://github.com/SpikeyCoder/chaos_tester' rel='noopener' target='_blank'>GitHub</a>"),
    ("WAO-NV-005", "Navigation & IA", "/changelog 200 (release-notes page)", "pass", "-", "Live GET /changelog 200."),
    ("WAO-NV-006", "Navigation & IA", "/about 200", "pass", "-", "Live GET /about 200; page extends base.html."),
    ("WAO-NV-007", "Navigation & IA", "/status 200", "pass", "-", "Live GET /status 200."),
    ("WAO-NV-008", "Navigation & IA", "/privacy 200 and lists data-handling policies", "pass", "-", "Live GET /privacy 200 (templates/privacy.html)."),
    ("WAO-NV-009", "Navigation & IA", "/terms 200 with terms-of-use copy", "pass", "-", "Live GET /terms 200 (templates/terms.html)."),
    ("WAO-NV-010", "Navigation & IA", "/sitemap.xml + /robots.txt 200", "pass", "-", "Both return HTTP 200."),
    ("WAO-NV-011", "Navigation & IA", "/dashboard intentionally returns 404 (no public dashboard)", "info", "P3", "Live GET /dashboard returns 404; route is the homepage, not /dashboard. Not flagged as bug — no link to /dashboard anywhere in the rendered site."),
    ("WAO-NV-012", "Navigation & IA", "OWNER-INFO: /features, /how-it-works intentionally absent", "info", "-", "Per task spec — owner removed redundant /features and /how-it-works pages. Verified live: both return 404. NOT recommended for re-addition (logged in Owner exceptions)."),

    # Performance & Loading (10)
    ("WAO-PF-001", "Performance & Loading", "Preload critical assets", "pass", "-", "<link rel='preload' href='/static/logo.svg' as='image'>; preload + preconnect for favicon, analytics, fonts."),
    ("WAO-PF-002", "Performance & Loading", "Strict CSP with script-src hashes", "pass", "-", "Live header: 126 sha256 inline-script-attr hashes pinned (commit 02251a3 regenerated — previous was 127 stale). No unsafe-inline on script-src."),
    ("WAO-PF-003", "Performance & Loading", "CSP includes report-uri + report-to + Reporting-Endpoints", "pass", "-", "Live header: report-uri /api/csp-report; report-to csp-endpoint; Reporting-Endpoints: csp-endpoint=\"/api/csp-report\"."),
    ("WAO-PF-004", "Performance & Loading", "Permissions-Policy denies sensitive APIs (dense allowlist)", "pass", "-", "Live header: 40+ feature denylist (camera, microphone, geolocation, payment, USB, MIDI, …); fullscreen=(self), picture-in-picture=(self), web-share=(self) only."),
    ("WAO-PF-005", "Performance & Loading", "HSTS preload-eligible", "pass", "-", "Live header: Strict-Transport-Security: max-age=63072000; includeSubDomains; preload (2y)."),
    ("WAO-PF-006", "Performance & Loading", "X-Frame-Options DENY + X-Content-Type-Options nosniff", "pass", "-", "Both set on /. frame-ancestors 'none' enforced via CSP. Cross-Origin-Opener-Policy: same-origin; Cross-Origin-Resource-Policy: same-origin; Cross-Origin-Embedder-Policy: credentialless."),
    ("WAO-PF-007", "Performance & Loading", "Referrer-Policy strict-origin-when-cross-origin", "pass", "-", "Live header set."),
    ("WAO-PF-008", "Performance & Loading", "Two stylesheets only (base.css + utilities.css)", "pass", "-", "base.html links base.css + utilities.css; per-page additions only on /sample-report (sample-report.css) and /api-docs (api-docs.css). No over-fetching."),
    ("WAO-PF-009", "Performance & Loading", "Rate-limit headers expose budget to caller", "pass", "-", "Live header: x-ratelimit-limit: 120; x-ratelimit-remaining: 118; x-ratelimit-reset epoch — clients can self-throttle."),
    ("WAO-PF-010", "Performance & Loading", "Cloud Run secrets migrated to Secret Manager (regression)", "pass", "-", "Commits 1401942 + bbc7019 + 4d848de + eb15306 (WA-2026-05-28-01): Cloud Run secrets now flow via Secret Manager instead of --set-env-vars. eb15306 clears stale secret refs to avoid type conflict."),

    # Mobile Responsiveness (10)
    ("WAO-MO-001", "Mobile Responsiveness", "viewport meta correct", "pass", "-", "<meta name='viewport' content='width=device-width, initial-scale=1.0'>."),
    ("WAO-MO-002", "Mobile Responsiveness", "theme-color (#0f172a) — iOS Safari URL bar tinted", "pass", "-", "<meta name='theme-color' content='#0f172a'> in base.html line 6."),
    ("WAO-MO-003", "Mobile Responsiveness", "color-scheme dark light declared", "pass", "-", "<meta name='color-scheme' content='dark light'> in base.html line 7 (added in 2026-05-25 audit fix)."),
    ("WAO-MO-004", "Mobile Responsiveness", "Hamburger #navToggle exposes aria-expanded for SR users", "pass", "-", "Verified in base.html — aria-expanded toggled via JS."),
    ("WAO-MO-005", "Mobile Responsiveness", "Sample-report action pills wrap on narrow viewport", "pass", "-", "report-action-pills uses flex-wrap; pill-share, pill-pdf, pill-schedule all 44×44 tap targets."),
    ("WAO-MO-006", "Mobile Responsiveness", "Hero form usable at 375px width", "pass", "-", "URL input takes 100% width inside .landing-hero; submit button stacks below input."),
    ("WAO-MO-007", "Mobile Responsiveness", "Trust badges wrap with flex-wrap on mobile", "pass", "-", "trust-badges container uses flex; gap collapses on narrow viewport."),
    ("WAO-MO-008", "Mobile Responsiveness", "Loading indicator absolute-positioned (no layout shift)", "pass", "-", "dashboard.css line 47-65: .loading-indicator-overlay { position: absolute; left:0; right:0; top:100%; margin-top:12px; pointer-events:none; }"),
    ("WAO-MO-009", "Mobile Responsiveness", "Touch targets ≥44×44 (WCAG 2.5.5)", "pass", "-", "Sample-report pills + audit btn min-width 160px; nav links + footer links padded."),
    ("WAO-MO-010", "Mobile Responsiveness", "Hero CTA min-width prevents shift during spinner", "pass", "-", "static/css/utilities.css line 608: .u-cursor-disabled { cursor: not-allowed; min-width: 160px; } — locks width so spinner swap doesn't reflow."),

    # Content Quality (8)
    ("WAO-CQ-001", "Content Quality", "Copy reads cleanly on home (no typos)", "pass", "-", "Reviewed templates/dashboard.html; no typos in hero / features / CTA / testimonials."),
    ("WAO-CQ-002", "Content Quality", "All outbound product links 200", "pass", "-", "GitHub footer link → public repo 200."),
    ("WAO-CQ-003", "Content Quality", "Privacy + Terms pages 200 and on-brand", "pass", "-", "Both extend base.html; both 200; both indexed in sitemap.xml."),
    ("WAO-CQ-004", "Content Quality", "Contact info correct (Web3Forms endpoint)", "pass", "-", "Contact form posts to api.web3forms.com endpoint allowlisted in CSP form-action."),
    ("WAO-CQ-005", "Content Quality", "Plain-language report explanations (no jargon)", "pass", "-", "Feature card copy: 'Slow sites lose customers. We measure how fast your pages load and show you what to fix first.' Reading level appropriate for SMB owners."),
    ("WAO-CQ-006", "Content Quality", "Hero Gartner stat lacks citation footnote (OWNER EXCEPTION)", "warn", "P3", "Same item as WAO-FI-011 — OWNER EXCEPTION per task. Owner kept the claim. Inline style refactor commit 0e2aab7 moved style → class without changing copy."),
    ("WAO-CQ-007", "Content Quality", "API upsell pricing disclosed inline", "pass", "-", "API upsell card: 'Run 5 automated tests per day for just $10/month' — explicit rate + price."),
    ("WAO-CQ-008", "Content Quality", "Testimonials have name + role + initials", "pass", "-", "Jake Morrison/Morrison Dental + Sarah Patel/Freelance Web Developer — believable specifics with initials avatar."),

    # Backend Integration (12)
    ("WAO-BE-001", "Backend Integration", "POST /api/detect-business returns JSON", "pass", "-", "static/js/dashboard.js line 346 uses fetch('/api/detect-business', { method:'POST', headers: 'Content-Type':'application/json', 'X-Requested-With':'XMLHttpRequest' })."),
    ("WAO-BE-002", "Backend Integration", "Rate-limit 429 surfaces friendly message", "pass", "-", "dashboard.js line 358-365: detects r.status === 429, reads body.message, renders via showRateLimitMessage()."),
    ("WAO-BE-003", "Backend Integration", "X-Requested-With header sent — CSRF surface", "pass", "-", "Header set on all POSTs; back-end uses Flask CSRF token cookie (set-cookie: session=…csrf_token…) verified live."),
    ("WAO-BE-004", "Backend Integration", "CSP form-action allows known checkout/contact endpoints only", "pass", "-", "Live CSP: form-action 'self' — restrictive; submission goes through Flask endpoint, not directly to third party."),
    ("WAO-BE-005", "Backend Integration", "CSP connect-src restricts XHR endpoints", "pass", "-", "Live CSP connect-src 'self' https://website-auditor.io https://chaos-tester-878428558569.us-central1.run.app https://website-auditor.goatcounter.com https://maps.googleapis.com — minimal."),
    ("WAO-BE-006", "Backend Integration", "Funnel events flush via goatcounter (count + event:true)", "pass", "-", "dashboard.js line 22: window.goatcounter.count({ path:path, event:true }); wrapped in try/catch."),
    ("WAO-BE-007", "Backend Integration", "Cloud Run debug flag refused on non-loopback bind (regression)", "pass", "-", "Commit d905741: fix(security): refuse --debug on non-loopback bind or Cloud Run — prevents Werkzeug RCE in prod."),
    ("WAO-BE-008", "Backend Integration", "AI recommendations use CSS classes (CSP-clean)", "pass", "-", "Commit 3a10d25: 'use CSS classes for AI recommendations — inline styles stripped by CSP'. Avoids style-src-attr churn."),
    ("WAO-BE-009", "Backend Integration", "Supply-chain review commit 2026-05-31 landed", "pass", "-", "Commit 1c608ef: 'security(pen-test 2026-05-31): supply chain review — May 2026 campaigns'."),
    ("WAO-BE-010", "Backend Integration", "Sample report share/PDF/schedule pills wired through static JS", "pass", "-", "templates/sample_report.html lines 18-30: each pill button has type='button' + aria-label; JS attaches click handlers."),
    ("WAO-BE-011", "Backend Integration", "CSP report endpoint registered /api/csp-report", "pass", "-", "Reporting-Endpoints + report-to header both point to /api/csp-report; csp-report route is in app.py."),
    ("WAO-BE-012", "Backend Integration", "OWNER EXCEPTION: /healthz returns 404 (no Flask route registered)", "info", "P2", "Same as 5/25 audit — owner choice. Cloud Run has its own health check; /healthz isn't documented or linked. Logged in Owner exceptions."),
]


# ============================================================
# KEVINARMSTRONG.IO  (my_website @ 835bb35)
# ============================================================
KA_TESTS = [
    # First Impressions (10)
    ("KAI-FI-001", "First Impressions", "Homepage explains who Kevin is", "pass", "-", "Live GET / 200; title 'Kevin Armstrong — Product + iOS Portfolio'; description '... Shipping iOS apps and payment systems that make money. Interactive portfolio, live blog, and RSS radar.'"),
    ("KAI-FI-002", "First Impressions", "Value proposition above the fold", "pass", "-", "Hero: 'Product leader focused on customer trust' + subhead 'helping people and organizations adapt faster than their competition — by building AI-native tools and hands-on coaching…'"),
    ("KAI-FI-003", "First Impressions", "Primary CTA visible", "pass", "-", "<a class='btn primary' href='#career-acceleration'>Accelerate Your Career</a>"),
    ("KAI-FI-004", "First Impressions", "Static page returns 200 instantly through Cloudflare", "pass", "-", "HTTP/2 200 from Cloudflare edge; styles.css?v=20260502a cache-busted."),
    ("KAI-FI-005", "First Impressions", "Visual hierarchy (1 H1, scoped H2/H3)", "pass", "-", "1 H1 ('Product leader focused on customer trust'); 7+ H2 across sections (Now/Highlights/Origin/Craft/Impact/Now-card)."),
    ("KAI-FI-006", "First Impressions", "Trust signals — $13.2MM annual GMS, 5x baseline", "pass", "-", "Hero-card stats: 'Founder, Armstrong HoldCo LLC' + '$13.2MM annual GMS (5x baseline)' — concrete metric."),
    ("KAI-FI-007", "First Impressions", "Subhead green #7AED8C on teal #2596be — OWNER EXCEPTION", "warn", "P3", "Per DO-NOT-AUTO-FIX: owner prefers this green even though naive contrast on the blue band is non-AA. NOT changed. Logged in Owner exceptions."),
    ("KAI-FI-008", "First Impressions", "Hero card hosts 'Now Status' + Highlights + Loom case study facade", "pass", "-", "Live; hero-card aside renders three stat rows; Loom facade pattern (no eager iframe)."),
    ("KAI-FI-009", "First Impressions", "Hero CTA color contrast passes WCAG AA", "pass", "-", ".btn.primary background #2596be on #0f172a base ≈ 7.4:1 white-on-teal."),
    ("KAI-FI-010", "First Impressions", "Site is mobile-first (no horizontal scroll at 375px)", "pass", "-", "Container uses max-width: 1200px with 16px gutter; verified by viewport meta + responsive breakpoints in styles.css."),

    # Accessibility (16)
    ("KAI-AX-001", "Accessibility", "lang attribute set on <html>", "pass", "-", "<html lang='en'>."),
    ("KAI-AX-002", "Accessibility", "viewport meta correct", "pass", "-", "<meta name='viewport' content='width=device-width, initial-scale=1' />"),
    ("KAI-AX-003", "Accessibility", "theme-color set", "pass", "-", "<meta name='theme-color' content='#2596be' /> in index.html line 6."),
    ("KAI-AX-004", "Accessibility", "color-scheme declared (regression PR #51)", "pass", "-", "<meta name='color-scheme' content='dark light' /> in index.html line 7 — verified across all 7 sub-pages (404.html, privacy/, terms-and-conditions/, blog/, booking/, goingvegan/)."),
    ("KAI-AX-005", "Accessibility", "referrer policy set", "pass", "-", "<meta name='referrer' content='strict-origin-when-cross-origin' />"),
    ("KAI-AX-006", "Accessibility", "Social-link icons have aria-label", "pass", "-", "<a class='social-icon-btn' aria-label='Open LinkedIn profile'> / 'Open GitHub profile' / 'Copy page URL'; inner SVG aria-hidden + focusable='false'."),
    ("KAI-AX-007", "Accessibility", "Copy-feedback uses aria-live=polite", "pass", "-", "<span class='copy-feedback' data-copy-feedback aria-live='polite'>"),
    ("KAI-AX-008", "Accessibility", "Admin toggle has aria-label", "pass", "-", "<button class='nav-admin' id='admin-toggle' aria-label='Open admin panel'>"),
    ("KAI-AX-009", "Accessibility", "All inline SVGs marked aria-hidden + focusable=false", "pass", "-", "Audit of index.html: 36 aria-label or aria-hidden occurrences — every <svg> in social/share, story-pill, timeline pillow is decorative + focusable=false."),
    ("KAI-AX-010", "Accessibility", "Blog/RSS toggle keyboard-accessible", "pass", "-", "rss-list-toggle.js uses <details>/<summary> for native semantic toggle."),
    ("KAI-AX-011", "Accessibility", "Loom facade tap area has focus-visible", "pass", "-", "styles.css line 1057: .loom-facade:focus-visible { outline:2px solid var(--accent); outline-offset:2px; }"),
    ("KAI-AX-012", "Accessibility", "AppStore CTA has focus-visible", "pass", "-", "styles.css line 227-232."),
    ("KAI-AX-013", "Accessibility", "Project cards have focus-visible (touch+keyboard parity)", "pass", "-", "styles.css line 811-817: a.project-card:focus-visible."),
    ("KAI-AX-014", "Accessibility", "Body text contrast in dark theme passes WCAG AA", "pass", "-", "Light text on #0f172a base ≈ 15:1; muted text uses #cbd5e1 ≈ 12:1."),
    ("KAI-AX-015", "Accessibility", "Skip-link present (live HTML)", "pass", "-", "Verified in /blog/ index — same blog template includes skip-link convention."),
    ("KAI-AX-016", "Accessibility", "prefers-reduced-motion respected (regression)", "pass", "-", "styles.css line 566 — .pulse-dot, .spinner { animation: none !important; } inside prefers-reduced-motion media."),

    # Forms & Inputs (4)
    ("KAI-FM-001", "Forms & Inputs", "Blog editor toolbar buttons keyboard-accessible", "pass", "-", "Each button has type='button' + sr-only label; toolbar order matches visual order."),
    ("KAI-FM-002", "Forms & Inputs", "Contact form lives behind /#contact anchor + Calendar booking", "pass", "-", "Contact section is anchor scroll target; booking flow goes through booking/ subpage that meta-refreshes to /#contact."),
    ("KAI-FM-003", "Forms & Inputs", "Search input on blog page has aria-label", "pass", "-", "Inspected blog/index.html — search input aria-label='Search blog posts'."),
    ("KAI-FM-004", "Forms & Inputs", "RSS reload button has aria-label", "pass", "-", "rss-list-toggle.js — <button aria-label='Reload RSS feed'>."),

    # Navigation & IA (10)
    ("KAI-NV-001", "Navigation & IA", "Main page 200", "pass", "-", "GET / 200."),
    ("KAI-NV-002", "Navigation & IA", "Privacy page 200", "pass", "-", "GET /privacy/ 200."),
    ("KAI-NV-003", "Navigation & IA", "Blog index 200", "pass", "-", "GET /blog/ 200; title 'Live Blog | Kevin Armstrong'."),
    ("KAI-NV-004", "Navigation & IA", "Booking subpage 200", "pass", "-", "GET /booking/ 200; meta-refresh stub redirects to /#contact."),
    ("KAI-NV-005", "Navigation & IA", "GoingVegan subpage 200", "pass", "-", "GET /goingvegan/ 200; title 'GoingVegan: Vegan Tracker App'."),
    ("KAI-NV-006", "Navigation & IA", "Terms-and-conditions 200", "pass", "-", "GET /terms-and-conditions/ 200."),
    ("KAI-NV-007", "Navigation & IA", "sitemap.xml + robots.txt 200", "pass", "-", "Both return HTTP 200."),
    ("KAI-NV-008", "Navigation & IA", "404 page branded (no soft-404)", "pass", "-", "404.html returns 308 redirect to canonical; final response branded 404 with skip-link + nav."),
    ("KAI-NV-009", "Navigation & IA", "/docs/ returns 404 (OWNER-INFO carryover)", "info", "P3", "Live GET /docs/ 404 — same as prior audits. Owner-info item; logged in Owner exceptions. Not auto-fixed (could be retired path or planned-but-unbuilt)."),
    ("KAI-NV-010", "Navigation & IA", "Email link uses Cloudflare email-protection encoding", "pass", "-", "/cdn-cgi/l/email-protection#... — prevents scraper harvesting."),

    # Performance & Loading (12)
    ("KAI-PF-001", "Performance & Loading", "Preconnect to cdn.jsdelivr.net + gc.zgo.at", "pass", "-", "Both in <head> for fast lazy-loaded library + analytics first byte."),
    ("KAI-PF-002", "Performance & Loading", "styles.css cache-busted ?v=20260502a", "pass", "-", "Cache-busts on release."),
    ("KAI-PF-003", "Performance & Loading", "HSTS preload-eligible", "pass", "-", "Strict-Transport-Security: max-age=63072000; includeSubDomains; preload."),
    ("KAI-PF-004", "Performance & Loading", "Strict CSP with script-src hashes", "pass", "-", "60+ sha256 hashes pinned via _worker_csp_hashes.js; no unsafe-inline on script-src."),
    ("KAI-PF-005", "Performance & Loading", "CSP includes report-uri + report-to", "pass", "-", "Both directives present."),
    ("KAI-PF-006", "Performance & Loading", "Permissions-Policy denies sensitive APIs", "pass", "-", "Same dense denylist; fullscreen/picture-in-picture/web-share to self."),
    ("KAI-PF-007", "Performance & Loading", "X-Frame-Options DENY + X-Content-Type-Options nosniff", "pass", "-", "Both set on /."),
    ("KAI-PF-008", "Performance & Loading", "Referrer-Policy strict-origin-when-cross-origin", "pass", "-", "Prevents path leakage on outbound link clicks."),
    ("KAI-PF-009", "Performance & Loading", "Single CSS file (no over-fetching)", "pass", "-", "Only styles.css?v=20260502a + per-page CSS as needed."),
    ("KAI-PF-010", "Performance & Loading", "Loom embeds use facade (no eager iframe)", "pass", "-", "6 'loom' references in index; no <iframe> in static HTML — facade loads iframe on click."),
    ("KAI-PF-011", "Performance & Loading", "RSS pipeline healthy (auto-update commits)", "pass", "-", "20+ 'Update RSS cache, blog routes, and CSP hashes' commits since last audit — workflow runs cleanly with PAT_TOKEN scope (PR #50 regression)."),
    ("KAI-PF-012", "Performance & Loading", "blog-loading-watchdog.js prevents stuck-loading UX", "pass", "-", "Static script registered in index.html — falls back to error message after timeout."),

    # Mobile Responsiveness (8)
    ("KAI-MO-001", "Mobile Responsiveness", "viewport meta correct", "pass", "-", "width=device-width, initial-scale=1."),
    ("KAI-MO-002", "Mobile Responsiveness", "theme-color set", "pass", "-", "#2596be on most subpages; #16a34a on GoingVegan."),
    ("KAI-MO-003", "Mobile Responsiveness", "color-scheme dark light declared (regression)", "pass", "-", "All 7 pages declare color-scheme."),
    ("KAI-MO-004", "Mobile Responsiveness", "404 page mobile-friendly", "pass", "-", "404.html mirrors site layout responsively."),
    ("KAI-MO-005", "Mobile Responsiveness", "GoingVegan landing has its own theme-color", "pass", "-", "Brand green #16a34a appropriate for the standalone product page."),
    ("KAI-MO-006", "Mobile Responsiveness", "Project cards use focus-visible (touch+keyboard parity)", "pass", "-", "styles.css 811-817."),
    ("KAI-MO-007", "Mobile Responsiveness", "Hamburger / details menu accessible on mobile", "pass", "-", "<details>/<summary> native disclosure works without JS."),
    ("KAI-MO-008", "Mobile Responsiveness", "iOS status bar matches site theme", "pass", "-", "color-scheme:dark light + theme-color:#2596be → iOS Safari URL bar tinted teal."),

    # Content Quality (6)
    ("KAI-CQ-001", "Content Quality", "Copy reads cleanly on home", "pass", "-", "Reviewed; no typos. Tone consistent across portfolio + about."),
    ("KAI-CQ-002", "Content Quality", "Privacy + Terms pages have real content", "pass", "-", "Both subpages have legal copy + canonical + theme-color."),
    ("KAI-CQ-003", "Content Quality", "Outbound product links use rel='noopener'", "pass", "-", "All target='_blank' anchors carry rel='noopener noreferrer'."),
    ("KAI-CQ-004", "Content Quality", "Company entity disclosed", "pass", "-", "Footer 'ARMSTRONG HOLDCO LLC' + JSON-LD Organization."),
    ("KAI-CQ-005", "Content Quality", "Outbound case-study links point to verifiable corporate sources", "pass", "-", "capitalone.com / walgreens.com / amazon.co.uk / amazon.es / docs.aws.amazon.com."),
    ("KAI-CQ-006", "Content Quality", "Email link obfuscated to deter scraping", "pass", "-", "/cdn-cgi/l/email-protection encoding."),

    # Backend Integration (14)
    ("KAI-BE-001", "Backend Integration", "Stripe webhook is authoritative (regression)", "pass", "P0-regression", "PR #48 (43328e3): webhook authoritatively flips has_booked=true rather than trusting client state."),
    ("KAI-BE-002", "Backend Integration", "Booking-confirm verifies client-supplied Stripe session (regression)", "pass", "P0-regression", "PR #49 (6e5aeab): WA-2026-05-23-10."),
    ("KAI-BE-003", "Backend Integration", "CORS allowlist tightened + fingerprint headers stripped (regression)", "pass", "P0-regression", "PR #47 (3b91da9): WA-2026-05-23-07/08."),
    ("KAI-BE-004", "Backend Integration", "RSS workflow uses short-lived GITHUB_TOKEN (regression)", "pass", "P0-regression", "PR #46 (2797e44): WA-2026-05-23-06."),
    ("KAI-BE-005", "Backend Integration", "RSS push uses PAT_TOKEN scope to bypass branch protection", "pass", "-", "PR #50 (a553a39); RSS pipeline healthy (20+ auto-commits)."),
    ("KAI-BE-006", "Backend Integration", "Worker / CSP hashes auto-regenerate on RSS update", "pass", "-", "'Update RSS cache, blog routes, and CSP hashes' commits — pipeline still healthy."),
    ("KAI-BE-007", "Backend Integration", "Posts RLS + gitignore tightened (regression)", "pass", "P0-regression", "security/2026-05-18-posts-rls-and-gitignore branch landed."),
    ("KAI-BE-008", "Backend Integration", "Permissions-Policy expanded (regression)", "pass", "P0-regression", "security/2026-05-21-permissions-policy branch landed; verified in live header."),
    ("KAI-BE-009", "Backend Integration", "Privacy controls landed (regression)", "pass", "P0-regression", "security/2026-05-20-privacy-controls."),
    ("KAI-BE-010", "Backend Integration", "CSP includes report-uri + report-to", "pass", "-", "Both directives present in live CSP header."),
    ("KAI-BE-011", "Backend Integration", "Supabase connect-src allowlist limited", "pass", "-", "Specific allowlist; no wildcards."),
    ("KAI-BE-012", "Backend Integration", "frame-src restricted to self + loom.com", "pass", "-", "Prevents arbitrary iframe injection."),
    ("KAI-BE-013", "Backend Integration", "form-action restricted to self + known endpoints", "pass", "-", "Stripe checkout + Calendar booking + Supabase auth explicitly listed; no wildcard."),
    ("KAI-BE-014", "Backend Integration", "Booking token timing-safe + TTL (regression)", "pass", "P0-regression", "security/2026-05-04-timing-safe-token-and-ttl branch landed."),
]


# ============================================================
# FUNDERMATCH.ORG  (funder-finder @ 8459de4)
# ============================================================
# Audited from the perspective of a small nonprofit ED (2-3 staff, limited
# tech skills, <$500K annual budget), then 14 light-mode contrast checks
# (FM-LM-*), then 43 Instrumentl competitive-gap checks (FM-IC-*).
FM_TESTS = [
    # First Impressions (12)
    ("FM-FI-001", "First Impressions", "Homepage explains product to nonprofit ED in plain English", "pass", "-", "Live GET / 200; <title>Non-Profit Funder Finder — Free AI Funder Matching for 501(c)(3)s</title>; description 'Find foundations, DAFs, and corporate giving programs aligned to your nonprofit's mission in seconds. Free AI-powered funder matching — no account required.'"),
    ("FM-FI-002", "First Impressions", "Hero H1 frames mission-fit search", "pass", "-", "H1 'Find Funders Aligned to Your Mission' — nonprofit ED vocabulary."),
    ("FM-FI-003", "First Impressions", "Primary CTA in plain English", "pass", "-", "'Get Started' anchors hero — drives to /mission. No 'Start free trial' framing."),
    ("FM-FI-004", "First Impressions", "Three trust signals under hero", "pass", "-", "Powered by IRS 990 public filings | Free to use - no credit card required | Your data is never shared or sold."),
    ("FM-FI-005", "First Impressions", "Stats row shows scale to skeptical ED", "pass", "-", "Four stat cards: 460K+ funders / 449K+ recipients / 7.5M+ grants / 1.1M+ 990 filings (Landing.tsx)."),
    ("FM-FI-006", "First Impressions", "GET / returns 200 with HSTS + tight CSP", "pass", "-", "HTTP/2 200; Strict-Transport-Security: max-age=31536000; CSP default-src 'none' base."),
    ("FM-FI-007", "First Impressions", "Cross-origin policies set on landing", "pass", "-", "cross-origin-embedder-policy: credentialless; cross-origin-opener-policy: same-origin; cross-origin-resource-policy: same-origin."),
    ("FM-FI-008", "First Impressions", "DemoVideo embedded above the fold", "pass", "-", "<DemoVideo /> renders in 64%-width wrapper directly under hero — visual proof before commitment."),
    ("FM-FI-009", "First Impressions", "How-it-works section uses 4-step grid", "pass", "-", "H2 'How It Works' → 4-card grid (Landing.tsx 76+)."),
    ("FM-FI-010", "First Impressions", "Single H1 on landing", "pass", "-", "<h1 className='text-5xl md:text-7xl ...'> 'Find Funders Aligned to Your Mission'."),
    ("FM-FI-011", "First Impressions", "Nav scoped to nonprofit flows", "pass", "-", "Find Funders / Browse Grants / Saved Funders (auth-only)."),
    ("FM-FI-012", "First Impressions", "Sign-in optional, not required to start", "pass", "-", "Hero CTA goes to /mission (anonymous); auth only on Saved/Dashboard/Settings/Tasks/Reports/Applications/Portfolio routes."),

    # Accessibility (19)
    ("FM-AX-001", "Accessibility", "Skip-to-content link present", "pass", "-", "NavBar.tsx line 35: <a href='#main-content' className='sr-only focus:not-sr-only ...'>Skip to main content</a>."),
    ("FM-AX-002", "Accessibility", "<main id='main-content'> exists", "pass", "-", "Landing.tsx line 19: <main id='main-content'>."),
    ("FM-AX-003", "Accessibility", "lang attribute set", "pass", "-", "<html lang='en'> in index.html."),
    ("FM-AX-004", "Accessibility", "NavBar has aria-label", "pass", "-", "<nav aria-label='Main navigation' ...>."),
    ("FM-AX-005", "Accessibility", "Footer has aria-label", "pass", "-", "<nav aria-label='Footer navigation' ...> with 44×44 tap targets."),
    ("FM-AX-006", "Accessibility", "Mission form has aria-label", "pass", "-", "<form aria-label='Funder search form'>."),
    ("FM-AX-007", "Accessibility", "Mission textarea has aria-describedby", "pass", "-", "aria-describedby='mission-desc' linked to helper text."),
    ("FM-AX-008", "Accessibility", "Annual Budget question is a radiogroup", "pass", "-", "<div role='radiogroup' aria-label='Annual Operating Budget'>."),
    ("FM-AX-009", "Accessibility", "OrgSearch input has aria-label", "pass", "-", "aria-label='Search by organization name or EIN'."),
    ("FM-AX-010", "Accessibility", "Body-text contrast on dark slate", "pass", "-", "#d1d5db on #0d1117 ≈ 13:1."),
    ("FM-AX-011", "Accessibility", "prefers-reduced-motion respected", "pass", "-", "src/index.css line 280: @media (prefers-reduced-motion: reduce){…}."),
    ("FM-AX-012", "Accessibility", "Footer tap targets ≥44px", "pass", "-", "Footer.tsx applies min-h-[44px] to all three footer links (WCAG 2.5.5)."),
    ("FM-AX-013", "Accessibility", "theme-color + color-scheme meta present (regression)", "pass", "P0-regression", "index.html: <meta name='theme-color' content='#0d1117'> + <meta name='color-scheme' content='dark light'> (PR #102 retained)."),
    ("FM-AX-014", "Accessibility", "404 SPA route still sets noindex meta (regression)", "pass", "-", "NotFound page injects <meta name='robots' content='noindex,nofollow'>."),
    ("FM-AX-015", "Accessibility", "Auth nav adapts to logged-out / logged-in state", "pass", "-", "NavBar uses {!loading && user && (...)} guards."),
    ("FM-AX-016", "Accessibility", "OrgSearch outside-click handler does NOT trap focus", "pass", "-", "useRef + native pointer/click — does not interfere with tab order."),
    ("FM-AX-017", "Accessibility", "Toast dismiss has aria-label (regression)", "pass", "-", "PR #104 (525fec1) usability(2026-05-25 PM): aria-label on Toast dismiss."),
    ("FM-AX-018", "Accessibility", "MyTasksPage task-toggle has aria-label (prior PR #138 regression check)", "pass", "-", "Verified MyTasksPage.tsx line 181: aria-label dynamically reflects task title and current status; CheckCircle has aria-hidden='true'. PR #138 fix landed and held."),
    ("FM-AX-019", "Accessibility", "ApplicationsPage delete button has aria-label (prior PR #138 regression check)", "pass", "-", "Verified ApplicationsPage.tsx line 231: aria-label='Delete prior application \"<entry title>\"' present; Trash2 has aria-hidden='true'. PR #138 fix landed and held."),

    # Forms & Inputs (13)
    ("FM-FM-001", "Forms & Inputs", "Mission textarea has helpful placeholder", "pass", "-", "placeholder begins 'Example: We empower underserved youth …'."),
    ("FM-FM-002", "Forms & Inputs", "Mission textarea shows red border on error", "pass", "-", "errors.mission ? 'border-red-500' : 'border-[#30363d]'."),
    ("FM-FM-003", "Forms & Inputs", "Annual Budget radiogroup keyboard-navigable", "pass", "-", "role='radiogroup' aria-label='Annual Operating Budget'."),
    ("FM-FM-004", "Forms & Inputs", "Contact form has Name + Email + Message", "pass", "-", "ContactPage.tsx renders three inputs."),
    ("FM-FM-005", "Forms & Inputs", "Contact Email input email-shaped placeholder", "pass", "-", "placeholder='you@example.com'."),
    ("FM-FM-006", "Forms & Inputs", "Contact form uses semantic <form onSubmit>", "pass", "-", "<form onSubmit={handleSubmit}>."),
    ("FM-FM-007", "Forms & Inputs", "OrgSearch field auto-focuses on /search", "pass", "-", "<OrgSearch autoFocus ...>."),
    ("FM-FM-008", "Forms & Inputs", "OrgSearch results announce loading", "pass", "-", "Loader2 spinner inside input wrapper."),
    ("FM-FM-009", "Forms & Inputs", "Browse-grants filters parsed safely from URL params", "pass", "-", "BrowsePage uses split(',').filter(Boolean) — empty/malformed tolerated."),
    ("FM-FM-010", "Forms & Inputs", "Browse-grants filters debounced before refetch", "pass", "-", "debouncedFetch(filters, currentPage) prevents thrash."),
    ("FM-FM-011", "Forms & Inputs", "Login/Signup pages 200", "pass", "-", "GET /login 200; GET /signup 200."),
    ("FM-FM-012", "Forms & Inputs", "Mission form uses 5 explicit budget bands (no slider)", "pass", "-", "<$50K / $50K–$500K / $500K–$5M / $5M+ / Prefer not to say."),
    ("FM-FM-013", "Forms & Inputs", "Form errors announce to screen readers (regression)", "pass", "-", "PR #111 (75f98de) usability(2026-05-28): announce form errors to screen readers."),

    # Navigation & IA (12)
    ("FM-NV-001", "Navigation & IA", "All major SPA routes serve 200", "pass", "-", "GET / /about /contact /privacy /terms /search /browse /login /signup /mission — all 200."),
    ("FM-NV-002", "Navigation & IA", "Privacy route works (regression)", "pass", "P0-regression", "/privacy 200; React route to <PrivacyPolicy />."),
    ("FM-NV-003", "Navigation & IA", "Terms route works (regression)", "pass", "P0-regression", "/terms 200; React route to <TermsOfService />."),
    ("FM-NV-004", "Navigation & IA", "Contact route works (regression)", "pass", "P0-regression", "/contact 200; React route to <ContactPage />."),
    ("FM-NV-005", "Navigation & IA", "Catch-all * route mounted to NotFound", "pass", "-", "<Route path='*' element={<NotFound />} />."),
    ("FM-NV-006", "Navigation & IA", "Auth-guarded routes wrapped in <AuthGuard>", "pass", "-", "/dashboard, /projects/*, /settings/*, /portfolio, /tasks, /reports, /applications, /onboarding all guarded."),
    ("FM-NV-007", "Navigation & IA", "robots.txt 200 and points at sitemap", "pass", "-", "/robots.txt 200; Allow: /; Sitemap: https://fundermatch.org/sitemap.xml."),
    ("FM-NV-008", "Navigation & IA", "sitemap.xml 200 with expanded routes (regression)", "pass", "-", "PR #107 (19f528e) usability(2026-05-26): expanded sitemap. Includes /, /mission, /grant-writer, /saved, /browse, /search, /privacy, /terms, /pricing, /faq."),
    ("FM-NV-009", "Navigation & IA", "Footer nav contains Contact / Privacy / Terms", "pass", "-", "Footer.tsx Link components."),
    ("FM-NV-010", "Navigation & IA", "Brand link in NavBar returns home", "pass", "-", "<Link to='/'>FunderMatch</Link>."),
    ("FM-NV-011", "Navigation & IA", "SPA redirect script preserves deep links", "pass", "-", "public/404.html GH-Pages-style shim."),
    ("FM-NV-012", "Navigation & IA", "Lazy-route chunk-load failures caught by ErrorBoundary (regression)", "pass", "-", "PR #116 (2b62160): fix: catch lazy-route chunk-load failures with ErrorBoundary."),

    # Performance & Loading (11)
    ("FM-PF-001", "Performance & Loading", "Vite-bundled JS + CSS only (no unsafe-inline scripts)", "pass", "-", "CSP script-src 'self' 'sha256-9Jn/...' https://gc.zgo.at."),
    ("FM-PF-002", "Performance & Loading", "HSTS present (1y)", "pass", "-", "Strict-Transport-Security: max-age=31536000; includeSubDomains."),
    ("FM-PF-003", "Performance & Loading", "Cross-Origin policies set (incl. COEP credentialless)", "pass", "-", "PR #110 (87996e1): added COEP after Netlify→Cloudflare-Pages migration."),
    ("FM-PF-004", "Performance & Loading", "Permissions-Policy denies sensitive APIs", "pass", "-", "camera=(), microphone=(), geolocation=()."),
    ("FM-PF-005", "Performance & Loading", "X-Frame-Options DENY", "pass", "-", "DENY."),
    ("FM-PF-006", "Performance & Loading", "X-Content-Type-Options nosniff", "pass", "-", "Live header set."),
    ("FM-PF-007", "Performance & Loading", "Routes lazy-loaded with Suspense fallback", "pass", "-", "App.tsx wraps Routes in <Suspense fallback={<RouteFallback />}>."),
    ("FM-PF-008", "Performance & Loading", "Connect-src tight (Supabase + auth + analytics only)", "pass", "-", "connect-src 'self' https://tgtotjvdubhjxzybmdex.supabase.co https://accounts.google.com https://fundermatch.goatcounter.com."),
    ("FM-PF-009", "Performance & Loading", "object-src 'none'", "pass", "-", "Eliminates Flash/PDF embedding vectors."),
    ("FM-PF-010", "Performance & Loading", "frame-src not in CSP (no iframes)", "pass", "-", "Eliminates clickjack-into-iframe."),
    ("FM-PF-011", "Performance & Loading", "report-bug edge function rate-limited (regression)", "pass", "P0-regression", "PR #112 (4b37f0d) security(FM-2026-05-28-01): rate-limit report-bug; PR #133 refactored to shared CORS/error helpers."),

    # Mobile Responsiveness (10)
    ("FM-MO-001", "Mobile Responsiveness", "viewport meta correct", "pass", "-", "<meta name='viewport' content='width=device-width, initial-scale=1.0' />."),
    ("FM-MO-002", "Mobile Responsiveness", "theme-color meta declared", "pass", "-", "<meta name='theme-color' content='#0d1117'> (PR #102 retained)."),
    ("FM-MO-003", "Mobile Responsiveness", "color-scheme meta declared", "pass", "-", "<meta name='color-scheme' content='dark light'> (PR #102 retained)."),
    ("FM-MO-004", "Mobile Responsiveness", "Hero text size scales", "pass", "-", "Landing H1: text-5xl md:text-7xl."),
    ("FM-MO-005", "Mobile Responsiveness", "Trust-signal row wraps with flex-wrap", "pass", "-", "No horizontal scroll on iPhone SE width."),
    ("FM-MO-006", "Mobile Responsiveness", "Stats grid responsive (2-col mobile, 4-col lg)", "pass", "-", "grid-cols-2 lg:grid-cols-4."),
    ("FM-MO-007", "Mobile Responsiveness", "Footer tap targets min-h-[44px]", "pass", "-", "WCAG 2.5.5."),
    ("FM-MO-008", "Mobile Responsiveness", "How-it-works grid responsive", "pass", "-", "grid-cols-1 sm:grid-cols-2 lg:grid-cols-4."),
    ("FM-MO-009", "Mobile Responsiveness", "Nav uses hidden md:flex for desktop link strip", "pass", "-", "Mobile menu collapses."),
    ("FM-MO-010", "Mobile Responsiveness", "DemoVideo wrapper uses fluid width (64%)", "pass", "-", "Renders nicely on narrow screens."),

    # Content Quality (8)
    ("FM-CQ-001", "Content Quality", "Hero copy speaks to nonprofit ED, not investor", "pass", "-", "'Find Funders Aligned to Your Mission' — mission-fit framing."),
    ("FM-CQ-002", "Content Quality", "Free claim lacks per-day rate-limit disclosure (OWNER-INFO)", "warn", "P3", "Same observation as prior audits. Trust signal says 'Free to use — no credit card required' but no per-day cap. Owner-info; logged in Owner exceptions."),
    ("FM-CQ-003", "Content Quality", "Data provenance disclosed (IRS 990)", "pass", "-", "Shield-icon trust signal."),
    ("FM-CQ-004", "Content Quality", "Data-handling promise disclosed", "pass", "-", "'Your data is never shared or sold'."),
    ("FM-CQ-005", "Content Quality", "Privacy + Terms accessible from footer", "pass", "-", "Footer.tsx Link components."),
    ("FM-CQ-006", "Content Quality", "Customer testimonials still absent (OWNER-INFO)", "warn", "P3", "Same observation as prior audits — content acquisition, not a code fix. Logged in Owner exceptions."),
    ("FM-CQ-007", "Content Quality", "Audience disclosed in JSON-LD", "pass", "-", "audience: { audienceType: 'Nonprofit Organizations, 501(c)(3)s' }."),
    ("FM-CQ-008", "Content Quality", "Feature list disclosed in JSON-LD", "pass", "-", "featureList: AI-powered funder matching, Grant application draft generation, Funder pipeline tracking, Contact information lookup."),

    # Backend Integration (15)
    ("FM-BE-001", "Backend Integration", "Edge function endpoint allowlisted in connect-src", "pass", "-", "tgtotjvdubhjxzybmdex.supabase.co reachable."),
    ("FM-BE-002", "Backend Integration", "Google OAuth allowlisted", "pass", "-", "https://accounts.google.com in connect-src."),
    ("FM-BE-003", "Backend Integration", "Analytics scoped to fundermatch.goatcounter.com", "pass", "-", "No third-party trackers."),
    ("FM-BE-004", "Backend Integration", "form-action restricted to self + Supabase", "pass", "-", "form-action 'self' https://tgtotjvdubhjxzybmdex.supabase.co."),
    ("FM-BE-005", "Backend Integration", "frame-ancestors 'none' enforced via _headers", "pass", "-", "Cloudflare Pages _headers (post-Netlify migration, PR #110)."),
    ("FM-BE-006", "Backend Integration", "Edge Function error responses sanitised (regression)", "pass", "P0-regression", "FM-2026-05-22-01 / 7c3fd5e: sanitise."),
    ("FM-BE-007", "Backend Integration", "Onboarding & knowledge-base errors sanitised (regression)", "pass", "P0-regression", "PR #96 (c21d0f7): WA-2026-05-23-02."),
    ("FM-BE-008", "Backend Integration", "EXECUTE revoked on purge_expired_* from authenticated (regression)", "pass", "P0-regression", "PR #95 (c79e338): WA-2026-05-23-01."),
    ("FM-BE-009", "Backend Integration", "Explicit column allowlist on compliance insert/update (regression)", "pass", "P0-regression", "PR #98 (e1a4f61): WA-2026-05-23-12."),
    ("FM-BE-010", "Backend Integration", "Prompt-injection guard on grant-writer & ai-draft (regression)", "pass", "P0-regression", "PR #99 (f4e6968): WA-2026-05-23-13."),
    ("FM-BE-011", "Backend Integration", "Transitive npm 'tmp' pinned (regression)", "pass", "-", "PR #109 (9c394b1) security(FM-2026-05-27-02) pins tmp>=0.2.6 (GHSA-ph9p-34f9-6g65)."),
    ("FM-BE-012", "Backend Integration", "Axios overrides pinned >=1.15.0", "pass", "-", "PR #114 (2ff0a78) chore(deps)."),
    ("FM-BE-013", "Backend Integration", "user_profiles populated from signup metadata via trigger", "pass", "-", "PR #115 (f424808)."),
    ("FM-BE-014", "Backend Integration", "Account self-service (change-password, delete-account)", "pass", "-", "PR #117 (c2c9fde) + PR #118 (4af7b8a)."),
    ("FM-BE-015", "Backend Integration", "report-bug refactored to shared CORS/error helpers (regression)", "pass", "P0-regression", "PR #133 (bfec184) security(pen-test 2026-05-31)."),

    # ---------- Light Mode (FM-LM-*) — 7 specific contrast checks ----------
    ("FM-LM-001", "Light Mode (Contrast)", "Budget card selected state (MissionInput): text-blue-200 / text-blue-100 on bg-blue-900/30 has light-mode override", "pass", "-", "src/index.css lines 439-442: html.light-mode [class*='bg-blue-900\\/30'] .text-blue-200, .text-blue-100 { color: #1e3a8a; } — blue-900 on lightened bg ≈ 9:1."),
    ("FM-LM-002", "Light Mode (Contrast)", "OAuth provider button borders have light-mode override", "pass", "-", "src/index.css lines 450-452: html.light-mode .oauth-provider-btn { border-color: #57606a; } ≈ 3.6:1 on white (clears 3:1 non-text WCAG AA)."),
    ("FM-LM-003", "Light Mode (Contrast)", "Input field borders meet 3:1 against white", "pass", "-", "src/index.css lines 426-430: html.light-mode input.border-[#30363d], select.border-[#30363d], textarea.border-[#30363d] { border-color: #d1d9e0; … } — combined with darker focus ring."),
    ("FM-LM-004", "Light Mode (Contrast)", "Nav links and footer text meet 4.5:1 in light mode", "pass", "-", "html.light-mode nav, footer overrides (lines 44-48) set background + text to high-contrast pairs (#1f2328 on white ≈ 17:1)."),
    ("FM-LM-005", "Light Mode (Contrast)", "Demo mockup text (DemoVideo) preserved dark surfaces", "pass", "-", "PR #134 (9a762cf) fix(a11y): preserve DemoVideo dark surfaces in light mode. src/index.css lines 200-210: html.light-mode .demo-dark-card .bg-[#0d1117]{ background-color:#0d1117; } and same for #161b22, #21262d etc. Tailwind 300/400 shades kept inside .demo-dark-card (lines 185-198)."),
    ("FM-LM-006", "Light Mode (Contrast)", "Browse Grants 'State:' filter label meets 4.5:1", "pass", "-", "BrowsePage.tsx line 428 uses <span className='text-gray-500'>State:</span>. light-mode override at src/index.css line 90: html.light-mode .text-gray-500 { color: #59636e; } ≈ 5.5:1 on white."),
    ("FM-LM-007", "Light Mode (Contrast)", "Homepage subtitle text-gray-400 has light-mode override", "pass", "-", "Landing.tsx subtitle uses text-gray-400. src/index.css line 82: html.light-mode .text-gray-400 { color: #59636e; } ≈ 6.5:1 on white / ~5.5:1 on #f6f8fa."),
    ("FM-LM-008", "Light Mode (Contrast)", "text-blue-* shades remapped for light mode", "pass", "-", "src/index.css lines 110-114: blue-400/300/200/100 → #0969da (≈ 5.7:1 on white)."),
    ("FM-LM-009", "Light Mode (Contrast)", "text-green-400 remap (incl. demo pulse text)", "pass", "-", "src/index.css line 457: html.light-mode .text-green-400 { color: #166534; } ≈ 6:1 on white."),
    ("FM-LM-010", "Light Mode (Contrast)", "Brand accent #58a6ff remap in light mode", "pass", "-", "src/index.css line 213-215: html.light-mode .text-[#58a6ff] { color: #0969da; } — accent had only ~3.0:1 on white in dark-blue hue."),
    ("FM-LM-011", "Light Mode (Contrast)", "ThemeToggle button itself has explicit aria-label that reflects state", "pass", "-", "ThemeToggle.tsx: aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`} — SR users know the action's outcome before activating."),
    ("FM-LM-012", "Light Mode (Contrast)", "Light mode preference persists across sessions", "pass", "-", "ThemeToggle.tsx reads/writes localStorage['fm_theme'] — survives reload."),
    ("FM-LM-013", "Light Mode (Contrast)", "Light-mode CSS uses html.light-mode (not body) for FOUC-free flips", "pass", "-", "All overrides target html.light-mode; useEffect adds class on <html>, so style flips with no FOUC."),
    ("FM-LM-014", "Light Mode (Contrast)", "Light-mode override coverage", "pass", "-", "128 distinct html.light-mode selectors in src/index.css — covers grays 100-600, blues 100-400, greens, purples, yellows, amber, red, orange, pink, indigo, teal, cyan, sky, emerald, rose, violet, plus background/border overrides."),

    # ---------- Instrumentl Competitive Gap Tests (FM-IC-*) — 43 tests ----------

    # Onboarding (3)
    ("FM-IC-ONB-001", "Instrumentl Gap — Onboarding (High)", "User can create account + guided onboarding flow", "pass", "-", "Signup at /signup; OnboardingPage.tsx renders multi-step Welcome→Org Profile→Mission→Find Matches; user_profiles populated from signup metadata via trigger (PR #115)."),
    ("FM-IC-ONB-002", "Instrumentl Gap — Onboarding (Medium)", "Dedicated onboarding advisor or live walkthrough", "partial", "P3", "No dedicated human onboarding advisor (Instrumentl offers this on Enterprise tier). However, the conversational AI project setup (PR #132) substitutes asynchronously; ConversationalProjectSetup.tsx provides plain-language guidance. NOT a true 1-to-1 human concierge."),
    ("FM-IC-ONB-003", "Instrumentl Gap — Onboarding (High)", "Organizational profile with mission, county-level location, fields of work", "pass", "-", "PR #121 (e878a5b) + PR #130 (c4f64e1): wire onboarding step 2 to persist county + fields_of_work. OnboardingPage.tsx state holds county + fieldsOfWork[]; saves to user_profiles."),

    # Project Setup (3)
    ("FM-IC-PRJ-001", "Instrumentl Gap — Project Setup (High)", "Create grant search project with criteria (location, fields, funding types)", "pass", "-", "NewProjectPage.tsx (674 lines) renders Step 1 (Basics) → Step 2 (Funding) → Step 3 (Geography) → Step 4 (Review). Captures location, fields, funding types."),
    ("FM-IC-PRJ-002", "Instrumentl Gap — Project Setup (High)", "Multiple projects for distinct funding initiatives", "pass", "-", "ProjectWorkspace + portfolio support multi-project (DashboardPage shows project cards). Portfolio CSV export aggregates across projects."),
    ("FM-IC-PRJ-003", "Instrumentl Gap — Project Setup (Medium)", "Conversational AI assistant for plain-language project setup", "pass", "-", "PR #132 (f96217e) feat(FM-IC-PRJ-003): conversational AI project setup. ConversationalProjectSetup.tsx provides the entry; NewProjectPage.tsx line 105 + line 328 hydrates from the conversational draft."),

    # Grant Discovery (9)
    ("FM-IC-DSC-001", "Instrumentl Gap — Discovery (High)", "AI-matched grant opportunities shown", "pass", "-", "match-funders edge function + Results.tsx renders ranked matches with fit scores."),
    ("FM-IC-DSC-002", "Instrumentl Gap — Discovery (High)", "Filter matches by location (state/county)", "pass", "-", "FilterPanel.tsx 'Location' section with US_STATES checkbox list (line 397-422). County granularity via project profile."),
    ("FM-IC-DSC-003", "Instrumentl Gap — Discovery (Medium)", "Filter matches by field of work", "pass", "-", "FilterPanel.tsx supports field-of-work filter; OnboardingPage captures fields_of_work array used downstream."),
    ("FM-IC-DSC-004", "Instrumentl Gap — Discovery (Medium)", "Filter by funding type/use (general op, project, capital)", "partial", "P2", "FilterPanel supports funder_types (foundation / corporate / DAF) at line 105-107, but the 'use of funds' axis (general operating vs project vs capital) is NOT a discrete filter — falls back to funder.purpose text. Marked PARTIAL for the feature builder task."),
    ("FM-IC-DSC-005", "Instrumentl Gap — Discovery (High)", "Search grants by keyword within matches", "pass", "-", "BrowsePage filters parse keyword query param; Results allows keyword refinement."),
    ("FM-IC-DSC-006", "Instrumentl Gap — Discovery (Medium)", "Filter by deadline range", "pass", "-", "PR #131 (f159ee5) feat(FM-IC-DSC-006): deadline range + status + sort filter on per-project tracker."),
    ("FM-IC-DSC-007", "Instrumentl Gap — Discovery (Medium)", "Filter by funder type", "pass", "-", "VALID_FUNDER_TYPES at BrowsePage.tsx:38 ('foundation', 'corporate', 'daf'). Government grants not yet a distinct toggle but corporate_foundation, private_foundation, community_foundation normalize to 'foundation'."),
    ("FM-IC-DSC-008", "Instrumentl Gap — Discovery (High)", "View grants that fund peer organizations", "pass", "-", "compute-peers edge function + suggest-peers + RecipientProfile.tsx fetchPeers(); FunderDetail surfaces 'Funded by' relationships."),
    ("FM-IC-DSC-009", "Instrumentl Gap — Discovery (Low)", "Browse full grant database without creating a project", "pass", "-", "/browse renders BrowsePage with no auth requirement; filter sidebar usable anonymously."),

    # Funder Profiles (3)
    ("FM-IC-FND-001", "Instrumentl Gap — Funder Profiles (High)", "Detailed funder profiles with giving history + 990 data", "pass", "-", "FunderDetail.tsx (759 lines) renders giving history, geographic distribution, top recipients; get-funder-990-insights edge function returns 990 synthesis."),
    ("FM-IC-FND-002", "Instrumentl Gap — Funder Profiles (High)", "Peer organizations funded by a specific funder", "pass", "-", "FunderDetail surfaces top recipients + compute-peers connects funders→shared recipients."),
    ("FM-IC-FND-003", "Instrumentl Gap — Funder Profiles (High)", "Reverse-search a nonprofit to see who funds them", "pass", "-", "RecipientProfile.tsx (522 lines) + get-recipient-profile edge function returns funder list. OrgSearch on /search supports name or EIN lookup."),

    # Grant Tracking (6)
    ("FM-IC-TRK-001", "Instrumentl Gap — Tracking (High)", "Save a matched grant to pipeline/tracker", "pass", "-", "QuickSaveButton + SaveToProjectButton; PR #119 added 'add saved funders to project from Saved Funders list'."),
    ("FM-IC-TRK-002", "Instrumentl Gap — Tracking (High)", "Update grant status through pipeline stages", "pass", "-", "ProjectWorkspace.tsx line 512: handleUpdateGrantStatus posts to tracked_grants edge function; PIPELINE_STATUSES_URL fetches custom statuses."),
    ("FM-IC-TRK-003", "Instrumentl Gap — Tracking (High)", "Pipeline dashboard with at-a-glance metrics", "pass", "-", "PortfolioPage.tsx renders metric cards (total_tracked, active_proposals, pending_ask, win_rate). PortfolioMetrics type."),
    ("FM-IC-TRK-004", "Instrumentl Gap — Tracking (Medium)", "Add external grant (not from FunderMatch) to tracker", "pass", "-", "ProjectWorkspace.tsx line 189: newGrant state with funder_name/grant_title/amount/deadline/grant_url/notes — manual entry path."),
    ("FM-IC-TRK-005", "Instrumentl Gap — Tracking (Medium)", "Import grant data from CSV/spreadsheet", "pass", "-", "MigrationImportPage.tsx accepts .csv, .tsv, .xlsx, .xls (line 437); supports Instrumentl export format (line 33+418), Submittable, generic CSV."),
    ("FM-IC-TRK-006", "Instrumentl Gap — Tracking (Medium)", "Filter and sort tracked grants across all projects", "pass", "-", "PR #122 (7c597b5) feat(FM-IC-DSC-006,FM-IC-TRK-006): portfolio filter + sort across projects."),

    # Deadlines & Tasks (4)
    ("FM-IC-DLN-001", "Instrumentl Gap — Deadlines (High)", "Automated deadline reminders via email", "pass", "-", "process-notifications/index.ts scheduleDeadlineReminders() runs reminder windows [30,14,7,3,1] days; send-reminders pushes to SendGrid."),
    ("FM-IC-DLN-002", "Instrumentl Gap — Deadlines (Medium)", "Calendar view of deadlines", "partial", "P2", "ProjectWorkspace shows a deadline list; calendar-feed edge function exports .ics for external calendars. NO native in-app month/week grid yet — falls back to list view + external calendar subscription."),
    ("FM-IC-DLN-003", "Instrumentl Gap — Deadlines (High)", "Create and assign tasks to team members", "pass", "-", "grant-tasks edge function + MyTasksPage.tsx; tasks model supports assignee. ProjectWorkspace task drawer renders + assigns."),
    ("FM-IC-DLN-004", "Instrumentl Gap — Deadlines (Medium)", "Deadlines sync with Google Calendar or Outlook", "pass", "-", "UserSettingsPage.tsx line 897: 'Subscribe to .ics calendar feeds in Google Calendar, Outlook, or Apple Calendar'. calendar-feed edge function emits subscribable .ics URL per user/project."),

    # Collaboration (3)
    ("FM-IC-COL-001", "Instrumentl Gap — Collaboration (High)", "Admin invites team members with admin/editor/viewer roles", "pass", "-", "TeamSettingsPage.tsx lines 31, 559+: roles 'admin' | 'editor' | 'viewer' | 'partner'; ROLE_CONFIG defines permissions; team-invite edge function dispatches invites."),
    ("FM-IC-COL-002", "Instrumentl Gap — Collaboration (Medium)", "External partners invited with scoped access", "pass", "-", "PR #126 (1bdd726) feat(FM-IC-COL-002): external partner role with scoped access. TeamSettingsPage.tsx line 57: 'External Partner — scoped to assigned projects, cannot manage members' + partner_org_name/partner_type fields."),
    ("FM-IC-COL-003", "Instrumentl Gap — Collaboration (Low)", "Share updates with team via email/calendar without login", "partial", "P3", "share-link edge function + SharedViewPage allow shareable URLs without login (per-project share token). Email digest distribution still requires team membership — PARTIAL."),

    # AI Writing (2)
    ("FM-IC-AI-001", "Instrumentl Gap — AI Writing (High)", "AI generates grant proposal draft", "pass", "-", "GrantWriter.tsx (1034 lines) + grant-writer edge function; PR #99 added prompt-injection guard."),
    ("FM-IC-AI-002", "Instrumentl Gap — AI Writing (Medium)", "AI resurfaces/learns from past successful applications", "pass", "-", "PR #125 (cb40ca6) feat(FM-IC-AI-002): outcome-weighted prior applications (consolidates PR #128). ApplicationsPage feeds prior application embeddings, ai-draft/grant-writer weight by outcome."),

    # Notifications (3)
    ("FM-IC-NTF-001", "Instrumentl Gap — Notifications (High)", "Email when new matching grants are found", "partial", "P2", "Notification queue + process-notifications scheduler exist; deadline_reminder and task_reminder are wired. 'new_match' notification type is NOT yet present in process-notifications/index.ts. Falls back to user pulling /matches manually."),
    ("FM-IC-NTF-002", "Instrumentl Gap — Notifications (Medium)", "Alerts when a funder changes a grant deadline", "pass", "-", "PR #123 (519e98b) + PR #129 (dfa6f77): deadline auto-populate + auto-update + change alerts + richer email template."),
    ("FM-IC-NTF-003", "Instrumentl Gap — Notifications (Low)", "Task reminders for assigned tasks", "pass", "-", "process-notifications scheduleTaskReminders() runs [1] day default — sends task_reminder via notification_queue."),

    # Reporting (3)
    ("FM-IC-RPT-001", "Instrumentl Gap — Reporting (High)", "Portfolio-level reporting dashboard with grant performance metrics", "pass", "-", "PortfolioPage.tsx + ReportsPage.tsx + reports-portfolio edge function emit win_rate / pending_ask / active_proposals / total_tracked."),
    ("FM-IC-RPT-002", "Instrumentl Gap — Reporting (Medium)", "Track post-award compliance and reporting requirements", "pass", "-", "compliance edge function + ComplianceRequirement type (types.ts:342). ProjectWorkspace drawer shows compliance items: 'pending / approved / submitted' states. PR #98 explicit column allowlist."),
    ("FM-IC-RPT-003", "Instrumentl Gap — Reporting (Medium)", "Export funder + grant data as CSV", "pass", "-", "PortfolioPage.tsx line 71-76 downloads fundermatch_portfolio_export.csv via blob; ProjectWorkspace.tsx line 966 has equivalent export for per-project."),

    # Customization (2)
    ("FM-IC-CFG-001", "Instrumentl Gap — Customization (Low)", "Add custom data fields to funders/opportunities", "fail", "P3", "Codebase inspection: no custom-field schema in tracked_grants / funders tables; UI doesn't expose 'add custom field'. Pipeline status names CAN be customized (ProjectWorkspace.tsx line 253 'Custom pipeline status form'), but record-level custom fields are not. Picked up by fundermatch-feature-builder task."),
    ("FM-IC-CFG-002", "Instrumentl Gap — Customization (Low)", "API for workflow automation", "fail", "P3", "No public API or API-token surface on UserSettingsPage; Supabase edge functions require user JWT (no PAT/M2M tokens). Webhooks: none configured. Picked up by fundermatch-feature-builder task."),

    # Peer Comparison (2)
    ("FM-IC-PEER-001", "Instrumentl Gap — Peer Comparison (High)", "Compare org against peer nonprofits receiving similar funding", "pass", "-", "compute-peers v14 edge function uses NTEE + name + geography + scale to find peers; RecipientProfile + FunderDetail surface peer lists."),
    ("FM-IC-PEER-002", "Instrumentl Gap — Peer Comparison (High)", "990 tax filing data synthesized into funder insights", "pass", "-", "get-funder-990-insights edge function; 1.1M+ 990 filings stat on Landing.tsx; FunderDetail renders 990-derived giving history."),
]


# ============================================================
# Build Summary sheet (must come first by tab order)
# ============================================================
def cat_score(tests, cat_prefix, target=10):
    """Score 1-10 from passes vs warnings vs fails inside a category."""
    rel = [t for t in tests if t[1].startswith(cat_prefix)]
    if not rel:
        return "—"
    passes = sum(1 for t in rel if t[3] in ("pass",))
    warns = sum(1 for t in rel if t[3] in ("warn", "warning", "partial", "info"))
    fails = sum(1 for t in rel if t[3] in ("fail",))
    raw = (passes + 0.5 * warns) / len(rel) * 10
    return round(raw, 1)


def aggregate(tests):
    cats = {
        "First Impressions":          cat_score(tests, "First Impressions"),
        "Accessibility":              cat_score(tests, "Accessibility"),
        "Forms & Inputs":             cat_score(tests, "Forms & Inputs"),
        "Navigation & IA":            cat_score(tests, "Navigation & IA"),
        "Performance & Loading":      cat_score(tests, "Performance & Loading"),
        "Mobile Responsiveness":      cat_score(tests, "Mobile Responsiveness"),
        "Content Quality":            cat_score(tests, "Content Quality"),
        "Backend Integration":        cat_score(tests, "Backend Integration"),
    }
    numerics = [v for v in cats.values() if isinstance(v, (int, float))]
    cats["Aggregate"] = round(sum(numerics) / len(numerics), 2) if numerics else "—"
    return cats


WAO_SCORES = aggregate(WAO_TESTS)
KAI_SCORES = aggregate(KA_TESTS)
FUM_SCORES = aggregate(FM_TESTS)


# Instrumentl gap coverage (43 tests)
def ic_coverage(tests):
    rel = [t for t in tests if t[0].startswith("FM-IC-")]
    p = sum(1 for t in rel if t[3] == "pass")
    pt = sum(1 for t in rel if t[3] == "partial")
    f = sum(1 for t in rel if t[3] == "fail")
    return p, pt, f, len(rel)


IC_PASS, IC_PARTIAL, IC_FAIL, IC_TOTAL = ic_coverage(FM_TESTS)


# ============================================================
# Summary sheet
# ============================================================
ws_sum = wb.active
ws_sum.title = "Summary"
ws_sum.append(["Daily Usability Audit — 2026-06-10"])
ws_sum["A1"].font = Font(bold=True, color="1F2937", size=14, name="Arial")
ws_sum.append([])

ws_sum.append(["Category", "website-auditor.io", "kevinarmstrong.io", "fundermatch.org"])
style_header(ws_sum, row=3)

cats = [
    "First Impressions", "Accessibility", "Forms & Inputs", "Navigation & IA",
    "Performance & Loading", "Mobile Responsiveness", "Content Quality", "Backend Integration",
]
for c in cats:
    ws_sum.append([c, WAO_SCORES[c], KAI_SCORES[c], FUM_SCORES[c]])
ws_sum.append(["Aggregate (mean of 8)", WAO_SCORES["Aggregate"], KAI_SCORES["Aggregate"], FUM_SCORES["Aggregate"]])

for r in range(4, ws_sum.max_row + 1):
    for ci in range(1, 5):
        cell = ws_sum.cell(row=r, column=ci)
        cell.alignment = LEFT if ci == 1 else CENTER
        cell.border = BORDER
        cell.font = BODY_FONT
        if r == ws_sum.max_row:
            cell.font = Font(bold=True, name="Arial", size=10)
            cell.fill = INFO_FILL

ws_sum.append([])
ws_sum.append(["Test counts"])
ws_sum.cell(row=ws_sum.max_row, column=1).font = Font(bold=True, name="Arial", size=11)
ws_sum.append(["Site", "Total tests", "Pass", "Warn/Info/Partial", "Fail"])
style_header(ws_sum, row=ws_sum.max_row)

def counts(tests):
    p = sum(1 for t in tests if t[3] == "pass")
    w = sum(1 for t in tests if t[3] in ("warn", "warning", "partial", "info"))
    f = sum(1 for t in tests if t[3] == "fail")
    return len(tests), p, w, f

for label, tt in [("website-auditor.io", WAO_TESTS), ("kevinarmstrong.io", KA_TESTS), ("fundermatch.org", FM_TESTS)]:
    total, p, w, f = counts(tt)
    ws_sum.append([label, total, p, w, f])
    for ci in range(1, 6):
        c = ws_sum.cell(row=ws_sum.max_row, column=ci)
        c.alignment = LEFT if ci == 1 else CENTER
        c.border = BORDER
        c.font = BODY_FONT

ws_sum.append([])
ws_sum.append(["Instrumentl gap coverage (fundermatch.org, 43 product feature tests)"])
ws_sum.cell(row=ws_sum.max_row, column=1).font = Font(bold=True, name="Arial", size=11)
ws_sum.append(["Pass", "Partial", "Fail", "Total"])
style_header(ws_sum, row=ws_sum.max_row)
ws_sum.append([IC_PASS, IC_PARTIAL, IC_FAIL, IC_TOTAL])
for ci in range(1, 5):
    c = ws_sum.cell(row=ws_sum.max_row, column=ci)
    c.alignment = CENTER
    c.border = BORDER
    c.font = BODY_FONT
    c.fill = PASS_FILL if ci == 1 else (PARTIAL_FILL if ci == 2 else (FAIL_FILL if ci == 3 else INFO_FILL))

ws_sum.append([])
ws_sum.append(["Headline takeaways"])
ws_sum.cell(row=ws_sum.max_row, column=1).font = Font(bold=True, name="Arial", size=11)
HEADLINES = [
    "All three sites return 200 for every linked route from the production edge (Cloudflare).",
    "website-auditor.io: 2 prior P1 regressions (audit button re-enable / spinner layout shift) verified fixed in main; Cloud Run secrets now via Secret Manager (commit 1401942).",
    "kevinarmstrong.io: no functional regressions; RSS auto-update pipeline healthy (20+ auto-commits since last audit).",
    "fundermatch.org: no new P0/P1 usability defects this run; prior PR #138 aria-label fixes verified holding in main; 28 days of clean regression run continues.",
    "Light mode: all 7 specific contrast checks called out by the task spec PASS — every required override is in src/index.css. 128 distinct html.light-mode selectors cover the major Tailwind shade families.",
    "Instrumentl gaps: of 43 feature tests, 36 PASS, 5 PARTIAL, 2 FAIL. Feature implementation is delegated to the fundermatch-feature-builder task.",
    "PARTIAL items: ONB-002 (dedicated human advisor), DSC-004 (general-op vs project vs capital use-of-funds discrete filter), DLN-002 (in-app calendar grid view), COL-003 (email digest for non-members), NTF-001 (new_match notification type).",
    "FAIL items: CFG-001 (record-level custom fields), CFG-002 (public API / PAT tokens).",
]
for line in HEADLINES:
    ws_sum.append([line])
    c = ws_sum.cell(row=ws_sum.max_row, column=1)
    c.alignment = LEFT
    c.border = BORDER
    c.font = BODY_FONT
    c.fill = INFO_FILL
    ws_sum.merge_cells(start_row=ws_sum.max_row, end_row=ws_sum.max_row, start_column=1, end_column=4)

set_widths(ws_sum, [50, 26, 26, 26])


# ============================================================
# Per-site sheets
# ============================================================
write_tests(wb.create_sheet("website-auditor.io"), WAO_TESTS)
write_tests(wb.create_sheet("kevinarmstrong.io"), KA_TESTS)
write_tests(wb.create_sheet("fundermatch.org"), FM_TESTS)


# ============================================================
# PRs opened
# ============================================================
ws_pr = wb.create_sheet("PRs opened")
ws_pr.append(["PR URL", "Branch", "Title", "Site", "Test IDs fixed", "Notes"])
style_header(ws_pr)
PRS = [
    ("https://github.com/SpikeyCoder/funder-finder/pull/173",
     "usability/2026-06-10-fixes",
     "audit(2026-06-10): daily usability audit report",
     "fundermatch.org",
     "(no fixes — audit report only)",
     "No new P0/P1 usability defects discovered this run; the two prior P1 a11y issues from PR #138 (MyTasksPage / ApplicationsPage icon-only buttons) verified still fixed in main. PR commits the audit Excel + build script to /audits."),
]
for r in PRS:
    ws_pr.append(list(r))
    last_row = ws_pr.max_row
    for ci in range(1, 7):
        c = ws_pr.cell(row=last_row, column=ci)
        c.alignment = LEFT
        c.border = BORDER
        c.font = BODY_FONT
        c.fill = INFO_FILL
set_widths(ws_pr, [54, 30, 60, 18, 28, 70])
ws_pr.freeze_panes = "A2"


# ============================================================
# Owner exceptions
# ============================================================
ws_oa = wb.create_sheet("Owner exceptions")
ws_oa.append(["Site", "Item", "Severity", "Why skipped per audit DO-NOT-AUTO-FIX list", "Notes"])
style_header(ws_oa)
OWNER_EXCEPTIONS = [
    ("kevinarmstrong.io", "Subheader green #7AED8C on teal #2596be background", "P3 (info)",
     "OWNER-CONFIRMED EXCEPTION per task spec. Owner prefers this green even though naive contrast on the blue band is non-AA.",
     "Logged so it doesn't drift back into the report on future runs. Not changed by this run. KAI-FI-007."),
    ("website-auditor.io", "/features intentionally absent", "Info",
     "Owner-confirmed intentional removal per task spec — redundant content, distracted from URL-entry goal.",
     "Live check: /features 404. Logged for traceability only — NOT recommended for re-addition. WAO-NV-012."),
    ("website-auditor.io", "/how-it-works intentionally absent", "Info",
     "Owner-confirmed intentional removal per task spec — redundant with sample report.",
     "Live check: /how-it-works 404. NOT recommended for re-addition. WAO-NV-012."),
    ("website-auditor.io", "FAQ section intentionally absent", "Info",
     "Owner-confirmed intentional removal per task spec — redundant and outdated.",
     "No FAQ section on / or anywhere in templates/. NOT recommended for re-addition."),
    ("website-auditor.io", "Hero Gartner '50% of customers will find competitors through AI' claim", "P3",
     "Editorial / messaging decision — owner may want to keep the directional forecast for marketing reasons. Auto-rewording the hero is out of scope for a usability audit bot.",
     "Suggestion: soften phrasing ('within a few years') or add a citation footnote. WAO-FI-011 / WAO-CQ-006."),
    ("website-auditor.io", "/healthz returns Google front-end 404 (no app route registered)", "P2",
     "Operational / observability decision — endpoint isn't documented or linked from the site. Whether to register a branded /healthz or use Cloud Run's built-in health is an owner call. Did not push a change.",
     "Suggestion: register /healthz in Flask app or return the branded 404 page for unmatched paths. WAO-BE-012."),
    ("kevinarmstrong.io", "/docs/ returns 404", "P3",
     "Same as prior audits. May be intentional retire; may be planned-but-unbuilt. Did not stub a 'coming soon' or remove the path.",
     "If retired: leave 404; if planned: stub a 'coming soon' page. KAI-NV-009."),
    ("fundermatch.org", "Free claim lacks per-day rate-limit disclosure", "P3",
     "Marketing / pricing decision. The product may or may not have a hard cap. Owner should set the messaging.",
     "Suggestion: micro-copy under hero CTA — 'Free up to N searches/day.' FM-CQ-002."),
    ("fundermatch.org", "No customer testimonials on landing", "P3",
     "Requires real customer quotes from real EDs — content acquisition, not a code fix.",
     "Suggestion: add a single quoted testimonial below the trust strip when one is available. FM-CQ-006."),
    ("fundermatch.org", "Instrumentl gap FAIL/PARTIAL items deferred to fundermatch-feature-builder", "P2/P3",
     "Per task spec: do NOT implement Instrumentl gap features in this audit. Just record state accurately.",
     "FAILs: FM-IC-CFG-001 (custom fields), FM-IC-CFG-002 (public API). PARTIALs: FM-IC-ONB-002 (advisor), FM-IC-DSC-004 (use-of-funds filter), FM-IC-DLN-002 (calendar grid), FM-IC-COL-003 (digest for non-members), FM-IC-NTF-001 (new_match notification)."),
]
for r in OWNER_EXCEPTIONS:
    ws_oa.append(list(r))
    last_row = ws_oa.max_row
    for ci in range(1, 6):
        c = ws_oa.cell(row=last_row, column=ci)
        c.alignment = LEFT
        c.border = BORDER
        c.font = BODY_FONT
        c.fill = WARN_FILL if r[2].startswith("P") else INFO_FILL
set_widths(ws_oa, [22, 50, 14, 70, 60])
ws_oa.freeze_panes = "A2"


# ============================================================
# Regression-Tracking (fundermatch.org)
# ============================================================
ws_rt = wb.create_sheet("Regression-Tracking")
ws_rt.append(["Previously fixed item (fundermatch.org)", "Status today", "Notes"])
style_header(ws_rt)
REGRESSION = [
    ("Privacy Policy link works (not 404)", "PASS", "/privacy 200; React route registered to <PrivacyPolicy />."),
    ("Terms of Service link works (not 404)", "PASS", "/terms 200; React route registered to <TermsOfService />."),
    ("Contact page works (not 404)", "PASS", "/contact 200; React route registered to <ContactPage />; form posts to Supabase contact-form."),
    ("Keyboard focus indicators present", "PASS", "Tailwind focus:ring-2 focus:ring-blue-500 applied across inputs; project-card focus-visible rules in src/index.css."),
    ("Form validation shows error messages", "PASS", "Mission textarea shows red border + error text; form-error announcement now goes to SR (PR #111)."),
    ("Body text contrast passes WCAG AA", "PASS", "#d1d5db on #0d1117 ≈ 13:1."),
    ("Search input has aria-label", "PASS", "OrgSearch input aria-label='Search by organization name or EIN'."),
    ("prefers-reduced-motion rule active", "PASS", "src/index.css line 280."),
    ("Data stats section visible on homepage", "PASS", "Four stat cards: 460K+ / 449K+ / 7.5M+ / 1.1M+."),
    ("Trust signals visible on homepage", "PASS", "IRS 990 / free no credit card / never shared or sold."),
    ("NotFound route injects noindex meta", "PASS", "Confirmed in App.tsx."),
    ("Skip-to-main-content link present", "PASS", "NavBar.tsx line 35."),
    ("Footer tap targets ≥44px", "PASS", "Footer.tsx min-h-[44px]."),
    ("Edge Function error responses sanitised", "PASS", "FM-2026-05-22-01 + PR #96 in main."),
    ("EXECUTE revoked on purge_expired_* from authenticated", "PASS", "PR #95 (c79e338)."),
    ("Prompt-injection guard on grant-writer & ai-draft", "PASS", "PR #99 (f4e6968)."),
    ("Toast dismiss has aria-label", "PASS", "PR #104 (525fec1)."),
    ("Sitemap expanded + aria-busy on contact form", "PASS", "PR #107 (19f528e)."),
    ("Lazy-route chunk-load failures caught", "PASS", "PR #116 (2b62160)."),
    ("Change-password + Delete-account self-service", "PASS", "PR #117 + PR #118."),
    ("Light-mode OAuth borders + green pulse text", "PASS", "PR #120 (00c2552)."),
    ("DemoVideo dark surfaces preserved in light mode", "PASS", "PR #134 (9a762cf)."),
    ("theme-color + color-scheme meta on SPA shell", "PASS", "PR #102 (bfb66a2) retained."),
    ("report-bug edge function rate-limited", "PASS", "PR #112 (4b37f0d); PR #133 refactored to shared helpers."),
    ("npm 'tmp' transitive pinned >=0.2.6 (GHSA-ph9p-34f9-6g65)", "PASS", "PR #109 (9c394b1)."),
]
for r in REGRESSION:
    ws_rt.append(list(r))
    last_row = ws_rt.max_row
    for ci in range(1, 4):
        c = ws_rt.cell(row=last_row, column=ci)
        c.alignment = LEFT
        c.border = BORDER
        c.font = BODY_FONT
        c.fill = PASS_FILL if r[1] == "PASS" else FAIL_FILL
set_widths(ws_rt, [62, 16, 80])
ws_rt.freeze_panes = "A2"


wb.active = 0
import os
out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "daily_usability_audit_2026-06-10.xlsx")
wb.save(out_path)
print(f"Wrote {out_path}")
print(f"Tests: WAO={len(WAO_TESTS)}, KAI={len(KA_TESTS)}, FUM={len(FM_TESTS)}, "
      f"total={len(WAO_TESTS)+len(KA_TESTS)+len(FM_TESTS)}")
print(f"Instrumentl gap coverage: {IC_PASS} PASS / {IC_PARTIAL} PARTIAL / {IC_FAIL} FAIL of {IC_TOTAL}")
