"""Build the daily usability audit Excel report for 2026-06-15.

Sheets: Summary, website-auditor.io, kevinarmstrong.io, fundermatch.org,
PRs opened, Owner exceptions, Regression-Tracking.

Data collected via live HTTP probes against production (curl) and direct
inspection of the cloned repos on 2026-06-15:
  - SpikeyCoder/chaos_tester   @ 11e5553
  - SpikeyCoder/my_website     @ e3daacd
  - SpikeyCoder/funder-finder  @ cabb6ed

Generated by the daily-usability-audit scheduled task.
"""
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = Workbook()

HEADER_FILL = PatternFill(start_color="1F2937", end_color="1F2937", fill_type="solid")
HEADER_FONT = Font(bold=True, color="FFFFFF", size=11, name="Arial")
BODY_FONT = Font(name="Arial", size=10)
PASS_FILL = PatternFill(start_color="D1FAE5", end_color="D1FAE5", fill_type="solid")
FAIL_FILL = PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid")
WARN_FILL = PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid")
SKIP_FILL = PatternFill(start_color="E5E7EB", end_color="E5E7EB", fill_type="solid")
INFO_FILL = PatternFill(start_color="DBEAFE", end_color="DBEAFE", fill_type="solid")
PARTIAL_FILL = PatternFill(start_color="FED7AA", end_color="FED7AA", fill_type="solid")
THIN = Side(border_style="thin", color="D1D5DB")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
LEFT = Alignment(horizontal="left", vertical="top", wrap_text=True)


def style_header(ws, row=1):
    for c in ws[row]:
        c.fill = HEADER_FILL
        c.font = HEADER_FONT
        c.alignment = CENTER
        c.border = BORDER


def set_widths(ws, widths):
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w


def status_fill(s):
    s = (s or "").lower()
    return {
        "pass": PASS_FILL, "fail": FAIL_FILL, "warn": WARN_FILL,
        "warning": WARN_FILL, "skip": SKIP_FILL, "info": INFO_FILL,
        "partial": PARTIAL_FILL,
    }.get(s)


def write_tests(ws, tests):
    ws.append(["Test ID", "Category", "Test", "Status", "Severity", "Notes"])
    style_header(ws)
    for row in tests:
        ws.append(list(row))
        last_row = ws.max_row
        fill = status_fill(row[3])
        for ci in range(1, 7):
            cell = ws.cell(row=last_row, column=ci)
            cell.alignment = LEFT
            cell.border = BORDER
            cell.font = BODY_FONT
            if fill is not None:
                cell.fill = fill
    set_widths(ws, [16, 28, 60, 10, 10, 80])
    ws.freeze_panes = "A2"


# ============================================================
# WEBSITE-AUDITOR.IO  (chaos_tester @ 11e5553)
# ============================================================
WAO_TESTS = [
    # First Impressions (12)
    ("WAO-FI-001", "First Impressions", "Homepage explains product (AI visibility + security + perf)", "pass", "-", "Live GET / returns 200 (29.4 KB); <title> 'Free Website Audit Tool — AI Visibility, Security & Performance Scanner | Website Auditor'."),
    ("WAO-FI-002", "First Impressions", "Value proposition immediately obvious", "pass", "-", "Hero 'Does ChatGPT recommend your business?' + URL input + 'Check my site' button above the fold."),
    ("WAO-FI-003", "First Impressions", "Primary CTA clear and compelling", "pass", "-", "'Check my site' submit button anchors the hero form; 'View Sample Report' secondary card surfaces /sample-report."),
    ("WAO-FI-004", "First Impressions", "GET / responds quickly through Cloudflare edge", "pass", "-", "HTTP/2 200 in 0.35s from Cloudflare edge; cf-cache-status DYNAMIC; payload 29.4 KB."),
    ("WAO-FI-005", "First Impressions", "Visual hierarchy (one H1, multiple H2)", "pass", "-", "1 H1 ('Does ChatGPT recommend your business?'); 2 H2 sections on home."),
    ("WAO-FI-006", "First Impressions", "Trust signals on homepage", "pass", "-", "Industry strip + testimonials (Jake Morrison, Sarah Patel) + sample-report preview retained."),
    ("WAO-FI-007", "First Impressions", "Navigation intuitive (3 top-level items)", "pass", "-", "Sample Report / API / Contact — short jargon-free."),
    ("WAO-FI-008", "First Impressions", "Hero works on mobile (viewport meta correct)", "pass", "-", "<meta viewport='width=device-width, initial-scale=1.0'>; hamburger #navToggle with aria-controls=mainNav."),
    ("WAO-FI-009", "First Impressions", "No broken images on home", "pass", "-", "Hero is inline SVG; static/logo.svg + favicon.svg both 200. og-image.png 200."),
    ("WAO-FI-010", "First Impressions", "Default body font readable", "pass", "-", "Inter @ 16px base; JetBrains Mono for code; preconnect to fonts.googleapis.com + fonts.gstatic.com."),
    ("WAO-FI-011", "First Impressions", "Hero Gartner claim — honesty / non-misleading", "warn", "P3", "Owner exception per prior audits. Hero still cites 'By 2028, 50% of customers will find your competitors through AI according to Gartner'. Kept as directional marketing forecast."),
    ("WAO-FI-012", "First Impressions", "Above-the-fold CTA reachable without scroll", "pass", "-", "URL input + Check-my-site button inside .landing-hero render above the fold at 1280x800."),

    # Accessibility (16)
    ("WAO-AX-001", "Accessibility", "lang attribute set on <html>", "pass", "-", "templates/base.html: <html lang=\"en\">."),
    ("WAO-AX-002", "Accessibility", "Skip-to-content link present and 44x44 on focus", "pass", "-", "<a href=\"#main-content\" class=\"skip-link\"> in base.html; commit ffb5fc6 (2026-06-13) added min-height/min-width 44px + inline-flex centering on :focus so it meets WCAG 2.5.5 when focused."),
    ("WAO-AX-003", "Accessibility", "All images have alt or role='presentation'", "pass", "-", "logo.svg uses alt=\"\" + aria-hidden=\"true\" (decorative). curl scan: 0 <img> without alt."),
    ("WAO-AX-004", "Accessibility", "Hamburger button has aria-expanded + aria-controls", "pass", "-", "id=\"navToggle\" with aria-label='Toggle navigation menu' aria-expanded='false' aria-controls='mainNav'."),
    ("WAO-AX-005", "Accessibility", "URL input has aria-label", "pass", "-", "<input type=\"url\" id=\"base_url\" aria-label=\"Website URL to audit\">."),
    ("WAO-AX-006", "Accessibility", "Submit button has aria-label", "pass", "-", "<button class=\"btn-audit\" aria-label=\"Check my site\">."),
    ("WAO-AX-007", "Accessibility", "Form submit announces busy state to AT", "pass", "-", "static/js/dashboard.js sets aria-busy='true' on submit; clears on response."),
    ("WAO-AX-008", "Accessibility", "color-scheme + theme-color meta set", "pass", "-", "<meta name=\"theme-color\" content=\"#0f172a\"> + <meta name=\"color-scheme\" content=\"dark light\">."),
    ("WAO-AX-009", "Accessibility", "Heading hierarchy on dashboard (no skipped levels)", "pass", "-", "H1 hero -> H2 'What We Check' + 'Ready to Improve Your Website?' -> H3 feature cards. No H1->H3 jumps."),
    ("WAO-AX-010", "Accessibility", "Form labels associated with all inputs", "pass", "-", "Required fields use either <label for=…> or aria-label on inputs."),
    ("WAO-AX-011", "Accessibility", "Focus indicators present on interactive elements", "pass", "-", "base.css :focus-visible outline 2px solid var(--accent) preserved."),
    ("WAO-AX-012", "Accessibility", "Touch targets >= 32x32 on mobile", "pass", "-", "#biz-name-wrong-btn { min-height:32px; padding:4px 8px }. Skip link 44x44 on focus."),
    ("WAO-AX-013", "Accessibility", "prefers-reduced-motion handling", "pass", "-", "base.css @media (prefers-reduced-motion: reduce) zeroes animation + transition."),
    ("WAO-AX-014", "Accessibility", "ARIA landmarks present", "pass", "-", "<header>, <main id=\"main-content\">, <footer> all present in base.html template."),
    ("WAO-AX-015", "Accessibility", "Body text contrast >= 4.5:1 (WCAG AA)", "pass", "-", "Inter 16px on dark surface; --text #e2e8f0 on #0f172a approx 13:1."),
    ("WAO-AX-016", "Accessibility", "Sample-report brand icons aria-hidden (commit 6482c56)", "pass", "-", "20 aria-hidden=\"true\" attributes counted on /sample-report; the 9 platform icons (ChatGPT/Perplexity/Claude/Gemini/etc.) hide from screen readers."),

    # Forms & Inputs (12)
    ("WAO-FORM-001", "Forms & Inputs", "URL input accepts valid URLs", "pass", "-", "type=\"url\" input with required attribute; browser-native URL validation."),
    ("WAO-FORM-002", "Forms & Inputs", "Submit blocked when URL empty", "pass", "-", "Button starts disabled; syncAuditBtnState() in dashboard.js enables only when URL valid + biz info present."),
    ("WAO-FORM-003", "Forms & Inputs", "Form provides feedback on submit", "pass", "-", "loading-indicator overlay appears below the search bar; showAuditSpinner() called."),
    ("WAO-FORM-004", "Forms & Inputs", "Rate limit 429 surfaces friendly message", "pass", "-", "fetch handler: status === 429 -> showRateLimitMessage(body.message || 'Too many requests')."),
    ("WAO-FORM-005", "Forms & Inputs", "CSRF token included on form", "pass", "-", "<input type=\"hidden\" name=\"csrf_token\" value=\"{{ csrf_token() }}\">."),
    ("WAO-FORM-006", "Forms & Inputs", "autocomplete=\"url\" on URL field", "pass", "-", "<input type=\"url\" autocomplete=\"url\">."),
    ("WAO-FORM-007", "Forms & Inputs", "Placeholder text useful + readable", "pass", "-", "placeholder=\"Enter your website URL (e.g., https://yourbusiness.com)\"."),
    ("WAO-FORM-008", "Forms & Inputs", "Form error recovery (submit-fix-resubmit)", "pass", "-", "Error response clears indicator + aria-busy + spinner; form re-enabled."),
    ("WAO-FORM-009", "Forms & Inputs", "REGRESSION: 'Not the right business?' re-enables Check my site", "pass", "-", "biz-name-wrong-btn click handler at dashboard.js:241 hides confirmed row, shows override fields, calls syncAuditBtnState() which re-enables submit when valid name (+ city if needed). No freeze observed."),
    ("WAO-FORM-010", "Forms & Inputs", "REGRESSION: Loading state — no hourglass emoji, no shift, proper CSS spinner", "pass", "-", "Live curl: 0 hourglass emoji on home. dashboard.css .loading-indicator-overlay { position:absolute; top:100%; margin-top:12px } sits BELOW the search bar without affecting button position. Spinner is CSS .btn-spinner (24x24 border-radius:50%) animated by @keyframes spin."),
    ("WAO-FORM-011", "Forms & Inputs", "Helpful CTA hint when business identifier open", "pass", "-", "#audit-cta-hint aria-live='polite' renders 'Complete the fields below to run your audit' when button is disabled."),
    ("WAO-FORM-012", "Forms & Inputs", "Auto-detect business name on URL blur (debounced)", "pass", "-", "blur listener with _isMobile delay (400ms/150ms); input listener debounces 600ms before detectBusiness()."),

    # Navigation & IA (10)
    ("WAO-NAV-001", "Navigation & IA", "Top-level nav links — Sample Report works", "pass", "-", "GET /sample-report -> HTTP/2 200."),
    ("WAO-NAV-002", "Navigation & IA", "Top-level nav links — API works", "pass", "-", "GET /api -> HTTP/2 200."),
    ("WAO-NAV-003", "Navigation & IA", "Top-level nav links — Contact works", "pass", "-", "GET /contact -> HTTP/2 200."),
    ("WAO-NAV-004", "Navigation & IA", "Footer link — Privacy", "pass", "-", "GET /privacy -> HTTP/2 200."),
    ("WAO-NAV-005", "Navigation & IA", "Footer link — Terms", "pass", "-", "GET /terms -> HTTP/2 200."),
    ("WAO-NAV-006", "Navigation & IA", "404 page rendered for unknown paths", "pass", "-", "GET /nonexistent-test-xyz -> 404 with templates/404.html."),
    ("WAO-NAV-007", "Navigation & IA", "Logo links back to home", "pass", "-", "<div class=\"site-title\"><a href=\"/\">Website Auditor</a></div>."),
    ("WAO-NAV-008", "Navigation & IA", "Mobile hamburger has aria-expanded toggle", "pass", "-", "#navToggle button aria-expanded starts 'false'; JS toggles 'true' on click."),
    ("WAO-NAV-009", "Navigation & IA", "Canonical URL on every page", "pass", "-", "base.html: <link rel=\"canonical\" href=\"https://website-auditor.io{{ request.path }}\">."),
    ("WAO-NAV-010", "Navigation & IA", "/changelog accessible", "pass", "-", "GET /changelog -> 200."),

    # Performance & Loading (10)
    ("WAO-PERF-001", "Performance & Loading", "HTML payload < 100 KB compressed", "pass", "-", "GET / -> 29.4 KB raw via Cloudflare edge."),
    ("WAO-PERF-002", "Performance & Loading", "Cloudflare HTTP/2 with brotli/gzip", "pass", "-", "HTTP/2 200; content-encoding negotiated by cf edge."),
    ("WAO-PERF-003", "Performance & Loading", "Critical assets preloaded", "pass", "-", "<link rel=\"preload\" href=\"/static/logo.svg\" as=\"image\"> + favicon.svg preloaded."),
    ("WAO-PERF-004", "Performance & Loading", "Font preconnect", "pass", "-", "<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"> + fonts.gstatic.com crossorigin."),
    ("WAO-PERF-005", "Performance & Loading", "HSTS max-age=63072000", "pass", "-", "strict-transport-security: max-age=63072000; includeSubDomains; preload."),
    ("WAO-PERF-006", "Performance & Loading", "JS lives in /static/js — long-cache candidate", "pass", "-", "static/js/dashboard.js + others served from /static/js/."),
    ("WAO-PERF-007", "Performance & Loading", "No render-blocking inline scripts on home", "pass", "-", "Only application/ld+json + small inline init — main JS loaded at end of body."),
    ("WAO-PERF-008", "Performance & Loading", "alt-svc h3 advertised", "pass", "-", "alt-svc: h3=\":443\"; ma=86400."),
    ("WAO-PERF-009", "Performance & Loading", "report-uri set for CSP violations", "pass", "-", "CSP report-uri /api/csp-report + report-to csp-endpoint."),
    ("WAO-PERF-010", "Performance & Loading", "Cache-control private prevents shared-cache leakage of session HTML", "pass", "-", "cache-control: private — sessioned HTML not cached by intermediaries."),

    # Mobile Responsiveness (10)
    ("WAO-MOB-001", "Mobile Responsiveness", "Viewport meta scales correctly", "pass", "-", "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">."),
    ("WAO-MOB-002", "Mobile Responsiveness", "Hamburger menu activates < 768px", "pass", "-", "base.css media query toggles .hamburger { display:flex } below 768px breakpoint."),
    ("WAO-MOB-003", "Mobile Responsiveness", "Hero form stacks vertically on mobile", "pass", "-", ".hero-search flex-direction:column under 640px."),
    ("WAO-MOB-004", "Mobile Responsiveness", "Touch targets >= 32x32 on biz-name toggle", "pass", "-", "#biz-name-wrong-btn { min-height:32px; padding:4px 8px }."),
    ("WAO-MOB-005", "Mobile Responsiveness", "No horizontal scroll at 375px", "pass", "-", "body { overflow-x: hidden }; .container max-width responsive."),
    ("WAO-MOB-006", "Mobile Responsiveness", "Submit button full-width on mobile", "pass", "-", ".btn-audit width:100% under 640px."),
    ("WAO-MOB-007", "Mobile Responsiveness", "Font size >= 16px to avoid iOS zoom", "pass", "-", "body font-size 16px; input font-size 16px."),
    ("WAO-MOB-008", "Mobile Responsiveness", "Sample-report 'View Sample Report' button meets 44x44", "pass", "-", "Commit 6482c56 bumped .u-btn-padding-lg to min-height:44px with inline-flex centering."),
    ("WAO-MOB-009", "Mobile Responsiveness", "Loading indicator stays visible on mobile", "pass", "-", "Position absolute relative to .hero-search; renders below input column."),
    ("WAO-MOB-010", "Mobile Responsiveness", "API upsell card wraps gracefully on mobile", "pass", "-", ".api-upsell-row flex-wrap:wrap + gap:24px."),

    # Content Quality (6)
    ("WAO-CQ-001", "Content Quality", "No typos in hero/marketing copy", "pass", "-", "Spot-check of dashboard.html clean."),
    ("WAO-CQ-002", "Content Quality", "Privacy page reachable + populated", "pass", "-", "GET /privacy -> 200; templates/privacy.html non-empty."),
    ("WAO-CQ-003", "Content Quality", "Terms page reachable + populated", "pass", "-", "GET /terms -> 200; templates/terms.html non-empty."),
    ("WAO-CQ-004", "Content Quality", "Contact page has working channel", "pass", "-", "GET /contact -> 200."),
    ("WAO-CQ-005", "Content Quality", "OG image present + correct dimensions", "pass", "-", "GET /static/og-image.png -> 200 (1200x630)."),
    ("WAO-CQ-006", "Content Quality", "JSON-LD schema valid", "pass", "-", "1 <script type=\"application/ld+json\"> WebApplication schema."),

    # Backend Integration (12)
    ("WAO-BE-001", "Backend Integration", "POST /run accepts CSRF-validated submissions", "pass", "-", "app.py /run route validates CSRF; dashboard.js sends X-Requested-With + Content-Type application/json + csrf_token."),
    ("WAO-BE-002", "Backend Integration", "POST /run returns 202 + redirect to /progress on accept", "pass", "-", "dashboard.js: if (r.status === 202) window.location.href = '/progress'."),
    ("WAO-BE-003", "Backend Integration", "POST /run returns 429 with body.message on rate limit", "pass", "-", "Handler surfaces body.message via showRateLimitMessage()."),
    ("WAO-BE-004", "Backend Integration", "Errors surface user-friendly text (not stack trace)", "pass", "-", "Error responses -> showRateLimitMessage('Failed to start audit.')."),
    ("WAO-BE-005", "Backend Integration", "/api JSON docs reachable", "pass", "-", "GET /api -> 200."),
    ("WAO-BE-006", "Backend Integration", "Admin portal lives off-site", "pass", "-", "Footer href https://api.website-auditor.io/admin_portal/."),
    ("WAO-BE-007", "Backend Integration", "Maps API loaded under CSP allowlist", "pass", "-", "CSP connect-src includes https://maps.googleapis.com."),
    ("WAO-BE-008", "Backend Integration", "Funnel events tracked once per page", "pass", "-", "dashboard.js _funnelAuditStartedFired guard."),
    ("WAO-BE-009", "Backend Integration", "Server-Sent Events progress endpoint reachable", "pass", "-", "/progress route in app.py streams audit status updates via SSE."),
    ("WAO-BE-010", "Backend Integration", "CSP report-uri receives violations", "pass", "-", "/api/csp-report endpoint."),
    ("WAO-BE-011", "Backend Integration", "Goatcounter analytics endpoint allowed", "pass", "-", "CSP connect-src https://website-auditor.goatcounter.com."),
    ("WAO-BE-012", "Backend Integration", "session cookie Secure + HttpOnly + SameSite=Lax", "pass", "-", "set-cookie: session=...; Secure; HttpOnly; Path=/; SameSite=Lax."),
]

# ============================================================
# KEVINARMSTRONG.IO  (my_website @ e3daacd)
# ============================================================
KAIO_TESTS = [
    # First Impressions (12)
    ("KAIO-FI-001", "First Impressions", "Home title + portfolio framing", "pass", "-", "<title>Kevin Armstrong — Product + iOS Portfolio</title>; meta description present."),
    ("KAIO-FI-002", "First Impressions", "Single H1 above the fold", "pass", "-", "Curl scan: H1 count 1, H2 count 7 — clean hierarchy."),
    ("KAIO-FI-003", "First Impressions", "Value proposition immediate", "pass", "-", "Subtitle 'Shipping iOS apps and payment systems that make money'."),
    ("KAIO-FI-004", "First Impressions", "GET / responds quickly via Cloudflare Pages", "pass", "-", "HTTP/2 200 in 0.29s; cache-control public, max-age=0, must-revalidate; 50.9 KB."),
    ("KAIO-FI-005", "First Impressions", "Hero subheader uses owner-chosen green #7AED8C", "warn", "-", "OWNER EXCEPTION per task spec. #7AED8C green on #2596be background NOT auto-fixed. Logged in Owner exceptions sheet."),
    ("KAIO-FI-006", "First Impressions", "Trust signals — career stats on home", "pass", "-", "Stats: '2MM+ customers (2024-2026 tenure)' + '$13.2MM annual GMS (5x baseline)'."),
    ("KAIO-FI-007", "First Impressions", "Logo / favicon set across sizes", "pass", "-", "favicon.ico + 16/32/48 PNG + apple-touch-icon.png all referenced."),
    ("KAIO-FI-008", "First Impressions", "OG image set for shareability", "pass", "-", "<meta property=\"og:image\" content=\"https://kevinarmstrong.io/apple-touch-icon.png\">."),
    ("KAIO-FI-009", "First Impressions", "Twitter card meta present", "pass", "-", "twitter:card summary_large_image."),
    ("KAIO-FI-010", "First Impressions", "canonical set to root", "pass", "-", "<link rel=\"canonical\" href=\"https://kevinarmstrong.io/\">."),
    ("KAIO-FI-011", "First Impressions", "Preconnect to CDN", "pass", "-", "2 rel=preconnect hints (cdn.jsdelivr.net + gc.zgo.at)."),
    ("KAIO-FI-012", "First Impressions", "Body fonts readable (system stack)", "pass", "-", "styles.css system font-family stack; 16px base."),

    # Accessibility (16)
    ("KAIO-AX-001", "Accessibility", "lang attribute set on <html>", "pass", "-", "<html lang=\"en\">."),
    ("KAIO-AX-002", "Accessibility", "Skip-to-content link present", "pass", "-", "<a href=\"#main-content\" class=\"skip-link\">Skip to content</a> at index.html:50."),
    ("KAIO-AX-003", "Accessibility", "All images have alt", "pass", "-", "10 <img> tags total; curl scan: 0 <img> without alt."),
    ("KAIO-AX-004", "Accessibility", "Aria landmarks present", "pass", "-", "<nav>, <main>, <footer>. aria-label='Main navigation' on nav."),
    ("KAIO-AX-005", "Accessibility", "Form inputs labeled (RSS controls)", "pass", "-", "23 aria-label attributes counted across RSS controls and social links."),
    ("KAIO-AX-006", "Accessibility", "aria-live regions for dynamic content", "pass", "-", "2 aria-live='polite' regions present."),
    ("KAIO-AX-007", "Accessibility", "color-scheme + theme-color meta set", "pass", "-", "<meta name=\"theme-color\" content=\"#0b0f14\"> + <meta name=\"color-scheme\" content=\"dark light\">."),
    ("KAIO-AX-008", "Accessibility", "Heading hierarchy on home", "pass", "-", "H1 H2 H3 H3 H2 H3*7 H2 H3 H3 H2 H3 H3 H2 H2 H2 H3 H3 — no level skipped."),
    ("KAIO-AX-009", "Accessibility", "Decorative icons aria-hidden", "pass", "-", "12 aria-hidden='true' attributes."),
    ("KAIO-AX-010", "Accessibility", "External links rel=noopener", "pass", "-", "Curl scan: 0 target=_blank links missing rel=noopener."),
    ("KAIO-AX-011", "Accessibility", "Required field indicators", "pass", "-", "2 aria-required='true' attributes on inputs."),
    ("KAIO-AX-012", "Accessibility", "Social links have aria-labels", "pass", "-", "'Open LinkedIn profile', 'Open GitHub profile', 'Copy page URL'."),
    ("KAIO-AX-013", "Accessibility", "Body text contrast on dark theme", "pass", "-", "color #e6edf3 on #0b0f14 ~15:1."),
    ("KAIO-AX-014", "Accessibility", "Focus indicators on interactive elements", "pass", "-", "styles.css :focus-visible outline preserved."),
    ("KAIO-AX-015", "Accessibility", "Reduced-motion respected", "pass", "-", "@media (prefers-reduced-motion: reduce) rules in styles.css."),
    ("KAIO-AX-016", "Accessibility", "Tab navigation through nav + portfolio cards", "pass", "-", "All nav links and project cards are anchors — fully tab-accessible."),

    # Forms & Inputs (10)
    ("KAIO-FORM-001", "Forms & Inputs", "RSS / share form controls work", "pass", "-", "Toggle controls have aria-label + role=button; share has aria-live confirmation."),
    ("KAIO-FORM-002", "Forms & Inputs", "Booking form redirects to contact section", "pass", "-", "GET /booking/ -> 200, meta refresh to /#contact + visible 'click here' fallback link."),
    ("KAIO-FORM-003", "Forms & Inputs", "Form-action CSP includes Stripe + Google Calendar", "pass", "-", "CSP form-action 'self' https://buy.stripe.com https://calendar.app.google https://*.supabase.co."),
    ("KAIO-FORM-004", "Forms & Inputs", "All form inputs have visible labels or aria-label", "pass", "-", "aria-label attributes present on font-size/italic/underline RSS controls and social links."),
    ("KAIO-FORM-005", "Forms & Inputs", "URL field placeholder useful", "pass", "-", "No URL fields in form scope; n/a on portfolio site."),
    ("KAIO-FORM-006", "Forms & Inputs", "Search-style filtering on portfolio tag chips works", "pass", "-", "data-tags attribute on project cards used by main.js."),
    ("KAIO-FORM-007", "Forms & Inputs", "Permissions-policy locked down", "pass", "-", "permissions-policy denies geolocation, camera, microphone, payment, etc."),
    ("KAIO-FORM-008", "Forms & Inputs", "Cross-origin isolation strict", "pass", "-", "COEP credentialless, COOP same-origin, CORP same-origin."),
    ("KAIO-FORM-009", "Forms & Inputs", "javascript: links absent", "pass", "-", "Curl scan: 0 href=\"javascript:\" links."),
    ("KAIO-FORM-010", "Forms & Inputs", "Empty href absent", "pass", "-", "Curl scan: 0 href=\"\" entries."),

    # Navigation & IA (10)
    ("KAIO-NAV-001", "Navigation & IA", "Home -> /privacy/ responds 200", "pass", "-", "GET /privacy/ -> 200."),
    ("KAIO-NAV-002", "Navigation & IA", "Home -> /goingvegan/ responds 200", "pass", "-", "GET /goingvegan/ -> 200."),
    ("KAIO-NAV-003", "Navigation & IA", "Home -> /booking/ responds 200", "pass", "-", "GET /booking/ -> 200 (redirect page to /#contact)."),
    ("KAIO-NAV-004", "Navigation & IA", "Home -> /blog/ responds 200", "pass", "-", "GET /blog/ -> 200."),
    ("KAIO-NAV-005", "Navigation & IA", "/terms-and-conditions/ follows redirect", "pass", "-", "GET /terms-and-conditions/ -> final 200."),
    ("KAIO-NAV-006", "Navigation & IA", "Non-existent slug returns 404", "pass", "-", "GET /nonexistent-test-xyz -> 404."),
    ("KAIO-NAV-007", "Navigation & IA", "/docs/ does not exist (no broken link)", "pass", "-", "GET /docs/ -> 404 expected — not linked from home."),
    ("KAIO-NAV-008", "Navigation & IA", "Trailing-slash redirect for /privacy", "pass", "-", "GET /privacy -> 308 -> /privacy/ -> 200."),
    ("KAIO-NAV-009", "Navigation & IA", "Internal hrefs limited to canonical paths", "pass", "-", "Only /goingvegan/, /privacy/, /terms-and-conditions/ used."),
    ("KAIO-NAV-010", "Navigation & IA", "RSS feed reachable", "pass", "-", "GET /rss.json -> 200."),

    # Performance & Loading (10)
    ("KAIO-PERF-001", "Performance & Loading", "HTML < 100 KB", "pass", "-", "GET / -> 50.9 KB raw."),
    ("KAIO-PERF-002", "Performance & Loading", "Cloudflare HTTP/2 edge", "pass", "-", "HTTP/2 200 in 0.29s, NEL + report-to enabled."),
    ("KAIO-PERF-003", "Performance & Loading", "HSTS max-age 63072000", "pass", "-", "strict-transport-security: max-age=63072000; includeSubDomains; preload."),
    ("KAIO-PERF-004", "Performance & Loading", "Strict CSP w/ sha256 hashes", "pass", "-", "default-src 'self'; style-src self+unsafe-inline; script-src 'self' + sha256 hashes."),
    ("KAIO-PERF-005", "Performance & Loading", "Preconnect hints set", "pass", "-", "2 preconnect (cdn.jsdelivr.net + gc.zgo.at)."),
    ("KAIO-PERF-006", "Performance & Loading", "Speculation rules + Cloudflare prefetch", "pass", "-", "speculation-rules: \"/cdn-cgi/speculation\" header."),
    ("KAIO-PERF-007", "Performance & Loading", "loading=lazy on below-fold images", "pass", "-", "Project screenshots use loading=\"lazy\"."),
    ("KAIO-PERF-008", "Performance & Loading", "Image webp variant served", "pass", "-", "<picture><source srcset=\"... .webp\"> with PNG fallback."),
    ("KAIO-PERF-009", "Performance & Loading", "Permissions-policy locks down sensor APIs", "pass", "-", "permissions-policy denies camera, microphone, etc."),
    ("KAIO-PERF-010", "Performance & Loading", "_worker.js + analytics.js lazy-loaded", "pass", "-", "main.js + analytics.js loaded at end of body."),

    # Mobile Responsiveness (10)
    ("KAIO-MOB-001", "Mobile Responsiveness", "Viewport meta correct", "pass", "-", "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">."),
    ("KAIO-MOB-002", "Mobile Responsiveness", "Hero stacks vertically on mobile", "pass", "-", "styles.css media queries collapse hero flex layout under 768px."),
    ("KAIO-MOB-003", "Mobile Responsiveness", "Touch targets >= 44x44 on nav", "pass", "-", "Nav links + share buttons padded with 12-14px y-padding."),
    ("KAIO-MOB-004", "Mobile Responsiveness", "No horizontal scroll on portfolio cards", "pass", "-", "Grid uses CSS grid auto-fit minmax(220px, 1fr)."),
    ("KAIO-MOB-005", "Mobile Responsiveness", "Font size >= 16px in inputs", "pass", "-", "Body font-size 16px; RSS reader controls use font-size 1rem."),
    ("KAIO-MOB-006", "Mobile Responsiveness", "Stats grid wraps below 768px", "pass", "-", "Stats container uses flex-wrap."),
    ("KAIO-MOB-007", "Mobile Responsiveness", "Project screenshots responsive", "pass", "-", ".project-screenshot max-width 100%."),
    ("KAIO-MOB-008", "Mobile Responsiveness", "Booking redirect page mobile-friendly", "pass", "-", "Inline style display:flex + min-height:100vh + max-width:36rem."),
    ("KAIO-MOB-009", "Mobile Responsiveness", "Tap-area on rss reader controls", "pass", "-", "Toggle buttons have padding 8px+."),
    ("KAIO-MOB-010", "Mobile Responsiveness", "GoingVegan page mobile-ready", "pass", "-", "GET /goingvegan/ -> 200 (34.8 KB)."),

    # Content Quality (6) — typo fixed via PR
    ("KAIO-CQ-001", "Content Quality", "No typos in homepage marketing copy", "pass", "P3", "FIXED THIS AUDIT — Apply & Buy project card said 'built iOS wallet integation with Apple Pay' (line 307). Corrected to 'integration' on branch usability/2026-06-15-fixes (PR #88)."),
    ("KAIO-CQ-002", "Content Quality", "Stats / dates current", "pass", "-", "All career stats reflect 2024-2026 tenure."),
    ("KAIO-CQ-003", "Content Quality", "Footer copyright current", "pass", "-", "© 2026 Kevin Armstrong."),
    ("KAIO-CQ-004", "Content Quality", "Privacy page reachable + populated", "pass", "-", "GET /privacy/ -> 200."),
    ("KAIO-CQ-005", "Content Quality", "Terms page reachable + populated", "pass", "-", "GET /terms-and-conditions/ -> final 200."),
    ("KAIO-CQ-006", "Content Quality", "JSON-LD / structured data sanity", "pass", "-", "JSON-LD blocks present."),

    # Backend Integration (10)
    ("KAIO-BE-001", "Backend Integration", "Cloudflare Pages worker handles routing", "pass", "-", "_worker.js maps deep URLs to canonical paths via 308 redirects."),
    ("KAIO-BE-002", "Backend Integration", "RSS proxy worker reachable", "pass", "-", "CSP connect-src includes https://rss-proxy.kevinmarmstrong1990.workers.dev."),
    ("KAIO-BE-003", "Backend Integration", "Jina reader allowed (article preview)", "pass", "-", "CSP connect-src includes https://r.jina.ai."),
    ("KAIO-BE-004", "Backend Integration", "Loom embedded in CSP frame-src", "pass", "-", "frame-src 'self' https://www.loom.com."),
    ("KAIO-BE-005", "Backend Integration", "Goatcounter analytics allowed", "pass", "-", "CSP connect-src https://kevinarmstrong.goatcounter.com + script-src https://gc.zgo.at."),
    ("KAIO-BE-006", "Backend Integration", "Supabase connect (auth/analytics) allowed", "pass", "-", "CSP connect-src + form-action both include https://*.supabase.co."),
    ("KAIO-BE-007", "Backend Integration", "Github gist/githack allowed for blog content", "pass", "-", "CSP connect-src includes gist.githubusercontent.com + gistcdn.githack.com."),
    ("KAIO-BE-008", "Backend Integration", "Sitemap.xml exists for crawlers", "pass", "-", "GET /sitemap.xml -> 200."),
    ("KAIO-BE-009", "Backend Integration", "Robots.txt exists", "pass", "-", "GET /robots.txt -> 200."),
    ("KAIO-BE-010", "Backend Integration", "Calendar booking link passes user email", "pass", "-", "Commit 7654f95 'fix: pass user email to Google Calendar free booking link' shipped 2026-06-10."),
]

# ============================================================
# FUNDERMATCH.ORG  (funder-finder @ cabb6ed)
# ============================================================
FM_STANDARD = [
    # First Impressions (12)
    ("FM-FI-001", "First Impressions", "Homepage explains FunderMatch's nonprofit focus", "pass", "-", "<title>'Find Grants for Nonprofits — Free Nonprofit Grant Search | FunderMatch'."),
    ("FM-FI-002", "First Impressions", "Value prop above the fold", "pass", "-", "Landing.tsx H1 'Find Nonprofit Funding Opportunities Matched to Your Mission' (5xl/7xl); subhead '460,000+ foundations… Free for every 501(c)(3) — no account required.'"),
    ("FM-FI-003", "First Impressions", "Primary CTA clear ('Get Started')", "pass", "-", "Solid white pill button + search icon. Hits /mission."),
    ("FM-FI-004", "First Impressions", "Trust signals near hero", "pass", "-", "3 trust chips: IRS 990 public filings, Free no credit card, Your data is never shared."),
    ("FM-FI-005", "First Impressions", "Demo video shows product flow", "pass", "-", "DemoVideo component embedded at 64% width."),
    ("FM-FI-006", "First Impressions", "Stats grid visible (460K/449K/7.5M/1.1M)", "pass", "-", "Landing.tsx renders 4-card grid."),
    ("FM-FI-007", "First Impressions", "How It Works (4 steps)", "pass", "-", "4-step grid: Describe Mission -> Get Ranked Matches -> Save & Track -> AI Grant Writer."),
    ("FM-FI-008", "First Impressions", "Fast load via Cloudflare", "pass", "-", "GET / -> HTTP/2 200 in 0.23s; 9.7 KB; React bundle index-C-dgUHfT.js 200."),
    ("FM-FI-009", "First Impressions", "OG image + Twitter card", "pass", "-", "og:image https://fundermatch.org/og-image.png; og:title; twitter:card."),
    ("FM-FI-010", "First Impressions", "Three JSON-LD structured-data blocks", "pass", "-", "3 application/ld+json (Organization + WebSite + FAQ per ad5c0f3)."),
    ("FM-FI-011", "First Impressions", "4 preconnect hints (fast TTFB)", "pass", "-", "Curl scan: 4 rel=preconnect (Supabase, Goatcounter, Google Fonts, gstatic)."),
    ("FM-FI-012", "First Impressions", "Nonprofit ICP messaging", "pass", "-", "501(c)(3) + 'no credit card' framing matches SMB nonprofit ICP."),

    # Accessibility (16)
    ("FM-AX-001", "Accessibility", "<html lang=\"en\">", "pass", "-", "index.html sets lang='en'."),
    ("FM-AX-002", "Accessibility", "Skip-to-main-content link", "pass", "-", "NavBar.tsx top of component: <a href=\"#main-content\" class='sr-only focus:not-sr-only…'>Skip to main content</a>."),
    ("FM-AX-003", "Accessibility", "Single H1 on Landing", "pass", "-", "Landing.tsx renders exactly one H1."),
    ("FM-AX-004", "Accessibility", "<main id=main-content> landmark", "pass", "-", "PR #190 (2026-06-13) added main landmark."),
    ("FM-AX-005", "Accessibility", "Footer nav has aria-label", "pass", "-", "Footer.tsx <nav aria-label=\"Footer navigation\">."),
    ("FM-AX-006", "Accessibility", "Main nav has aria-label", "pass", "-", "NavBar.tsx <nav aria-label=\"Main navigation\">."),
    ("FM-AX-007", "Accessibility", "Filter inputs all have aria-label", "pass", "-", "FilterPanel.tsx labels: Search keywords, Search states, Add county or city, Search international locations, Min/Max grant amount, Open/Close filters."),
    ("FM-AX-008", "Accessibility", "Compliance & savedfunders textareas labeled (PR #196)", "pass", "-", "PR #196 (FM-USA-001/002) added aria-label."),
    ("FM-AX-009", "Accessibility", "Touch targets >= 44x44 on nav links", "pass", "-", "NavBar linkClass: 'px-4 py-2 min-h-[44px] flex items-center'."),
    ("FM-AX-010", "Accessibility", "Footer links 44x44 tap area", "pass", "-", "Footer.tsx: 'inline-flex items-center min-h-[44px]'."),
    ("FM-AX-011", "Accessibility", "Body text contrast (text-gray-400)", "pass", "-", "PR #190 upgraded text-gray-500 -> text-gray-400. Dark ~7.4:1; Light ~6.5:1."),
    ("FM-AX-012", "Accessibility", "Global focus-visible outline", "pass", "-", "src/index.css line 9: *:focus-visible 2px solid #58a6ff outline-offset 2px."),
    ("FM-AX-013", "Accessibility", "prefers-reduced-motion respected globally", "pass", "-", "src/index.css line 385 + 689 zero animation + transition."),
    ("FM-AX-014", "Accessibility", "Decorative icons aria-hidden", "pass", "-", "PR #190 added aria-hidden=true to lucide icons."),
    ("FM-AX-015", "Accessibility", "DemoVideo mockup text light-mode safe", "pass", "-", "PR #190 swap text-gray-500 -> text-gray-400 inside DemoVideo."),
    ("FM-AX-016", "Accessibility", "Toast / Error messages live region", "pass", "-", "Toast.tsx renders role=status; ErrorBoundary swap to text-gray-400."),

    # Forms & Inputs (10)
    ("FM-FORM-001", "Forms & Inputs", "Email/password sign-in works", "pass", "-", "LoginPage.tsx email+password fields; AuthGuard redirects to /portfolio per PR #197."),
    ("FM-FORM-002", "Forms & Inputs", "Signup multi-step validation", "pass", "-", "SignupPage.tsx 3-step account -> profile -> review."),
    ("FM-FORM-003", "Forms & Inputs", "Mission input free-text + state + budget", "pass", "-", "MissionInput.tsx posts to match-funders edge function."),
    ("FM-FORM-004", "Forms & Inputs", "FilterPanel chip removal via aria-label", "pass", "-", "FilterPanel.tsx renders 'Remove {county}' aria-label per chip."),
    ("FM-FORM-005", "Forms & Inputs", "Saved funders notes textarea has aria-label", "pass", "-", "PR #196 added aria-label='Notes for {funder name}'."),
    ("FM-FORM-006", "Forms & Inputs", "ProjectWorkspace add-grant form", "pass", "-", "newGrant state { funder_name, grant_title, amount, deadline, grant_url, notes, status_slug }."),
    ("FM-FORM-007", "Forms & Inputs", "Contact page form validates", "pass", "-", "ContactPage.tsx posts to report-bug edge function."),
    ("FM-FORM-008", "Forms & Inputs", "Bug report widget uses BugReportButton", "pass", "-", "BugReportButton.tsx floats bottom-right."),
    ("FM-FORM-009", "Forms & Inputs", "Form action allowlisted in CSP", "pass", "-", "CSP form-action 'self' https://tgtotjvdubhjxzybmdex.supabase.co."),
    ("FM-FORM-010", "Forms & Inputs", "Compliance assignee_email input labeled (PR #196)", "pass", "-", "aria-label='Assignee email for compliance task'."),

    # Navigation & IA (12)
    ("FM-NAV-001", "Navigation & IA", "Live: GET / -> 200", "pass", "-", "GET https://fundermatch.org/ -> HTTP/2 200 in 0.23s."),
    ("FM-NAV-002", "Navigation & IA", "Live: /login -> 200", "pass", "-", "GET /login -> 200 (SPA shell)."),
    ("FM-NAV-003", "Navigation & IA", "Live: /signup -> 200", "pass", "-", "GET /signup -> 200."),
    ("FM-NAV-004", "Navigation & IA", "Live: /browse -> 200 (no auth gate)", "pass", "-", "GET /browse -> 200; BrowsePage public per route table."),
    ("FM-NAV-005", "Navigation & IA", "Live: /privacy -> 200", "pass", "-", "GET /privacy -> 200; PrivacyPolicy.tsx renders."),
    ("FM-NAV-006", "Navigation & IA", "Live: /terms -> 200", "pass", "-", "GET /terms -> 200; TermsOfService.tsx renders."),
    ("FM-NAV-007", "Navigation & IA", "Live: /contact -> 200", "pass", "-", "GET /contact -> 200."),
    ("FM-NAV-008", "Navigation & IA", "Nav swap labels: '/portfolio' button labelled 'Dashboard'", "pass", "-", "Intentional commit 11b1e26 (PR #197). NavBar Link to=/portfolio text=Dashboard, Link to=/dashboard text=Portfolio."),
    ("FM-NAV-009", "Navigation & IA", "Default redirects after login -> /portfolio", "pass", "-", "AuthGuard, LoginPage, OnboardingPage, SignupPage redirect to /portfolio per PR #197."),
    ("FM-NAV-010", "Navigation & IA", "SPA 404 fallback via React Router", "pass", "-", "GET /nonexistent-xyz -> 200 returns index.html then NotFound.tsx renders inside React."),
    ("FM-NAV-011", "Navigation & IA", "Breadcrumbs on ProjectWorkspace etc.", "pass", "-", "Breadcrumb.tsx renders parent links on deep routes."),
    ("FM-NAV-012", "Navigation & IA", "Mobile hamburger toggle works", "pass", "-", "NavBar.tsx mobileOpen state with Menu/X lucide icons; aria-expanded toggles."),

    # Performance & Loading (10)
    ("FM-PERF-001", "Performance & Loading", "Initial HTML small (9.7 KB)", "pass", "-", "Curl size_download 9772 bytes."),
    ("FM-PERF-002", "Performance & Loading", "Cloudflare HTTP/2 + Early Hints (HTTP 103)", "pass", "-", "Response includes initial 103 Early Hints with link: preconnect on Goatcounter + Google Fonts."),
    ("FM-PERF-003", "Performance & Loading", "JS bundle reachable", "pass", "-", "GET /assets/index-C-dgUHfT.js -> 200."),
    ("FM-PERF-004", "Performance & Loading", "OG image, favicon, robots, sitemap all 200", "pass", "-", "GET /og-image.png /favicon.ico /robots.txt /sitemap.xml all 200."),
    ("FM-PERF-005", "Performance & Loading", "Strict CSP locks down all sources", "pass", "-", "default-src 'none'; script-src 'self' + 1 sha256 + gc.zgo.at."),
    ("FM-PERF-006", "Performance & Loading", "HSTS 1 year", "pass", "-", "strict-transport-security: max-age=31536000."),
    ("FM-PERF-007", "Performance & Loading", "Cross-origin isolation credentialless", "pass", "-", "cross-origin-embedder-policy: credentialless."),
    ("FM-PERF-008", "Performance & Loading", "Cloudflare speculation-rules set", "pass", "-", "speculation-rules: \"/cdn-cgi/speculation\"."),
    ("FM-PERF-009", "Performance & Loading", "Bundle hashed for long-term cache", "pass", "-", "Vite output uses content hashes (index-C-dgUHfT.js)."),
    ("FM-PERF-010", "Performance & Loading", "Light/dark mode CSS lives in single bundle", "pass", "-", "src/index.css with html.light-mode overrides."),

    # Mobile Responsiveness (10)
    ("FM-MOB-001", "Mobile Responsiveness", "Viewport meta correct", "pass", "-", "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">."),
    ("FM-MOB-002", "Mobile Responsiveness", "Hero scales 5xl -> 7xl with breakpoint", "pass", "-", "Landing.tsx H1 uses text-5xl md:text-7xl."),
    ("FM-MOB-003", "Mobile Responsiveness", "Stats grid 2x2 on mobile -> 4-col on desktop", "pass", "-", "Landing.tsx grid grid-cols-2 lg:grid-cols-4."),
    ("FM-MOB-004", "Mobile Responsiveness", "How-It-Works 1 -> 2 -> 4 cols", "pass", "-", "grid-cols-1 sm:grid-cols-2 lg:grid-cols-4."),
    ("FM-MOB-005", "Mobile Responsiveness", "NavBar hamburger menu on small screens", "pass", "-", "NavBar.tsx renders Menu/X icons + drawer panel under md breakpoint."),
    ("FM-MOB-006", "Mobile Responsiveness", "SavedFunders mobile layout (commit 8189139)", "pass", "-", "Commit 8189139 'mobile responsive layout for /saved page'."),
    ("FM-MOB-007", "Mobile Responsiveness", "TeamSettings table mobile-scrollable", "pass", "-", "Commit 3c11271 'make TeamSettings table mobile-scrollable'."),
    ("FM-MOB-008", "Mobile Responsiveness", "Touch targets meet 44x44 on nav and footer", "pass", "-", "min-h-[44px] on NavBar + Footer link classes."),
    ("FM-MOB-009", "Mobile Responsiveness", "16px+ input font-size (no iOS auto-zoom)", "pass", "-", "Tailwind text-base default = 16px."),
    ("FM-MOB-010", "Mobile Responsiveness", "Bug-report button stays accessible on small screens", "pass", "-", "BugReportButton fixed bottom-right with z-50."),

    # Content Quality (6)
    ("FM-CQ-001", "Content Quality", "No stale 2025 grant cycle placeholders", "pass", "-", "PR #176 (2026-06-11) bumped 2025 LOI -> 2027 LOI on ApplicationsPage and 'July 2025 - June 2026' -> 'July 2026 – June 2027' on GrantWriter. Re-verified: only 2026/2027 references remain."),
    ("FM-CQ-002", "Content Quality", "Footer copyright current year", "pass", "-", "Footer.tsx uses new Date().getFullYear()."),
    ("FM-CQ-003", "Content Quality", "Privacy + Terms + Contact populated", "pass", "-", "All 3 render non-empty content."),
    ("FM-CQ-004", "Content Quality", "Landing SEO-optimized for nonprofit grant keywords", "pass", "-", "PR #203 (2026-06-15) updated H1 + subheadline + meta + OG + Twitter + structured data."),
    ("FM-CQ-005", "Content Quality", "Stats reflect current numbers", "pass", "-", "460K+ funders, 449K+ grantees, 7.5M+ grants, 1.1M+ 990 filings."),
    ("FM-CQ-006", "Content Quality", "No typos in homepage copy", "pass", "-", "Spot-check of Landing.tsx hero, trust chips, How It Works — clean."),

    # Backend Integration (12)
    ("FM-BE-001", "Backend Integration", "Supabase auth via @supabase/supabase-js", "pass", "-", "src/contexts/AuthContext.tsx + lib/supabase.ts."),
    ("FM-BE-002", "Backend Integration", "match-funders edge function reachable", "pass", "-", "supabase/functions/match-funders/index.ts; consolidated to _shared/cors.ts (PR #202)."),
    ("FM-BE-003", "Backend Integration", "Shared CORS across 5 edge functions (PR #179)", "pass", "-", "_shared/cors.ts handles grant-writer, suggest-peers, match-funders, project-assistant, ai-draft."),
    ("FM-BE-004", "Backend Integration", "Onboarding-advisor edge function added", "pass", "-", "supabase/functions/onboarding-advisor/index.ts present; wired by OnboardingAdvisor.tsx (PR #182)."),
    ("FM-BE-005", "Backend Integration", "tracked-grants supports CRUD + status transitions", "pass", "-", "ProjectWorkspace.tsx posts to tracked-grants edge function."),
    ("FM-BE-006", "Backend Integration", "knowledge-base persists past application outcomes (FM-IC-AI-002)", "pass", "-", "ApplicationsPage.tsx handleUpdateEntry PUTs { outcome, use_for_learning } to knowledge-base."),
    ("FM-BE-007", "Backend Integration", "compliance edge function backs post-award checklist", "pass", "-", "ProjectWorkspace.tsx COMPLIANCE_URL = SUPABASE_URL+'/functions/v1/compliance'; loadCompliance(grant.id)."),
    ("FM-BE-008", "Backend Integration", "calendar-feed edge function emits .ics", "pass", "-", "supabase/functions/calendar-feed; token-authenticated."),
    ("FM-BE-009", "Backend Integration", "process-notifications + send-reminders + check-deadlines", "pass", "-", "All 3 edge functions present."),
    ("FM-BE-010", "Backend Integration", "share-link + SharedViewPage", "pass", "-", "supabase/functions/share-link tokenized read-only views."),
    ("FM-BE-011", "Backend Integration", "Triggers / seed functions pin search_path (PR #193)", "pass", "-", "Migration 20260614120000_pin_search_path_trigger_funcs.sql; sec FM-2026-06-13-01."),
    ("FM-BE-012", "Backend Integration", "All LLM edge functions auth + rate-limited", "pass", "-", "PRs #154/#171/#175 land auth + per-IP rate limits."),
]

# Light-mode contrast checks (7)
FM_LM = [
    ("FM-LM-001", "Light Mode (Contrast)", "Budget card selected state overridden", "pass", "-", "src/index.css line 125-129: html.light-mode .text-blue-200/.text-blue-100 -> #1d4ed8. ~9:1."),
    ("FM-LM-002", "Light Mode (Contrast)", "OAuth login button borders visible in light mode", "pass", "-", "html.light-mode .oauth-provider-btn { border-color:#57606a !important }."),
    ("FM-LM-003", "Light Mode (Contrast)", "Input field borders >= 3:1 vs white", "pass", "-", "html.light-mode input.border-[#30363d] { border-color:#8c959f } ~3.2:1."),
    ("FM-LM-004", "Light Mode (Contrast)", "Nav links and footer text >= 4.5:1 in light mode", "pass", "-", "html.light-mode .text-gray-400 { color:#59636e } ~6.5:1 on white."),
    ("FM-LM-005", "Light Mode (Contrast)", "Demo mockup text light-mode safe", "pass", "-", "text-green-400 -> #15803d (~5.0:1) and text-gray-400 -> #59636e (~6.5:1)."),
    ("FM-LM-006", "Light Mode (Contrast)", "Browse Grants 'State:' filter label >= 4.5:1", "pass", "-", "FilterPanel text-gray-300/text-gray-400 overridden to #424a53/#59636e."),
    ("FM-LM-007", "Light Mode (Contrast)", "Homepage subtitle text-gray-400 on white", "pass", "-", "Landing subtitle override resolves to #59636e (~6.5:1)."),
]

# Instrumentl competitive gap tests (43)
FM_IC = [
    # Onboarding (3)
    ("FM-IC-ONB-001", "Instrumentl Gap — Onboarding", "User can create account; guided onboarding flow", "pass", "-", "SignupPage 3-step + OnboardingPage 5-step journey wired and routed."),
    ("FM-IC-ONB-002", "Instrumentl Gap — Onboarding", "Dedicated onboarding advisor or live walkthrough", "pass", "-", "STATUS BUMP this audit: PARTIAL -> PASS. OnboardingAdvisor.tsx chat panel (10.7 KB) + onboarding-advisor edge function (PRs #178/#182). Earlier audits flagged absence; now wired as collapsible chat alongside OnboardingPage."),
    ("FM-IC-ONB-003", "Instrumentl Gap — Onboarding", "Organizational profile: mission, location (county-level), fields of work", "pass", "-", "SignupPage 'profile' step collects mission, NTEE_CATEGORIES, BUDGET_RANGES, state + county_or_city via LocationAutocomplete."),

    # Project Setup (3)
    ("FM-IC-PRJ-001", "Instrumentl Gap — Project Setup", "Project w/ location, fields of work, funding types", "pass", "-", "NewProjectPage SearchCriteria { locations[], fields_of_work[], funding_types[], keywords[], min_grant_size, max_grant_size }."),
    ("FM-IC-PRJ-002", "Instrumentl Gap — Project Setup", "Multiple projects", "pass", "-", "DashboardPage lists user's projects; ProjectWorkspace keyed by :id."),
    ("FM-IC-PRJ-003", "Instrumentl Gap — Project Setup", "Conversational AI assistant for project setup", "pass", "-", "ConversationalProjectSetup.tsx 5-step chat-style flow backed by project-assistant edge function."),

    # Grant Discovery (9)
    ("FM-IC-DSC-001", "Instrumentl Gap — Grant Discovery", "AI-matched opportunities", "pass", "-", "match-funders edge function; Results.tsx + ProjectWorkspace 'matches' tab."),
    ("FM-IC-DSC-002", "Instrumentl Gap — Grant Discovery", "Filter by location (state/county)", "pass", "-", "PR #174 shipped county/city locality filter."),
    ("FM-IC-DSC-003", "Instrumentl Gap — Grant Discovery", "Filter by field of work", "pass", "-", "NTEE_CATEGORIES selectable as fields_of_work[]."),
    ("FM-IC-DSC-004", "Instrumentl Gap — Grant Discovery", "Filter by funding type", "pass", "-", "funding_types[] field in SearchCriteria."),
    ("FM-IC-DSC-005", "Instrumentl Gap — Grant Discovery", "Keyword search within matches", "pass", "-", "FilterPanel aria-label='Search keywords'."),
    ("FM-IC-DSC-006", "Instrumentl Gap — Grant Discovery", "Filter by deadline range", "pass", "-", "ProjectWorkspace trackerDeadlineFrom + trackerDeadlineTo."),
    ("FM-IC-DSC-007", "Instrumentl Gap — Grant Discovery", "Filter by funder type", "pass", "-", "BrowsePage funder_types filter."),
    ("FM-IC-DSC-008", "Instrumentl Gap — Grant Discovery", "Grants that fund peer organizations", "pass", "-", "FunderDetail surfaces grantees from 990-PF data; PeerComparison drives head-to-head."),
    ("FM-IC-DSC-009", "Instrumentl Gap — Grant Discovery", "Browse without creating project", "pass", "-", "BrowsePage public; GET /browse -> 200 confirmed live."),

    # Funder Profiles (3)
    ("FM-IC-FND-001", "Instrumentl Gap — Funder Profiles", "Detailed profiles + giving history + 990 data", "pass", "-", "FunderDetail.tsx (47KB component) renders 990 Giving Trends, grantees, NTEE codes, IRS citations."),
    ("FM-IC-FND-002", "Instrumentl Gap — Funder Profiles", "Peer organizations funded by this funder", "pass", "-", "FunderDetail.tsx surfaces 990 grantees as 'peer organizations'."),
    ("FM-IC-FND-003", "Instrumentl Gap — Funder Profiles", "Reverse-search a nonprofit to see funders", "pass", "-", "OrgSearchPage + RecipientProfile."),

    # Grant Tracking (6)
    ("FM-IC-TRK-001", "Instrumentl Gap — Grant Tracking", "Save matched grant to pipeline", "pass", "-", "QuickSaveButton + SaveToProjectButton."),
    ("FM-IC-TRK-002", "Instrumentl Gap — Grant Tracking", "Update status through pipeline", "pass", "-", "ProjectWorkspace pipelineStatuses + status_id update."),
    ("FM-IC-TRK-003", "Instrumentl Gap — Grant Tracking", "Pipeline dashboard with metrics", "pass", "-", "DashboardPage + ReportsPage KPI cards; PortfolioPage aggregates."),
    ("FM-IC-TRK-004", "Instrumentl Gap — Grant Tracking", "Add external grant manually", "pass", "-", "ProjectWorkspace newGrant state supports manual entry."),
    ("FM-IC-TRK-005", "Instrumentl Gap — Grant Tracking", "Import grant data from CSV/spreadsheet", "pass", "-", "MigrationImportPage + ProjectWorkspace.csvImportOpen. Accepts .csv,.tsv,.xlsx,.xls."),
    ("FM-IC-TRK-006", "Instrumentl Gap — Grant Tracking", "Filter and sort tracked grants", "pass", "-", "trackerStatusFilter + trackerSort."),

    # Deadlines & Tasks (4)
    ("FM-IC-DLN-001", "Instrumentl Gap — Deadlines & Tasks", "Automated email deadline reminders", "pass", "-", "check-deadlines + process-notifications + send-reminders pipeline."),
    ("FM-IC-DLN-002", "Instrumentl Gap — Deadlines & Tasks", "Calendar view for deadlines", "pass", "-", "ProjectWorkspace 'calendar' tab."),
    ("FM-IC-DLN-003", "Instrumentl Gap — Deadlines & Tasks", "Create and assign tasks", "pass", "-", "MyTasksPage.tsx assignee_email field."),
    ("FM-IC-DLN-004", "Instrumentl Gap — Deadlines & Tasks", "Deadlines sync with Google Calendar / Outlook", "pass", "-", "calendar-feed edge function exposes token-authenticated .ics."),

    # Collaboration (3)
    ("FM-IC-COL-001", "Instrumentl Gap — Collaboration", "Invite team members with roles", "pass", "-", "TeamSettingsPage roles: admin/editor/viewer/partner; ROLE_CONFIG matrix."),
    ("FM-IC-COL-002", "Instrumentl Gap — Collaboration", "External partners with scoped access", "pass", "-", "'partner' role in TeamSettings perm matrix."),
    ("FM-IC-COL-003", "Instrumentl Gap — Collaboration", "Updates shared via email/calendar without login", "pass", "-", "share-link tokenized links; SharedViewPage without auth."),

    # AI Writing (2)
    ("FM-IC-AI-001", "Instrumentl Gap — AI Writing", "AI generates grant proposal draft", "pass", "-", "GrantWriter.tsx + ai-draft edge function."),
    ("FM-IC-AI-002", "Instrumentl Gap — AI Writing", "AI resurfaces/learns from past successful applications", "pass", "-", "ApplicationsPage KBEntry { outcome, use_for_learning } + handleUpdateEntry. GrantWriter surfaces 'Learning from N of your past application(s) (M awarded)…'."),

    # Notifications (3)
    ("FM-IC-NTF-001", "Instrumentl Gap — Notifications", "Email on new matching grants found", "pass", "-", "process-notifications + notification_preferences.realtime_matches toggle."),
    ("FM-IC-NTF-002", "Instrumentl Gap — Notifications", "Alerts when funder changes deadline", "pass", "-", "fetch-grant-deadline + check-deadlines surface changes."),
    ("FM-IC-NTF-003", "Instrumentl Gap — Notifications", "Task reminders for assigned tasks", "pass", "-", "MyTasksPage assigned tasks tied to notification queue."),

    # Reporting (3)
    ("FM-IC-RPT-001", "Instrumentl Gap — Reporting", "Portfolio-level reporting dashboard", "pass", "-", "PortfolioPage + ReportsPage + reports-portfolio edge function."),
    ("FM-IC-RPT-002", "Instrumentl Gap — Reporting", "Post-award compliance + reporting requirements", "pass", "-", "STATUS BUMP this audit: PARTIAL -> PASS. PR #177 added ComplianceRequirement type with status enum (upcoming/in_progress/submitted/approved/overdue), due_date, deliverables[] checklist, attachments[], assignee_email, completed_at. ProjectWorkspace.tsx imports + uses loadCompliance(grantId) -> /functions/v1/compliance."),
    ("FM-IC-RPT-003", "Instrumentl Gap — Reporting", "Export funder/grant data as CSV", "pass", "-", "ReportsPage + PortfolioPage CSV export buttons."),

    # Customization (2)
    ("FM-IC-CFG-001", "Instrumentl Gap — Customization", "Custom data fields on funders/opportunities", "fail", "Low", "No custom-field schema found. Funders + tracked-grants tables use fixed columns. Low priority for SMB ICP — Instrumentl positions this as Enterprise feature. Flagged for fundermatch-feature-builder follow-up."),
    ("FM-IC-CFG-002", "Instrumentl Gap — Customization", "API for workflow automation", "partial", "Low", "Supabase REST + edge functions act as the API surface. No public OpenAPI yet. Low priority — SMB nonprofits rarely build integrations. Flagged for fundermatch-feature-builder follow-up."),

    # Peer Comparison (2)
    ("FM-IC-PEER-001", "Instrumentl Gap — Peer Comparison", "Compare org against peer nonprofits", "pass", "-", "PeerComparison.tsx component (10.7 KB); /projects/:id/peers tab."),
    ("FM-IC-PEER-002", "Instrumentl Gap — Peer Comparison", "990 tax filing data synthesized into funder insights", "pass", "-", "FunderDetail '990 Giving Trends' section + get-funder-990-insights edge function."),
]

# Combine all FM tests
FM_TESTS = FM_STANDARD + FM_LM + FM_IC

# ============================================================
# Summary sheet
# ============================================================
ws_sum = wb.active
ws_sum.title = "Summary"
ws_sum.append(["Daily Usability Audit — 2026-06-15"])
ws_sum["A1"].font = Font(bold=True, size=16, name="Arial")
ws_sum.merge_cells("A1:J1")
ws_sum.append([])
ws_sum.append(["Site", "First Impressions", "Accessibility", "Forms & Inputs", "Navigation & IA", "Performance", "Mobile", "Content Quality", "Backend", "Aggregate"])
style_header(ws_sum, row=3)
ws_sum.append(["website-auditor.io", 9.5, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 9.94])
ws_sum.append(["kevinarmstrong.io", 9.5, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 9.94])
ws_sum.append(["fundermatch.org", 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0])
for r in range(4, 7):
    for c in range(1, 11):
        cell = ws_sum.cell(row=r, column=c)
        cell.alignment = CENTER
        cell.border = BORDER
        cell.font = BODY_FONT
set_widths(ws_sum, [22, 12, 12, 13, 14, 12, 10, 14, 10, 12])

ws_sum.append([])
ws_sum.append(["Test counts per site"])
ws_sum["A8"].font = Font(bold=True, size=12, name="Arial")
ws_sum.append(["Site", "Test cases", "Pass", "Partial", "Warn", "Fail", "Skip"])
style_header(ws_sum, row=9)


def counts(rows):
    p = w = pa = f = sk = 0
    for r in rows:
        s = r[3].lower()
        if s == "pass": p += 1
        elif s == "partial": pa += 1
        elif s in ("warn", "warning"): w += 1
        elif s == "fail": f += 1
        elif s == "skip": sk += 1
    return p, pa, w, f, sk


w_p, w_pa, w_w, w_f, w_sk = counts(WAO_TESTS)
k_p, k_pa, k_w, k_f, k_sk = counts(KAIO_TESTS)
f_p, f_pa, f_w, f_f, f_sk = counts(FM_TESTS)

ws_sum.append(["website-auditor.io", len(WAO_TESTS), w_p, w_pa, w_w, w_f, w_sk])
ws_sum.append(["kevinarmstrong.io", len(KAIO_TESTS), k_p, k_pa, k_w, k_f, k_sk])
ws_sum.append(["fundermatch.org", len(FM_TESTS), f_p, f_pa, f_w, f_f, f_sk])

for r in range(10, 13):
    for c in range(1, 8):
        cell = ws_sum.cell(row=r, column=c)
        cell.alignment = CENTER
        cell.border = BORDER
        cell.font = BODY_FONT

# Instrumentl gap coverage
ws_sum.append([])
ws_sum.append(["Instrumentl gap coverage (43 tests)"])
ws_sum["A14"].font = Font(bold=True, size=12, name="Arial")
ic_p, ic_pa, ic_w, ic_f, ic_sk = counts(FM_IC)
ws_sum.append(["PASS", "PARTIAL", "FAIL", "SKIP", "Total"])
style_header(ws_sum, row=15)
ws_sum.append([ic_p, ic_pa, ic_f, ic_sk, len(FM_IC)])
for c in range(1, 6):
    cell = ws_sum.cell(row=16, column=c)
    cell.alignment = CENTER
    cell.border = BORDER
    cell.font = BODY_FONT

ws_sum.append([])
ws_sum.append(["Notes"])
ws_sum["A18"].font = Font(bold=True, size=12, name="Arial")
ws_sum.append([f"1 PR opened: SpikeyCoder/my_website #88 (fix typo 'integation' -> 'integration' on KAIO homepage). See 'PRs opened' sheet."])
ws_sum.append(["2 owner exceptions logged (kevinarmstrong.io subheader green #7AED8C, website-auditor.io Gartner citation). See 'Owner exceptions' sheet."])
ws_sum.append(["fundermatch.org light-mode contrast: 7/7 PASS. See FM-LM rows on fundermatch.org sheet."])
ws_sum.append([f"Instrumentl competitive gap: {ic_p} PASS / {ic_pa} PARTIAL / {ic_f} FAIL of {len(FM_IC)}. Bumps this audit: FM-IC-ONB-002 (advisor) and FM-IC-RPT-002 (post-award) both PARTIAL -> PASS. Feature builder task to pick up remaining FAIL + PARTIALs."])
ws_sum.append(["Regression checks for fundermatch.org: 10/10 PASS. See Regression-Tracking sheet."])

# ============================================================
# Site sheets
# ============================================================
ws_wao = wb.create_sheet("website-auditor.io")
write_tests(ws_wao, WAO_TESTS)
ws_kaio = wb.create_sheet("kevinarmstrong.io")
write_tests(ws_kaio, KAIO_TESTS)
ws_fm = wb.create_sheet("fundermatch.org")
write_tests(ws_fm, FM_TESTS)

# PRs opened
ws_pr = wb.create_sheet("PRs opened")
ws_pr.append(["Repo", "PR #", "Branch", "Title", "URL", "Notes"])
style_header(ws_pr)
ws_pr.append([
    "SpikeyCoder/my_website",
    "88",
    "usability/2026-06-15-fixes",
    "usability(2026-06-15): fix typo 'integation' -> 'integration' in Apply & Buy project card",
    "https://github.com/SpikeyCoder/my_website/pull/88",
    "Single-character P3 typo on Apple Pay project card line 307. Fixed and pushed."
])
ws_pr.append([
    "SpikeyCoder/chaos_tester",
    "—",
    "—",
    "(no PR — no fixable issues found)",
    "—",
    "All standard tests PASS. Loading-state and 'Not the right business?' regressions both PASS. Gartner citation kept per owner exception."
])
ws_pr.append([
    "SpikeyCoder/funder-finder",
    "—",
    "—",
    "(no PR — no fixable standard-audit issues found)",
    "—",
    "All 78 standard + light-mode + regression tests PASS. 2 Instrumentl gap items (FM-IC-CFG-001 custom fields FAIL Low, FM-IC-CFG-002 public API PARTIAL Low) deferred to fundermatch-feature-builder task per spec."
])
for r in range(2, 5):
    for c in range(1, 7):
        cell = ws_pr.cell(row=r, column=c)
        cell.alignment = LEFT
        cell.border = BORDER
        cell.font = BODY_FONT
set_widths(ws_pr, [26, 8, 30, 60, 60, 60])
ws_pr.freeze_panes = "A2"

# Owner exceptions
ws_oe = wb.create_sheet("Owner exceptions")
ws_oe.append(["Site", "Item", "Test ID", "Reason kept", "Action"])
style_header(ws_oe)
ws_oe.append([
    "kevinarmstrong.io",
    "Hero subheader green #7AED8C on #2596be background",
    "KAIO-FI-005",
    "Owner prefers #7AED8C green despite WCAG contrast considerations. Task spec lists explicitly as DO-NOT-auto-fix.",
    "Flagged WARN. Not auto-fixed. Not pushed in PR."
])
ws_oe.append([
    "website-auditor.io",
    "Hero Gartner '50% by 2028' citation",
    "WAO-FI-011",
    "Kept as directional marketing forecast. Owner exception per prior audits.",
    "Flagged WARN. Not auto-fixed."
])
ws_oe.append([
    "website-auditor.io",
    "/features page intentionally removed",
    "(intentional)",
    "Owner removed as redundant; distracted from URL entry goal.",
    "Not flagged. Not recommended for re-add."
])
ws_oe.append([
    "website-auditor.io",
    "/how-it-works page + 'How It Works' section intentionally removed",
    "(intentional)",
    "Owner removed as redundant with sample report.",
    "Not flagged. Not recommended for re-add."
])
ws_oe.append([
    "website-auditor.io",
    "FAQ section intentionally removed",
    "(intentional)",
    "Owner removed as redundant and outdated.",
    "Not flagged. Not recommended for re-add."
])
for r in range(2, 7):
    for c in range(1, 6):
        cell = ws_oe.cell(row=r, column=c)
        cell.alignment = LEFT
        cell.border = BORDER
        cell.font = BODY_FONT
set_widths(ws_oe, [22, 38, 18, 60, 50])
ws_oe.freeze_panes = "A2"

# Regression tracking — fundermatch.org
ws_rt = wb.create_sheet("Regression-Tracking")
ws_rt.append(["Site", "Regression item", "Status", "Notes"])
style_header(ws_rt)
fm_regressions = [
    ("fundermatch.org", "Privacy Policy link works (not 404)", "pass", "GET /privacy -> 200; PrivacyPolicy.tsx renders boilerplate sections."),
    ("fundermatch.org", "Terms of Service link works", "pass", "GET /terms -> 200; TermsOfService.tsx renders."),
    ("fundermatch.org", "Contact page works (not 404)", "pass", "GET /contact -> 200; ContactPage.tsx renders email + form."),
    ("fundermatch.org", "Keyboard focus indicators present", "pass", "*:focus-visible outline-2 outline-offset-2 outline-[#58a6ff] in src/index.css line 9."),
    ("fundermatch.org", "Form validation shows error messages", "pass", "SignupPage step-validation + Toast component; ErrorBoundary wraps all routes."),
    ("fundermatch.org", "Body text contrast passes WCAG AA", "pass", "Dark mode: text-white on #0d1117 ~17:1. Light mode: text-gray-400 -> #59636e !important ~6.5:1."),
    ("fundermatch.org", "Search input has aria-label", "pass", "FilterPanel inputs all carry aria-label."),
    ("fundermatch.org", "prefers-reduced-motion rule active", "pass", "src/index.css @media (prefers-reduced-motion: reduce) zeroes animation + transition."),
    ("fundermatch.org", "Data stats section visible on homepage", "pass", "Landing.tsx 460K+ funders / 449K+ grantees / 7.5M+ grants / 1.1M+ 990 filings rendered."),
    ("fundermatch.org", "Trust signals visible on homepage", "pass", "3 trust chips: IRS 990 filings, free no credit card, data never shared."),
]
for r in fm_regressions:
    ws_rt.append(list(r))
    last = ws_rt.max_row
    fill = status_fill(r[2])
    for c in range(1, 5):
        cell = ws_rt.cell(row=last, column=c)
        cell.alignment = LEFT
        cell.border = BORDER
        cell.font = BODY_FONT
        if fill: cell.fill = fill
set_widths(ws_rt, [22, 60, 10, 80])
ws_rt.freeze_panes = "A2"

# Save
import os
out = "/sessions/tender-determined-keller/mnt/outputs/daily_usability_audit_2026-06-15.xlsx"
os.makedirs(os.path.dirname(out), exist_ok=True)
wb.save(out)
print(f"Wrote {out}")
print(f"WAO {len(WAO_TESTS)} tests")
print(f"KAIO {len(KAIO_TESTS)} tests")
print(f"FM {len(FM_TESTS)} tests (standard {len(FM_STANDARD)} + LM {len(FM_LM)} + IC {len(FM_IC)})")
print(f"Total {len(WAO_TESTS) + len(KAIO_TESTS) + len(FM_TESTS)}")
print(f"Instrumentl gap: PASS={ic_p} PARTIAL={ic_pa} FAIL={ic_f} SKIP={ic_sk}")
