"""Build the daily usability audit Excel report for 2026-06-18.

Sheets: Summary, website-auditor.io, kevinarmstrong.io, fundermatch.org,
PRs opened, Owner exceptions, Regression-Tracking.

Data collected via direct inspection of the cloned repos on 2026-06-18:
  - SpikeyCoder/chaos_tester   @ 8e9bd71
  - SpikeyCoder/my_website     @ a188fdb
  - SpikeyCoder/funder-finder  @ 983977b

Generated by the daily-usability-audit scheduled task.
"""
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = Workbook()

HEADER_FILL = PatternFill(start_color="1F2937", end_color="1F2937", fill_type="solid")
HEADER_FONT = Font(bold=True, color="FFFFFF", size=11, name="Arial")
BODY_FONT = Font(name="Arial", size=10)
PASS_FILL = PatternFill(start_color="D1FAE5", end_color="D1FAE5", fill_type="solid")
FAIL_FILL = PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid")
WARN_FILL = PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid")
SKIP_FILL = PatternFill(start_color="E5E7EB", end_color="E5E7EB", fill_type="solid")
INFO_FILL = PatternFill(start_color="DBEAFE", end_color="DBEAFE", fill_type="solid")
PARTIAL_FILL = PatternFill(start_color="FED7AA", end_color="FED7AA", fill_type="solid")
THIN = Side(border_style="thin", color="D1D5DB")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
LEFT = Alignment(horizontal="left", vertical="top", wrap_text=True)


def style_header(ws, row=1):
    for c in ws[row]:
        c.fill = HEADER_FILL
        c.font = HEADER_FONT
        c.alignment = CENTER
        c.border = BORDER


def set_widths(ws, widths):
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w


def status_fill(s):
    s = (s or "").lower()
    return {
        "pass": PASS_FILL, "fail": FAIL_FILL, "warn": WARN_FILL,
        "warning": WARN_FILL, "skip": SKIP_FILL, "info": INFO_FILL,
        "partial": PARTIAL_FILL,
    }.get(s)


def write_tests(ws, tests):
    ws.append(["Test ID", "Category", "Test", "Status", "Severity", "Notes"])
    style_header(ws)
    for row in tests:
        ws.append(list(row))
        last_row = ws.max_row
        fill = status_fill(row[3])
        for ci in range(1, 7):
            cell = ws.cell(row=last_row, column=ci)
            cell.alignment = LEFT
            cell.border = BORDER
            cell.font = BODY_FONT
            if fill is not None:
                cell.fill = fill
    set_widths(ws, [14, 24, 60, 10, 10, 80])
    ws.freeze_panes = "A2"


# ============================================================
# WEBSITE-AUDITOR.IO  (chaos_tester @ 8e9bd71)
# ============================================================
WAO_TESTS = [
    # First Impressions (12)
    ("WAO-FI-001", "First Impressions", "Homepage explains product (AI visibility + security + perf)", "pass", "-", "Live GET / -> HTTP/2 200. <title> 'Free Website Audit Tool — AI Visibility, Security & Performance Scanner | Website Auditor'."),
    ("WAO-FI-002", "First Impressions", "Value proposition immediately obvious", "pass", "-", "Hero 'Does ChatGPT recommend your business?' + URL input + 'Check my site' button above the fold."),
    ("WAO-FI-003", "First Impressions", "Primary CTA clear and compelling", "pass", "-", "'Check my site' submit button anchors the hero form; 'View Sample Report' secondary card surfaces /sample-report."),
    ("WAO-FI-004", "First Impressions", "GET / responds quickly through Cloudflare edge", "pass", "-", "HTTP/2 200 from Cloudflare edge; cf-cache-status DYNAMIC."),
    ("WAO-FI-005", "First Impressions", "Visual hierarchy (one H1, multiple H2/H3)", "pass", "-", "1 H1 ('Does ChatGPT recommend your business?'); H2s/H3s present."),
    ("WAO-FI-006", "First Impressions", "Trust signals on homepage", "pass", "-", "Industry strip + testimonials (Jake Morrison, Sarah Patel) + sample-report preview."),
    ("WAO-FI-007", "First Impressions", "Navigation intuitive (3 top-level items)", "pass", "-", "Sample Report / API / Contact - short, jargon-free."),
    ("WAO-FI-008", "First Impressions", "Hero works on mobile (viewport meta correct)", "pass", "-", "<meta viewport='width=device-width, initial-scale=1.0'>; hamburger #navToggle with aria-controls=mainNav."),
    ("WAO-FI-009", "First Impressions", "No broken images on home", "pass", "-", "Hero is inline SVG; logo.svg + favicon.svg both 200."),
    ("WAO-FI-010", "First Impressions", "Default body font readable", "pass", "-", "Inter @ 16px base; JetBrains Mono for code; preconnect to fonts.googleapis.com + fonts.gstatic.com."),
    ("WAO-FI-011", "First Impressions", "Hero Gartner claim - honesty / non-misleading", "warn", "P3", "Owner exception per task spec. Hero cites 'By 2028, 50% of customers will find your competitors through AI according to Gartner'. Kept as directional marketing forecast."),
    ("WAO-FI-012", "First Impressions", "Above-the-fold CTA reachable without scroll", "pass", "-", "URL input + Check-my-site button inside .landing-hero render above the fold at 1280x800."),

    # Accessibility (16)
    ("WAO-AX-001", "Accessibility", "lang attribute set on <html>", "pass", "-", "templates/base.html: <html lang='en'>."),
    ("WAO-AX-002", "Accessibility", "Skip-to-content link present", "pass", "-", "<a href='#main-content' class='skip-link'> in base.html immediately after <body>."),
    ("WAO-AX-003", "Accessibility", "All images have alt or role='presentation'", "pass", "-", "logo.svg uses alt='' + aria-hidden='true' (decorative). SVG icons use focusable='false'. No <img> without alt found."),
    ("WAO-AX-004", "Accessibility", "Hamburger button has aria-expanded + aria-controls", "pass", "-", "id='navToggle' with aria-label='Toggle navigation menu' aria-expanded='false' aria-controls='mainNav'."),
    ("WAO-AX-005", "Accessibility", "URL input has aria-label", "pass", "-", "<input type='url' id='base_url' aria-label='Website URL to audit'> in dashboard.html."),
    ("WAO-AX-006", "Accessibility", "Submit button has aria-label", "pass", "-", "<button class='btn-audit' aria-label='Check my site'>."),
    ("WAO-AX-007", "Accessibility", "Form submit announces busy state to AT", "pass", "-", "static/js/dashboard.js sets aria-busy='true' on submit; clears on response."),
    ("WAO-AX-008", "Accessibility", "color-scheme + theme-color meta set", "pass", "-", "<meta name='theme-color' content='#0f172a'> + <meta name='color-scheme' content='dark light'>."),
    ("WAO-AX-009", "Accessibility", "Heading hierarchy on dashboard (no skipped levels)", "pass", "-", "H1 hero -> H2 'What We Check' + 'Ready to Improve Your Website?' -> H3 feature cards."),
    ("WAO-AX-010", "Accessibility", "Form labels associated with all inputs", "pass", "-", "Required fields use either <label for=...> or aria-label."),
    ("WAO-AX-011", "Accessibility", "Focus indicators present on interactive elements", "pass", "-", "base.css :focus-visible outline 2px solid var(--accent)."),
    ("WAO-AX-012", "Accessibility", "Touch targets >= 32x32 on mobile", "pass", "-", "#biz-name-wrong-btn { min-height:32px; padding:4px 8px }; skip link 44x44 on focus."),
    ("WAO-AX-013", "Accessibility", "prefers-reduced-motion handling", "pass", "-", "base.css @media (prefers-reduced-motion: reduce) zeroes animation + transition."),
    ("WAO-AX-014", "Accessibility", "ARIA landmarks present", "pass", "-", "<header>, <main id='main-content'>, <footer> all present in base.html."),
    ("WAO-AX-015", "Accessibility", "Body text contrast >= 4.5:1 (WCAG AA)", "pass", "-", "Inter 16px on dark surface; --text #e2e8f0 on #0f172a approx 13:1."),
    ("WAO-AX-016", "Accessibility", "Sample-report brand icons aria-hidden", "pass", "-", "9 platform icons (ChatGPT/Perplexity/Claude/Gemini/etc.) carry aria-hidden='true'."),

    # Forms & Inputs (12)
    ("WAO-FORM-001", "Forms & Inputs", "URL input accepts valid URLs", "pass", "-", "type='url' input with required attribute; browser-native URL validation."),
    ("WAO-FORM-002", "Forms & Inputs", "Submit blocked when URL empty", "pass", "-", "Button starts disabled; syncAuditBtnState() enables only when URL valid + biz info present."),
    ("WAO-FORM-003", "Forms & Inputs", "Form provides feedback on submit", "pass", "-", "loading-indicator overlay appears below the search bar; showAuditSpinner() called."),
    ("WAO-FORM-004", "Forms & Inputs", "Rate limit 429 surfaces friendly message", "pass", "-", "fetch handler: status === 429 -> showRateLimitMessage(body.message || 'Too many requests')."),
    ("WAO-FORM-005", "Forms & Inputs", "CSRF token included on form", "pass", "-", "<input type='hidden' name='csrf_token' value='{{ csrf_token() }}'>."),
    ("WAO-FORM-006", "Forms & Inputs", "autocomplete='url' on URL field", "pass", "-", "<input type='url' autocomplete='url'>."),
    ("WAO-FORM-007", "Forms & Inputs", "Placeholder text useful + readable", "pass", "-", "placeholder='Enter your website URL (e.g., https://yourbusiness.com)'."),
    ("WAO-FORM-008", "Forms & Inputs", "Form error recovery (submit-fix-resubmit)", "pass", "-", "Error response clears indicator + aria-busy + spinner; form re-enabled."),
    ("WAO-FORM-009", "Forms & Inputs", "REGRESSION: 'Not the right business?' re-enables Check my site", "pass", "-", "biz-name-wrong-btn click handler hides confirmed row, shows override fields, calls syncAuditBtnState() which re-enables submit when valid. No freeze observed."),
    ("WAO-FORM-010", "Forms & Inputs", "REGRESSION: Loading state - no hourglass emoji, no shift, proper CSS spinner", "pass", "-", "dashboard.css .loading-indicator-overlay { position:absolute; top:100%; margin-top:12px } sits BELOW the search bar. Spinner is CSS .btn-spinner animated by @keyframes spin. 0 hourglass emoji in dashboard.html or dashboard.js."),
    ("WAO-FORM-011", "Forms & Inputs", "Helpful CTA hint when business identifier open", "pass", "-", "#audit-cta-hint aria-live='polite' renders 'Complete the fields below to run your audit' when button disabled."),
    ("WAO-FORM-012", "Forms & Inputs", "Auto-detect business name on URL blur (debounced)", "pass", "-", "blur listener with _isMobile delay (400ms/150ms); input listener debounces 600ms before detectBusiness()."),

    # Navigation & IA (10)
    ("WAO-NAV-001", "Navigation & IA", "Top-level nav links - Sample Report works", "pass", "-", "GET /sample-report -> HTTP/2 200."),
    ("WAO-NAV-002", "Navigation & IA", "Top-level nav links - API works", "pass", "-", "GET /api -> HTTP/2 200."),
    ("WAO-NAV-003", "Navigation & IA", "Top-level nav links - Contact works", "pass", "-", "GET /contact -> HTTP/2 200."),
    ("WAO-NAV-004", "Navigation & IA", "Footer link - Privacy", "pass", "-", "GET /privacy -> HTTP/2 200."),
    ("WAO-NAV-005", "Navigation & IA", "Footer link - Terms", "pass", "-", "GET /terms -> HTTP/2 200."),
    ("WAO-NAV-006", "Navigation & IA", "404 page rendered for unknown paths", "pass", "-", "GET /nonexistent-test-xyz -> 404 with templates/404.html."),
    ("WAO-NAV-007", "Navigation & IA", "Logo links back to home", "pass", "-", "<div class='site-title'><a href='/'>Website Auditor</a></div>."),
    ("WAO-NAV-008", "Navigation & IA", "Mobile hamburger has aria-expanded toggle", "pass", "-", "#navToggle aria-expanded starts 'false'; JS toggles 'true' on click."),
    ("WAO-NAV-009", "Navigation & IA", "Canonical URL on every page", "pass", "-", "base.html: <link rel='canonical' href='https://website-auditor.io{{ request.path }}'>."),
    ("WAO-NAV-010", "Navigation & IA", "/changelog accessible", "pass", "-", "GET /changelog -> 200."),

    # Performance & Loading (10)
    ("WAO-PERF-001", "Performance & Loading", "HTML payload < 100 KB compressed", "pass", "-", "GET / -> ~30 KB via Cloudflare edge."),
    ("WAO-PERF-002", "Performance & Loading", "Cloudflare HTTP/2 with brotli/gzip", "pass", "-", "HTTP/2 200; content-encoding negotiated by cf edge."),
    ("WAO-PERF-003", "Performance & Loading", "Critical assets preloaded", "pass", "-", "<link rel='preload' href='/static/logo.svg' as='image'> + favicon.svg preloaded."),
    ("WAO-PERF-004", "Performance & Loading", "Font preconnect", "pass", "-", "<link rel='preconnect' href='https://fonts.googleapis.com'> + fonts.gstatic.com crossorigin."),
    ("WAO-PERF-005", "Performance & Loading", "HSTS max-age=63072000", "pass", "-", "strict-transport-security: max-age=63072000; includeSubDomains; preload."),
    ("WAO-PERF-006", "Performance & Loading", "JS lives in /static/js - long-cache candidate", "pass", "-", "static/js/dashboard.js + others served from /static/js/."),
    ("WAO-PERF-007", "Performance & Loading", "No render-blocking inline scripts on home", "pass", "-", "Only application/ld+json + small inline init - main JS loaded at end of body."),
    ("WAO-PERF-008", "Performance & Loading", "alt-svc h3 advertised", "pass", "-", "alt-svc: h3=':443'; ma=86400."),
    ("WAO-PERF-009", "Performance & Loading", "report-uri set for CSP violations", "pass", "-", "CSP report-uri /api/csp-report + report-to csp-endpoint."),
    ("WAO-PERF-010", "Performance & Loading", "Cache-control private prevents shared-cache leakage", "pass", "-", "cache-control: private - sessioned HTML not cached by intermediaries."),

    # Mobile Responsiveness (10)
    ("WAO-MOB-001", "Mobile Responsiveness", "Viewport meta scales correctly", "pass", "-", "<meta name='viewport' content='width=device-width, initial-scale=1.0'>."),
    ("WAO-MOB-002", "Mobile Responsiveness", "Hamburger menu activates < 768px", "pass", "-", "base.css media query toggles .hamburger { display:flex } below 768px breakpoint."),
    ("WAO-MOB-003", "Mobile Responsiveness", "Hero form stacks vertically on mobile", "pass", "-", ".hero-search flex-direction:column under 640px."),
    ("WAO-MOB-004", "Mobile Responsiveness", "Touch targets >= 32x32 on biz-name toggle", "pass", "-", "#biz-name-wrong-btn { min-height:32px; padding:4px 8px }."),
    ("WAO-MOB-005", "Mobile Responsiveness", "No horizontal scroll at 375px", "pass", "-", "body { overflow-x: hidden }; .container max-width responsive."),
    ("WAO-MOB-006", "Mobile Responsiveness", "Submit button full-width on mobile", "pass", "-", ".btn-audit width:100% under 640px."),
    ("WAO-MOB-007", "Mobile Responsiveness", "Font size >= 16px to avoid iOS zoom", "pass", "-", "body font-size 16px; input font-size 16px."),
    ("WAO-MOB-008", "Mobile Responsiveness", "Sample-report 'View Sample Report' button meets 44x44", "pass", "-", ".u-btn-padding-lg min-height:44px with inline-flex centering."),
    ("WAO-MOB-009", "Mobile Responsiveness", "Loading indicator stays visible on mobile", "pass", "-", "Position absolute relative to .hero-search; renders below input column."),
    ("WAO-MOB-010", "Mobile Responsiveness", "API upsell card wraps gracefully on mobile", "pass", "-", ".api-upsell-row flex-wrap:wrap + gap:24px."),

    # Content Quality (6)
    ("WAO-CQ-001", "Content Quality", "No typos in hero/marketing copy", "pass", "-", "Spot-check of dashboard.html clean."),
    ("WAO-CQ-002", "Content Quality", "Privacy page reachable + populated", "pass", "-", "GET /privacy -> 200; templates/privacy.html non-empty."),
    ("WAO-CQ-003", "Content Quality", "Terms page reachable + populated", "pass", "-", "GET /terms -> 200; templates/terms.html non-empty."),
    ("WAO-CQ-004", "Content Quality", "Contact page has working channel", "pass", "-", "GET /contact -> 200."),
    ("WAO-CQ-005", "Content Quality", "OG image present + correct dimensions", "pass", "-", "GET /static/og-image.png -> 200 (1200x630)."),
    ("WAO-CQ-006", "Content Quality", "JSON-LD Organization name correct", "pass", "-", "Commits dda1453 + 5a8dc9c set Organization schema name to 'Armstrong HoldCo LLC' while keeping SoftwareApplication as 'Website Auditor'."),

    # Backend Integration (13)
    ("WAO-BE-001", "Backend Integration", "POST /run accepts CSRF-validated submissions", "pass", "-", "app.py /run route validates CSRF; dashboard.js sends X-Requested-With + csrf_token."),
    ("WAO-BE-002", "Backend Integration", "POST /run returns 202 + redirect to /progress on accept", "pass", "-", "dashboard.js: if (r.status === 202) window.location.href = '/progress'."),
    ("WAO-BE-003", "Backend Integration", "POST /run returns 429 with body.message on rate limit", "pass", "-", "Handler surfaces body.message via showRateLimitMessage()."),
    ("WAO-BE-004", "Backend Integration", "Errors surface user-friendly text (not stack trace)", "pass", "-", "Error responses -> showRateLimitMessage('Failed to start audit.')."),
    ("WAO-BE-005", "Backend Integration", "/api JSON docs reachable", "pass", "-", "GET /api -> 200; meta description correctly cites $10/month subscription (commit 41ba127)."),
    ("WAO-BE-006", "Backend Integration", "Admin portal lives off-site", "pass", "-", "Footer href https://api.website-auditor.io/admin_portal/."),
    ("WAO-BE-007", "Backend Integration", "Maps API loaded under CSP allowlist", "pass", "-", "CSP connect-src includes https://maps.googleapis.com."),
    ("WAO-BE-008", "Backend Integration", "Funnel events tracked once per page", "pass", "-", "dashboard.js _funnelAuditStartedFired guard."),
    ("WAO-BE-009", "Backend Integration", "Server-Sent Events progress endpoint reachable", "pass", "-", "/progress route in app.py streams audit status updates via SSE."),
    ("WAO-BE-010", "Backend Integration", "CSP report-uri receives violations", "pass", "-", "/api/csp-report endpoint."),
    ("WAO-BE-011", "Backend Integration", "Goatcounter analytics endpoint allowed", "pass", "-", "CSP connect-src https://website-auditor.goatcounter.com."),
    ("WAO-BE-012", "Backend Integration", "session cookie Secure + HttpOnly + SameSite=Lax", "pass", "-", "set-cookie: session=...; Secure; HttpOnly; Path=/; SameSite=Lax."),
    ("WAO-BE-013", "Backend Integration", "NEW: SPA catch-all detection eliminates false positives (commit 8e9bd71)", "pass", "-", "Today's commit 8e9bd71 adds spa_detection.py + is_spa_catchall(). Security/auth scanners check SPA shell markers (<div id='root'>, <app-root>, <div id='__next'>, etc.) before flagging /.env / /admin / /api/swagger.json / HTTP DELETE as exposed. Conservative: non-HTML extensions (.env/.sql/.py/.yml/.json) must return SPA shell to suppress; HTML paths must hit known marker + non-empty body."),
]


# ============================================================
# KEVINARMSTRONG.IO  (my_website @ a188fdb)
# ============================================================
KAIO_TESTS = [
    # First Impressions (12)
    ("KAIO-FI-001", "First Impressions", "Home title - PM coaching CTR (commit 9ad7c5f)", "pass", "-", "<title>PM Interview Coaching - Land Your Next Product Manager Role | Kevin Armstrong</title>; meta description present."),
    ("KAIO-FI-002", "First Impressions", "Single H1 above the fold", "pass", "-", "Curl scan: H1 count 1, H2 count 7 - clean hierarchy."),
    ("KAIO-FI-003", "First Impressions", "Value proposition immediate", "pass", "-", "Subtitle 'Shipping iOS apps and payment systems that make money'."),
    ("KAIO-FI-004", "First Impressions", "GET / responds quickly via Cloudflare Pages", "pass", "-", "HTTP/2 200 in ~0.3s; cache-control public, max-age=0, must-revalidate."),
    ("KAIO-FI-005", "First Impressions", "Hero subheader uses owner-chosen green #7AED8C", "warn", "-", "OWNER EXCEPTION per task spec. #7AED8C green on #2596be background NOT auto-fixed. Logged in Owner exceptions sheet."),
    ("KAIO-FI-006", "First Impressions", "Trust signals - career stats on home", "pass", "-", "Stats: '2MM+ customers (2024-2026 tenure)' + '$13.2MM annual GMS (5x baseline)'."),
    ("KAIO-FI-007", "First Impressions", "Logo / favicon set across sizes", "pass", "-", "favicon.ico + 16/32/48 PNG + apple-touch-icon.png all referenced."),
    ("KAIO-FI-008", "First Impressions", "OG image set for shareability", "pass", "-", "<meta property='og:image' content='https://kevinarmstrong.io/apple-touch-icon.png'>."),
    ("KAIO-FI-009", "First Impressions", "Twitter card meta - PM coaching CTR refresh", "pass", "-", "twitter:card summary_large_image + PM coaching title/description tuned for CTR."),
    ("KAIO-FI-010", "First Impressions", "canonical set to root", "pass", "-", "<link rel='canonical' href='https://kevinarmstrong.io/'>."),
    ("KAIO-FI-011", "First Impressions", "Preconnect to CDN", "pass", "-", "2 rel=preconnect hints (cdn.jsdelivr.net + gc.zgo.at)."),
    ("KAIO-FI-012", "First Impressions", "Body fonts readable (system stack)", "pass", "-", "styles.css system font-family stack; 16px base."),

    # Accessibility (16)
    ("KAIO-AX-001", "Accessibility", "lang attribute set on <html>", "pass", "-", "<html lang='en'>."),
    ("KAIO-AX-002", "Accessibility", "Skip-to-content link present", "pass", "-", "<a href='#main-content' class='skip-link'>Skip to content</a>."),
    ("KAIO-AX-003", "Accessibility", "All images have alt", "pass", "-", "10 <img> tags total; curl scan: 0 <img> without alt."),
    ("KAIO-AX-004", "Accessibility", "Aria landmarks present", "pass", "-", "<nav>, <main>, <footer>. aria-label='Main navigation' on nav."),
    ("KAIO-AX-005", "Accessibility", "Form inputs labeled (RSS controls)", "pass", "-", "23 aria-label attributes counted across RSS controls and social links."),
    ("KAIO-AX-006", "Accessibility", "aria-live regions for dynamic content", "pass", "-", "2 aria-live='polite' regions present."),
    ("KAIO-AX-007", "Accessibility", "color-scheme + theme-color meta set", "pass", "-", "<meta name='theme-color' content='#0b0f14'> + <meta name='color-scheme' content='dark light'>."),
    ("KAIO-AX-008", "Accessibility", "Heading hierarchy on home", "pass", "-", "H1 H2 H3 H3 H2 H3*7 H2 H3 H3 H2 H3 H3 H2 H2 H2 H3 H3 - no level skipped."),
    ("KAIO-AX-009", "Accessibility", "Decorative icons aria-hidden", "pass", "-", "12 aria-hidden='true' attributes."),
    ("KAIO-AX-010", "Accessibility", "External links rel=noopener", "pass", "-", "Curl scan: 0 target=_blank links missing rel=noopener (commit a188fdb today swaps rel=noopener noreferrer -> rel=noopener on FunderMatch portfolio link only — still has rel=noopener)."),
    ("KAIO-AX-011", "Accessibility", "Required field indicators", "pass", "-", "2 aria-required='true' attributes on inputs."),
    ("KAIO-AX-012", "Accessibility", "Social links have aria-labels", "pass", "-", "'Open LinkedIn profile', 'Open GitHub profile', 'Copy page URL'."),
    ("KAIO-AX-013", "Accessibility", "Body text contrast on dark theme", "pass", "-", "color #e6edf3 on #0b0f14 ~15:1."),
    ("KAIO-AX-014", "Accessibility", "Focus indicators on interactive elements", "pass", "-", "styles.css :focus-visible outline preserved."),
    ("KAIO-AX-015", "Accessibility", "Reduced-motion respected", "pass", "-", "@media (prefers-reduced-motion: reduce) rules in styles.css."),
    ("KAIO-AX-016", "Accessibility", "Tab navigation through nav + portfolio cards", "pass", "-", "All nav links and project cards are anchors - fully tab-accessible."),

    # Forms & Inputs (10)
    ("KAIO-FORM-001", "Forms & Inputs", "RSS / share form controls work", "pass", "-", "Toggle controls have aria-label + role=button; share has aria-live confirmation."),
    ("KAIO-FORM-002", "Forms & Inputs", "Booking form redirects to contact section", "pass", "-", "GET /booking/ -> 200, meta refresh to /#contact + visible 'click here' fallback link."),
    ("KAIO-FORM-003", "Forms & Inputs", "Form-action CSP includes Stripe + Google Calendar", "pass", "-", "CSP form-action 'self' https://buy.stripe.com https://calendar.app.google https://*.supabase.co."),
    ("KAIO-FORM-004", "Forms & Inputs", "All form inputs have visible labels or aria-label", "pass", "-", "aria-label attributes present on font-size/italic/underline RSS controls and social links."),
    ("KAIO-FORM-005", "Forms & Inputs", "URL field placeholder useful", "pass", "-", "No URL fields in form scope; n/a on portfolio site."),
    ("KAIO-FORM-006", "Forms & Inputs", "Search-style filtering on portfolio tag chips works", "pass", "-", "data-tags attribute on project cards used by main.js."),
    ("KAIO-FORM-007", "Forms & Inputs", "Permissions-policy locked down", "pass", "-", "permissions-policy denies geolocation, camera, microphone, payment, etc."),
    ("KAIO-FORM-008", "Forms & Inputs", "Cross-origin isolation strict", "pass", "-", "COEP credentialless, COOP same-origin, CORP same-origin."),
    ("KAIO-FORM-009", "Forms & Inputs", "javascript: links absent", "pass", "-", "Curl scan: 0 href='javascript:' links."),
    ("KAIO-FORM-010", "Forms & Inputs", "Empty href absent", "pass", "-", "Curl scan: 0 href='' entries."),

    # Navigation & IA (12)
    ("KAIO-NAV-001", "Navigation & IA", "Home -> /privacy/ responds 200", "pass", "-", "GET /privacy/ -> 200."),
    ("KAIO-NAV-002", "Navigation & IA", "Home -> /goingvegan/ responds 200", "pass", "-", "GET /goingvegan/ -> 200."),
    ("KAIO-NAV-003", "Navigation & IA", "Home -> /booking/ responds 200", "pass", "-", "GET /booking/ -> 200."),
    ("KAIO-NAV-004", "Navigation & IA", "Home -> /blog/ responds 200", "pass", "-", "GET /blog/ -> 200; meta tags refreshed for SEO."),
    ("KAIO-NAV-005", "Navigation & IA", "/terms-and-conditions/ follows redirect", "pass", "-", "GET /terms-and-conditions/ -> final 200."),
    ("KAIO-NAV-006", "Navigation & IA", "Non-existent slug returns 404", "pass", "-", "GET /nonexistent-test-xyz -> 404."),
    ("KAIO-NAV-007", "Navigation & IA", "Trailing-slash redirect for /privacy", "pass", "-", "GET /privacy -> 308 -> /privacy/ -> 200."),
    ("KAIO-NAV-008", "Navigation & IA", "Internal hrefs limited to canonical paths", "pass", "-", "Only /goingvegan/, /privacy/, /terms-and-conditions/ used."),
    ("KAIO-NAV-009", "Navigation & IA", "RSS feed reachable", "pass", "-", "GET /rss.json -> 200."),
    ("KAIO-NAV-010", "Navigation & IA", "career-acceleration hash anchor", "pass", "-", "main.js updatePageTitle() maps '#career-acceleration' -> 'Product Manager Interview Coaching | Kevin Armstrong'. Standalone path returns 404 (intentional)."),
    ("KAIO-NAV-011", "Navigation & IA", "Recent SEO refresh: unique meta descriptions on key pages", "pass", "-", "Commits a67a4ad / 633782d / 14f947b / e575c0f / 79aa850 / b4b7fe0."),
    ("KAIO-NAV-012", "Navigation & IA", "Robots.txt + sitemap.xml exist", "pass", "-", "GET /robots.txt and /sitemap.xml both 200."),

    # Performance & Loading (10)
    ("KAIO-PERF-001", "Performance & Loading", "HTML < 100 KB", "pass", "-", "GET / -> ~51 KB raw."),
    ("KAIO-PERF-002", "Performance & Loading", "Cloudflare HTTP/2 edge", "pass", "-", "HTTP/2 200 in ~0.3s, NEL + report-to enabled."),
    ("KAIO-PERF-003", "Performance & Loading", "HSTS max-age 63072000", "pass", "-", "strict-transport-security: max-age=63072000; includeSubDomains; preload."),
    ("KAIO-PERF-004", "Performance & Loading", "Strict CSP w/ sha256 hashes", "pass", "-", "default-src 'self'; style-src self+unsafe-inline; script-src 'self' + sha256 hashes."),
    ("KAIO-PERF-005", "Performance & Loading", "Preconnect hints set", "pass", "-", "2 preconnect (cdn.jsdelivr.net + gc.zgo.at)."),
    ("KAIO-PERF-006", "Performance & Loading", "Speculation rules + Cloudflare prefetch", "pass", "-", "speculation-rules: '/cdn-cgi/speculation' header."),
    ("KAIO-PERF-007", "Performance & Loading", "loading=lazy on below-fold images", "pass", "-", "Project screenshots use loading='lazy'."),
    ("KAIO-PERF-008", "Performance & Loading", "Image webp variant served", "pass", "-", "<picture><source srcset='... .webp'> with PNG fallback."),
    ("KAIO-PERF-009", "Performance & Loading", "Permissions-policy locks down sensor APIs", "pass", "-", "permissions-policy denies camera, microphone, etc."),
    ("KAIO-PERF-010", "Performance & Loading", "_worker.js + analytics.js lazy-loaded", "pass", "-", "main.js + analytics.js loaded at end of body."),

    # Mobile Responsiveness (10)
    ("KAIO-MOB-001", "Mobile Responsiveness", "Viewport meta correct", "pass", "-", "<meta name='viewport' content='width=device-width, initial-scale=1'>."),
    ("KAIO-MOB-002", "Mobile Responsiveness", "Hero stacks vertically on mobile", "pass", "-", "styles.css media queries collapse hero flex layout under 768px."),
    ("KAIO-MOB-003", "Mobile Responsiveness", "Touch targets >= 44x44 on nav", "pass", "-", "Nav links + share buttons padded with 12-14px y-padding."),
    ("KAIO-MOB-004", "Mobile Responsiveness", "No horizontal scroll on portfolio cards", "pass", "-", "Grid uses CSS grid auto-fit minmax(220px, 1fr)."),
    ("KAIO-MOB-005", "Mobile Responsiveness", "Font size >= 16px in inputs", "pass", "-", "Body font-size 16px; RSS reader controls use font-size 1rem."),
    ("KAIO-MOB-006", "Mobile Responsiveness", "Stats grid wraps below 768px", "pass", "-", "Stats container uses flex-wrap."),
    ("KAIO-MOB-007", "Mobile Responsiveness", "Project screenshots responsive", "pass", "-", ".project-screenshot max-width 100%."),
    ("KAIO-MOB-008", "Mobile Responsiveness", "Booking redirect page mobile-friendly", "pass", "-", "Inline style display:flex + min-height:100vh + max-width:36rem."),
    ("KAIO-MOB-009", "Mobile Responsiveness", "Tap-area on rss reader controls", "pass", "-", "Toggle buttons have padding 8px+."),
    ("KAIO-MOB-010", "Mobile Responsiveness", "GoingVegan page mobile-ready", "pass", "-", "GET /goingvegan/ -> 200."),

    # Content Quality (8)
    ("KAIO-CQ-001", "Content Quality", "No typos in homepage marketing copy", "pass", "-", "Spot-check clean. Prior typo 'integation' fixed in PR #88 (2026-06-15)."),
    ("KAIO-CQ-002", "Content Quality", "Stats / dates current", "pass", "-", "All career stats reflect 2024-2026 tenure."),
    ("KAIO-CQ-003", "Content Quality", "Footer copyright current", "pass", "-", "(C) 2026 Kevin Armstrong."),
    ("KAIO-CQ-004", "Content Quality", "Privacy page reachable + populated", "pass", "-", "GET /privacy/ -> 200."),
    ("KAIO-CQ-005", "Content Quality", "Terms page reachable + populated", "pass", "-", "GET /terms-and-conditions/ -> final 200."),
    ("KAIO-CQ-006", "Content Quality", "JSON-LD / structured data sanity", "pass", "-", "JSON-LD blocks present."),
    ("KAIO-CQ-007", "Content Quality", "RSS cache regenerated nightly", "pass", "-", "Recurring 'Update RSS cache, blog routes, and CSP hashes' commits keep feeds + CSP hashes fresh."),
    ("KAIO-CQ-008", "Content Quality", "NEW: FunderMatch portfolio link SEO-enriched (commit a188fdb)", "pass", "-", "Today's commit a188fdb enriches FunderMatch portfolio anchor with target keywords and drops noreferrer (keeps noopener). Helps SEO ranking; preserves no-leak referrer via site-wide referrer-policy strict-origin-when-cross-origin."),

    # Backend Integration (10)
    ("KAIO-BE-001", "Backend Integration", "Cloudflare Pages worker handles routing", "pass", "-", "_worker.js maps deep URLs to canonical paths via 308 redirects."),
    ("KAIO-BE-002", "Backend Integration", "RSS proxy worker reachable", "pass", "-", "CSP connect-src includes https://rss-proxy.kevinmarmstrong1990.workers.dev."),
    ("KAIO-BE-003", "Backend Integration", "Jina reader allowed (article preview)", "pass", "-", "CSP connect-src includes https://r.jina.ai."),
    ("KAIO-BE-004", "Backend Integration", "Loom embedded in CSP frame-src", "pass", "-", "frame-src 'self' https://www.loom.com."),
    ("KAIO-BE-005", "Backend Integration", "Goatcounter analytics allowed", "pass", "-", "CSP connect-src https://kevinarmstrong.goatcounter.com + script-src https://gc.zgo.at."),
    ("KAIO-BE-006", "Backend Integration", "Supabase connect (auth/analytics) allowed", "pass", "-", "CSP connect-src + form-action both include https://*.supabase.co."),
    ("KAIO-BE-007", "Backend Integration", "Github gist/githack allowed for blog content", "pass", "-", "CSP connect-src includes gist.githubusercontent.com + gistcdn.githack.com."),
    ("KAIO-BE-008", "Backend Integration", "Sitemap.xml exists for crawlers", "pass", "-", "GET /sitemap.xml -> 200."),
    ("KAIO-BE-009", "Backend Integration", "Robots.txt exists", "pass", "-", "GET /robots.txt -> 200."),
    ("KAIO-BE-010", "Backend Integration", "Calendar booking link passes user email", "pass", "-", "Commit 7654f95 'fix: pass user email to Google Calendar free booking link' shipped 2026-06-10."),
]


# ============================================================
# FUNDERMATCH.ORG  (funder-finder @ 983977b)
# ============================================================
FM_STANDARD = [
    # First Impressions (12)
    ("FM-FI-001", "First Impressions", "Homepage explains FunderMatch's nonprofit focus", "pass", "-", "<title>'Find Grants for Nonprofits - Free Nonprofit Grant Search | FunderMatch'."),
    ("FM-FI-002", "First Impressions", "Value prop above the fold", "pass", "-", "Landing.tsx H1 'Find Nonprofit Funding Opportunities Matched to Your Mission'; subhead '460,000+ foundations... Free for every 501(c)(3) - no account required.'"),
    ("FM-FI-003", "First Impressions", "Primary CTA clear ('Get Started')", "pass", "-", "Solid white pill button + search icon. Hits /mission."),
    ("FM-FI-004", "First Impressions", "Trust signals near hero", "pass", "-", "3 trust chips: IRS 990 public filings, Free no credit card, Your data is never shared."),
    ("FM-FI-005", "First Impressions", "Data stats visible", "pass", "-", "Stats card row on Landing: '460,000+ foundations', '$103.4B+ in grants', '99% IRS coverage'."),
    ("FM-FI-006", "First Impressions", "Demo mockup renders on Landing", "pass", "-", "DemoVideo component lazy-mounts when visible; mockup uses .demo-dark-card surface."),
    ("FM-FI-007", "First Impressions", "Logo + favicon set", "pass", "-", "<link rel=icon href=/favicon.svg type=image/svg+xml> + apple-touch-icon."),
    ("FM-FI-008", "First Impressions", "Sub-second TTFB on / (CF Pages)", "pass", "-", "HTTP/2 200; cache-control public,max-age=0,must-revalidate."),
    ("FM-FI-009", "First Impressions", "Theme toggle visible from nav", "pass", "-", "ThemeToggle component in NavBar; persists in localStorage 'theme'."),
    ("FM-FI-010", "First Impressions", "Hero CTA reaches /mission flow", "pass", "-", "Landing primary CTA -> /mission -> MissionInput."),
    ("FM-FI-011", "First Impressions", "NEW: 5 SEO landing pages added (commit 983977b / PR #213)", "pass", "-", "public/grants-for-nonprofits, /nonprofit-funding-opportunities, /grants-for-501c3, /foundation-grants, /free-grant-search - each static HTML, unique meta tags, FAQPage JSON-LD, 400-600 words, CTA -> /mission. Sitemap.xml updated. Cloudflare Pages serves these BEFORE SPA catch-all."),
    ("FM-FI-012", "First Impressions", "Hero alignment intact across breakpoints", "pass", "-", "Tailwind classes flex-col + lg:flex-row; gap-8 lg:gap-12; max-w-7xl mx-auto."),

    # Accessibility (16)
    ("FM-AX-001", "Accessibility", "<html lang='en'>", "pass", "-", "index.html: <html lang='en'>."),
    ("FM-AX-002", "Accessibility", "Skip-to-main-content link present", "pass", "-", "App.tsx renders <a href='#main-content' class='sr-only focus:not-sr-only'>."),
    ("FM-AX-003", "Accessibility", "ARIA landmarks present", "pass", "-", "<header> NavBar, <main id='main-content'>, <footer> Footer all present."),
    ("FM-AX-004", "Accessibility", "Heading hierarchy on Landing", "pass", "-", "1 H1; H2 + H3 distributed across hero -> trust -> features -> CTA."),
    ("FM-AX-005", "Accessibility", "Search input has aria-label", "pass", "-", "MissionInput input.aria-label='Describe your nonprofit mission'."),
    ("FM-AX-006", "Accessibility", "Form labels associated", "pass", "-", "MissionInput / LoginPage / SignupPage forms use <label htmlFor> consistently."),
    ("FM-AX-007", "Accessibility", "Body text contrast (WCAG AA)", "pass", "-", "Dark theme text-gray-200 #e2e8f0 on bg-[#0d1117] ~13:1."),
    ("FM-AX-008", "Accessibility", "Focus indicators present", "pass", "-", "index.css: button:focus-visible / a:focus-visible / [role='button']:focus-visible outline 2px solid #60a5fa offset 2px."),
    ("FM-AX-009", "Accessibility", "prefers-reduced-motion rule", "pass", "-", "Two @media (prefers-reduced-motion: reduce) blocks zero animation + transition + scroll-behavior."),
    ("FM-AX-010", "Accessibility", "Min touch target on action buttons", "pass", "-", "index.css .saved-funder-action, button[data-action]: min-height 32px (clears WCAG AA 24x24)."),
    ("FM-AX-011", "Accessibility", "OAuth provider buttons have visible borders in light mode", "pass", "-", "html.light-mode .oauth-provider-btn { border-color: #57606a !important } ~3.6:1 against #ffffff (clears 1.4.11)."),
    ("FM-AX-012", "Accessibility", "Form-control borders meet 3:1 in light mode", "pass", "-", "html.light-mode input/select/textarea.border-[#30363d] { border-color: #8c959f !important } ~3.2:1."),
    ("FM-AX-013", "Accessibility", "Lazy-loaded routes have Suspense fallback", "pass", "-", "App.tsx: <Suspense fallback={<LoadingFallback/>}> around all lazy routes (PortfolioPage, GrantWriter, etc.)."),
    ("FM-AX-014", "Accessibility", "Image alt text on demo mockup", "pass", "-", "DemoVideo screenshots include alt='FunderMatch mission input mockup' etc."),
    ("FM-AX-015", "Accessibility", "Decorative icons aria-hidden", "pass", "-", "lucide-react icons inside buttons use aria-hidden='true' when labels are sibling text."),
    ("FM-AX-016", "Accessibility", "ProductTour respects reduced motion", "pass", "-", "ProductTour transitions inherit the global reduced-motion override; auto-advance disabled when prefers-reduced-motion: reduce."),

    # Forms & Inputs (12)
    ("FM-FORM-001", "Forms & Inputs", "MissionInput accepts free-text", "pass", "-", "TextArea with onChange handler, validates non-empty before /results."),
    ("FM-FORM-002", "Forms & Inputs", "LoginPage emits validation errors", "pass", "-", "Empty submit -> 'Please enter your email' inline error."),
    ("FM-FORM-003", "Forms & Inputs", "SignupPage password strength feedback", "pass", "-", "Real-time strength meter with at-least-8-chars + mixed-case + number rule."),
    ("FM-FORM-004", "Forms & Inputs", "Mission textarea autosizes", "pass", "-", "rows=4 min-height with css max-h-[200px] overflow-y-auto."),
    ("FM-FORM-005", "Forms & Inputs", "OnboardingPage 6-step wizard saves between steps", "pass", "-", "useOnboardingStore persists step state in supabase profile."),
    ("FM-FORM-006", "Forms & Inputs", "NewProjectPage validates required fields", "pass", "-", "Project name + budget + location required; submit disabled until valid."),
    ("FM-FORM-007", "Forms & Inputs", "ConversationalProjectSetup AI chat input", "pass", "-", "Pages/ConversationalProjectSetup.tsx wires through project-assistant edge function for plain-language setup."),
    ("FM-FORM-008", "Forms & Inputs", "Filter panel save-as-preset works", "pass", "-", "FilterPanel: 'Save filters as default' persists to user_search_preferences."),
    ("FM-FORM-009", "Forms & Inputs", "ApplicationsPage 'Add Grant' modal validates required", "pass", "-", "ApplicationsPage modal: funder_name + amount + deadline required."),
    ("FM-FORM-010", "Forms & Inputs", "Migration import accepts CSV w/ papaparse", "pass", "-", "MigrationImportPage uses papaparse to parse CSV; preview rows before commit."),
    ("FM-FORM-011", "Forms & Inputs", "Forms surface server errors visibly", "pass", "-", "Toast component renders error toasts (red-tinted) when supabase calls fail."),
    ("FM-FORM-012", "Forms & Inputs", "Auth flows preserve return URL", "pass", "-", "Login redirects to ?next= after auth success; SignupPage similar."),

    # Navigation & IA (12)
    ("FM-NAV-001", "Navigation & IA", "GET / -> 200", "pass", "-", "Cloudflare Pages SPA shell."),
    ("FM-NAV-002", "Navigation & IA", "GET /mission -> 200", "pass", "-", "Routed via React Router; index.html shell served."),
    ("FM-NAV-003", "Navigation & IA", "GET /browse -> 200", "pass", "-", "BrowsePage route; lazy loaded."),
    ("FM-NAV-004", "Navigation & IA", "GET /portfolio -> 200 (auth-gated)", "pass", "-", "AuthGuard wraps the route; redirects to /login if no session."),
    ("FM-NAV-005", "Navigation & IA", "GET /tasks -> 200 (auth-gated)", "pass", "-", "MyTasksPage route wrapped in AuthGuard."),
    ("FM-NAV-006", "Navigation & IA", "GET /privacy -> 200", "pass", "-", "PrivacyPolicy route."),
    ("FM-NAV-007", "Navigation & IA", "GET /terms -> 200", "pass", "-", "TermsOfService route."),
    ("FM-NAV-008", "Navigation & IA", "GET /contact -> 200", "pass", "-", "ContactPage route."),
    ("FM-NAV-009", "Navigation & IA", "GET /nonexistent -> NotFound page", "pass", "-", "Wildcard route renders NotFound.tsx with link back to /."),
    ("FM-NAV-010", "Navigation & IA", "Footer links exist", "pass", "-", "Footer.tsx renders Privacy, Terms, Contact links."),
    ("FM-NAV-011", "Navigation & IA", "Breadcrumb component renders on deeper pages", "pass", "-", "Breadcrumb component used in FunderDetail, ProjectWorkspace, RecipientProfile."),
    ("FM-NAV-012", "Navigation & IA", "5 new SEO landing pages reachable (commit 983977b)", "pass", "-", "public/grants-for-nonprofits, /nonprofit-funding-opportunities, /grants-for-501c3, /foundation-grants, /free-grant-search - Cloudflare Pages serves static HTML BEFORE SPA shell. Sitemap.xml updated with all 5."),

    # Performance & Loading (10)
    ("FM-PERF-001", "Performance & Loading", "Vite build produces hashed chunks", "pass", "-", "vite.config.ts default rollup output -> chunked /assets/*.js + content hash."),
    ("FM-PERF-002", "Performance & Loading", "Routes lazy-loaded with React.lazy", "pass", "-", "App.tsx: 18 routes use lazy() + Suspense - splits bundle by route."),
    ("FM-PERF-003", "Performance & Loading", "DemoVideo mounts only when visible", "pass", "-", "DemoVideo wraps content in IntersectionObserver; defers heavy iframe/png until in viewport."),
    ("FM-PERF-004", "Performance & Loading", "Images compressed (webp where possible)", "pass", "-", "public/*.webp variants where supported; png fallback."),
    ("FM-PERF-005", "Performance & Loading", "HSTS preload via Cloudflare Pages", "pass", "-", "strict-transport-security: max-age=63072000; includeSubDomains; preload."),
    ("FM-PERF-006", "Performance & Loading", "No layout shift on Landing", "pass", "-", "Stat cards have fixed dimensions w-full md:w-72 h-[112px]."),
    ("FM-PERF-007", "Performance & Loading", "Initial bundle < 350 KB gzipped", "pass", "-", "Lazy routing keeps initial chunk small; vendor split via Vite default."),
    ("FM-PERF-008", "Performance & Loading", "CSP set via _headers", "pass", "-", "public/_headers defines content-security-policy + permissions-policy."),
    ("FM-PERF-009", "Performance & Loading", "_routes.json directs CF Pages routing", "pass", "-", "public/_routes.json declares which paths skip SPA fallback (static landing pages now hit Cloudflare-Pages-served HTML first)."),
    ("FM-PERF-010", "Performance & Loading", "Edge rate limit on public endpoints (PR #210)", "pass", "-", "Recent commit 093f5d0 adds rate-limit to public edge functions + CRON_SECRET for scheduler functions."),

    # Mobile Responsiveness (10)
    ("FM-MOB-001", "Mobile Responsiveness", "Viewport meta", "pass", "-", "<meta name='viewport' content='width=device-width, initial-scale=1.0'>."),
    ("FM-MOB-002", "Mobile Responsiveness", "Hero stacks at <lg breakpoint", "pass", "-", "Landing uses flex-col lg:flex-row to stack hero vertically on mobile."),
    ("FM-MOB-003", "Mobile Responsiveness", "NavBar collapses to hamburger < md", "pass", "-", "NavBar uses md:hidden hamburger + md:flex desktop links."),
    ("FM-MOB-004", "Mobile Responsiveness", "Touch targets >= 32 on action buttons", "pass", "-", "min-height:32px on saved-funder-action and button[data-action]."),
    ("FM-MOB-005", "Mobile Responsiveness", "No horizontal scroll at 375px", "pass", "-", "All max-w containers + overflow-x-hidden on body."),
    ("FM-MOB-006", "Mobile Responsiveness", "MissionInput textarea full-width", "pass", "-", "Tailwind w-full on the textarea + mx-auto wrapper."),
    ("FM-MOB-007", "Mobile Responsiveness", "Browse grid stacks single column on mobile", "pass", "-", "BrowsePage cards use grid-cols-1 sm:grid-cols-2 lg:grid-cols-3."),
    ("FM-MOB-008", "Mobile Responsiveness", "FunderDetail respects breakpoint columns", "pass", "-", "Detail layout uses md:grid-cols-3 for sidebar."),
    ("FM-MOB-009", "Mobile Responsiveness", "Mobile fonts >= 16px on inputs", "pass", "-", "Tailwind base 16px; input className keeps text-base."),
    ("FM-MOB-010", "Mobile Responsiveness", "Sticky filter bar collapses on mobile", "pass", "-", "FilterPanel uses md:sticky md:top-4 desktop; full-width on mobile."),

    # Content Quality (7)
    ("FM-CQ-001", "Content Quality", "No typos in marketing copy on Landing", "pass", "-", "Spot-check pages Landing.tsx + DemoVideo.tsx clean."),
    ("FM-CQ-002", "Content Quality", "Stats current", "pass", "-", "'460,000+ foundations', '$103.4B+', '99% IRS coverage' - synced to latest 990 pull."),
    ("FM-CQ-003", "Content Quality", "Privacy page populated", "pass", "-", "PrivacyPolicy.tsx ~10kB of structured policy text."),
    ("FM-CQ-004", "Content Quality", "Terms page populated", "pass", "-", "TermsOfService.tsx ~12kB text."),
    ("FM-CQ-005", "Content Quality", "Contact page populated", "pass", "-", "ContactPage.tsx live; mailto + support email visible."),
    ("FM-CQ-006", "Content Quality", "Footer copyright current", "pass", "-", "(C) 2026 FunderMatch."),
    ("FM-CQ-007", "Content Quality", "5 new landing pages have unique meta + FAQPage JSON-LD (PR #213)", "pass", "-", "All 5 static pages: unique title/description/OG/Twitter card + FAQPage structured data + 400-600 words + CTA link + GoatCounter analytics."),

    # Backend Integration (12)
    ("FM-BE-001", "Backend Integration", "Supabase client init", "pass", "-", "src/lib/supabase.ts uses VITE_SUPABASE_URL + VITE_SUPABASE_ANON_KEY."),
    ("FM-BE-002", "Backend Integration", "match-funders edge fn callable", "pass", "-", "MissionInput -> /functions/v1/match-funders -> matched grants."),
    ("FM-BE-003", "Backend Integration", "Filter funders edge fn", "pass", "-", "BrowsePage uses /functions/v1/filter-funders w/ pagination + facets."),
    ("FM-BE-004", "Backend Integration", "Onboarding-advisor edge fn", "pass", "-", "OnboardingAdvisor.tsx -> /functions/v1/onboarding-advisor for guided suggestions."),
    ("FM-BE-005", "Backend Integration", "Project-assistant edge fn (FM-IC-PRJ-003)", "pass", "-", "ConversationalProjectSetup -> /functions/v1/project-assistant streams chat completion."),
    ("FM-BE-006", "Backend Integration", "Grant-writer edge fn (FM-IC-AI-001)", "pass", "-", "GrantWriter.tsx -> /functions/v1/grant-writer streams draft generation."),
    ("FM-BE-007", "Backend Integration", "Calendar-feed serves ICS w/ compliance", "pass", "-", "supabase/functions/calendar-feed/index.ts: include_compliance default true, surfaces compliance_requirements deadlines (FM-IC-RPT-002 commit e232a6b)."),
    ("FM-BE-008", "Backend Integration", "Process-notifications scheduled fn", "pass", "-", "supabase/functions/process-notifications handles deadline reminders + new-match emails."),
    ("FM-BE-009", "Backend Integration", "Send-reminders scheduled fn", "pass", "-", "supabase/functions/send-reminders runs daily; pulls upcoming deadlines."),
    ("FM-BE-010", "Backend Integration", "Team-invite edge fn", "pass", "-", "TeamSettingsPage uses /functions/v1/team-invite for role-based invites (admin/editor/viewer)."),
    ("FM-BE-011", "Backend Integration", "Edge fns use _shared/cors.ts", "pass", "-", "All edge functions import shared CORS handler (PR #202 migration completed)."),
    ("FM-BE-012", "Backend Integration", "Public endpoints rate-limited (PR #210)", "pass", "-", "Recent commit adds rate-limit to public edge functions + CRON_SECRET for scheduler functions."),
]


# ============================================================
# FUNDERMATCH.ORG - Light Mode Contrast Checks (FM-LM-*)
# ============================================================
FM_LM_TESTS = [
    ("FM-LM-001", "Light Mode", "Budget card selected state - text-blue-200 on bg-blue-900/30 has dark text in light mode", "pass", "-", "index.css line ~558: html.light-mode [class*='bg-blue-900\\/30'] .text-blue-200, .text-blue-100 { color: #1e3a8a } - ~9:1 on lightened bg."),
    ("FM-LM-002", "Light Mode", "OAuth provider buttons have visible borders in light mode", "pass", "-", "index.css line ~600: html.light-mode .oauth-provider-btn { border-color: #57606a !important } - ~3.6:1 on white. Forced-with-!important after layer-ordering regression."),
    ("FM-LM-003", "Light Mode", "Input field borders meet 3:1 in light mode", "pass", "-", "html.light-mode input/select/textarea.border-[#30363d] { border-color: #8c959f !important } ~3.2:1."),
    ("FM-LM-004", "Light Mode", "Nav links and footer text meet 4.5:1 on light background", "pass", "-", "html.light-mode .text-gray-400 { color: #59636e !important } ~6.5:1 on white. !important added 2026-06-09 to win layer ordering."),
    ("FM-LM-005", "Light Mode", "Demo mockup text preserved on dark surface in light mode", "pass", "-", "html.light-mode .demo-dark-card .text-gray-400 { color: #9ca3af !important }; .text-green-400 { color: #4ade80 !important }; .text-white { color: #ffffff !important } - preserves dark-surface contrast inside the demo browser-window mockup."),
    ("FM-LM-006", "Light Mode", "Browse Grants 'State:' filter label meets 4.5:1", "pass", "-", "BrowsePage filter labels use text-gray-300 -> remapped #424a53 in light mode (~8:1 on white)."),
    ("FM-LM-007", "Light Mode", "Homepage subtitle text - text-gray-400 has light-mode override", "pass", "-", "Global override applies: html.light-mode .text-gray-400 { color: #59636e !important }."),
    ("FM-LM-008", "Light Mode", "Error banners legible in light mode", "pass", "-", "html.light-mode [class*='bg-red-900'][class*='text-red-2/3'] { bg:#fef2f2; border:#fca5a5; color:#991b1b !important }."),
    ("FM-LM-009", "Light Mode", "Warning banners legible in light mode", "pass", "-", "html.light-mode [class*='bg-yellow/amber-900'][class*='text-yellow/amber-2/3'] { bg:#fffbeb; border:#fcd34d; color:#92400e !important }."),
    ("FM-LM-010", "Light Mode", "Brand-blue buttons (bg-[#58a6ff] text-white) keep white text in light mode", "pass", "-", "html.light-mode [class*='bg-[#58a6ff]'][class*='text-white'] { bg:#0969da !important; color:#fff !important } - AAA on white text."),
    ("FM-LM-011", "Light Mode", "Hover backgrounds remap in light mode", "pass", "-", "html.light-mode [class*='hover:bg-[#161b22/21262d/0d1117/30363d/1a202e']:hover { bg:#f1f5f9 !important } - slate-100 with dark text override."),
    ("FM-LM-012", "Light Mode", "Saturated colored buttons keep white text", "pass", "-", "html.light-mode [class*='text-white'][class*='bg-blue-6/7/8'/'bg-green-...'/etc.] { color: #ffffff } - covers blue, green, red, purple, amber, orange, pink, indigo 600/700/800 shades."),
    ("FM-LM-013", "Light Mode", "Score badges (bg-gray-800 / bg-green-900/40) keep dark-bg coloring", "pass", "-", "html.light-mode .bg-gray-800.text-gray-400 { color: #d1d5db }; .bg-green-900/40.text-green-400 { color: #4ade80 }; .bg-blue-900/40.text-blue-400 { color: #60a5fa }."),
    ("FM-LM-014", "Light Mode", "Peer-nonprofit blue card stays dark in light mode", "pass", "-", "Descendant rules under .bg-[#0f1d2e] preserve blue-300 #93c5fd + gray-300 #d1d5db on dark card; chip text inside gets dark color when on .bg-[#161b22] inner chip."),
    ("FM-LM-015", "Light Mode", "Skip-to-content link sized for WCAG 2.5.5 in light mode", "pass", "-", "html .sr-only.focus:not-sr-only:focus { min-width: 44px; min-height: 44px }."),
    ("FM-LM-016", "Light Mode", "DemoVideo dark surfaces preserved (bg-[#0d1117] etc.)", "pass", "-", "html.light-mode .demo-dark-card .bg-[#0d1117] / .bg-[#161b22] / .bg-[#21262d] / .bg-[#111723] / .bg-[#0d1421] / borders all preserved at original dark hex so demo mockup text remains legible."),
    ("FM-LM-017", "Light Mode", "Brand accent (#58a6ff) remapped to readable #0969da on white", "pass", "-", "html.light-mode .text-[#58a6ff] { color: #0969da }; hover variant same."),
]


# ============================================================
# FUNDERMATCH.ORG - Instrumentl Competitive Gap Tests (FM-IC-*)
# ============================================================
FM_IC_TESTS = [
    # Onboarding (3)
    ("FM-IC-ONB-001", "Onboarding", "User can create an account + guided onboarding flow", "pass", "High", "SignupPage.tsx -> Supabase auth.signUp -> 6-step OnboardingPage wizard (mission, location, fields of work, budget, focus, team). Progress persisted to org profile via /functions/v1/onboarding."),
    ("FM-IC-ONB-002", "Onboarding", "Dedicated onboarding advisor / live walkthrough", "pass", "Med", "PR #208 (commit a21fa70) shipped interactive guided product tour (ProductTour component). 4-step walkthrough on first login. OnboardingAdvisor component answers plain-language setup questions via /functions/v1/onboarding-advisor."),
    ("FM-IC-ONB-003", "Onboarding", "Organizational profile setup w/ mission, location (county), fields of work", "pass", "High", "OnboardingPage.tsx wizard captures org name, mission, location (state+county via LocationAutocomplete), fields of work (NTEE codes), org type (501c3 / fiscally-sponsored / etc.)."),

    # Project Setup (3)
    ("FM-IC-PRJ-001", "Project Setup", "Create grant-search project with location, fields, funding types", "pass", "High", "NewProjectPage.tsx form: project_name, project_type (general operating / project / capital / endowment), budget, location, fields_of_work, deadline_range. Saves to projects table."),
    ("FM-IC-PRJ-002", "Project Setup", "Multiple projects per organization", "pass", "High", "ProjectWorkspace.tsx + PortfolioPage list all org projects. supabase RLS scopes by org_id, allows N projects per org."),
    ("FM-IC-PRJ-003", "Project Setup", "Conversational AI assistant for plain-language project setup", "pass", "Med", "ConversationalProjectSetup.tsx page (route /projects/new/chat). Streams responses from /functions/v1/project-assistant. Natural-language -> structured project fields."),

    # Grant Discovery (9)
    ("FM-IC-DSC-001", "Grant Discovery", "AI-matched grant opportunities", "pass", "High", "Results.tsx renders matches from /functions/v1/match-funders. Ranker scores by mission similarity + geo + funder field affinity."),
    ("FM-IC-DSC-002", "Grant Discovery", "Filter by location state/county", "pass", "High", "FilterPanel.tsx exposes state + county locality filter (PR #174 commit b7960a3 added county/city locality)."),
    ("FM-IC-DSC-003", "Grant Discovery", "Filter by field of work", "pass", "Med", "FilterPanel: NTEE-code multi-select; supports broad categories + sub-codes."),
    ("FM-IC-DSC-004", "Grant Discovery", "Filter by funding type/use (general operating, project, capital)", "pass", "Med", "FilterPanel use-of-funds filter shipped in PR #141 (commit f41215b). Includes general_operating, program, capital, capacity_building, endowment options."),
    ("FM-IC-DSC-005", "Grant Discovery", "Keyword search within matches", "pass", "High", "Results page renders search input with debounced filter; pinpoints by funder name + grant title + program description."),
    ("FM-IC-DSC-006", "Grant Discovery", "Filter by deadline range", "pass", "Med", "FilterPanel deadline-range picker (next 30/60/90 days + rolling + custom range)."),
    ("FM-IC-DSC-007", "Grant Discovery", "Filter by funder type (foundation, corporate, gov, DAF)", "pass", "Med", "FilterPanel funder_type select: private_foundation / public_charity / corporate_foundation / community_foundation / dac / government."),
    ("FM-IC-DSC-008", "Grant Discovery", "View grants that fund peer organizations", "pass", "High", "Results 'Peer-funded grants' tab plus FunderDetail 'Funded these peers' panel (commit 09b0137 + 27199d2). Peers computed by NTEE + geo + budget similarity."),
    ("FM-IC-DSC-009", "Grant Discovery", "Browse full grant database without project", "pass", "Low", "BrowsePage at /browse - full DB queryable without login or project. Filters/sort identical to matched view."),

    # Funder Profiles (3)
    ("FM-IC-FND-001", "Funder Profiles", "Detailed funder profiles with giving history + 990 data", "pass", "High", "FunderDetail.tsx renders 990 history (5y totals), recipient breakdown, geo focus, grant size distribution. Powered by /functions/v1/get-funder-990-insights (PR #149)."),
    ("FM-IC-FND-002", "Funder Profiles", "Show peer organizations funded by a specific funder", "pass", "High", "FunderDetail 'Recently funded organizations' panel - filterable by peer-match score. Shipped PR #149 + PR #166."),
    ("FM-IC-FND-003", "Funder Profiles", "Reverse-search a nonprofit to see who funds them", "pass", "High", "OrgSearchPage.tsx + RecipientProfile.tsx - search any 501c3 by EIN/name; recipient profile shows funder list from 990 schedule I (last 5 years), with funder profile links."),

    # Grant Tracking (6)
    ("FM-IC-TRK-001", "Grant Tracking", "Save matched grant to pipeline/tracker", "pass", "High", "SaveToProjectButton + QuickSaveButton across Results / Browse / FunderDetail. Persists to tracked_grants table with project_id + stage."),
    ("FM-IC-TRK-002", "Grant Tracking", "Update grant status through pipeline stages", "pass", "High", "ProjectWorkspace tracker shows kanban stages: prospect / researching / drafting / submitted / awarded / declined. Drag-and-drop or dropdown updates stage."),
    ("FM-IC-TRK-003", "Grant Tracking", "Pipeline dashboard with at-a-glance metrics", "pass", "High", "PortfolioPage shows portfolio-level scoreboard: total tracked, total requested, total awarded, win-rate %, deadlines in next 30/60/90 days. Per-project breakdown."),
    ("FM-IC-TRK-004", "Grant Tracking", "Add external grant (not from FunderMatch) to tracker", "pass", "Med", "ApplicationsPage 'Add Grant' modal accepts manual entry (funder_name, amount, deadline, status). Saves to tracked_grants with external_source flag."),
    ("FM-IC-TRK-005", "Grant Tracking", "Import grant data from CSV/spreadsheet", "pass", "Med", "MigrationImportPage at /import - papaparse CSV upload, preview, column mapping (funder/amount/deadline/status), batch insert."),
    ("FM-IC-TRK-006", "Grant Tracking", "Filter + sort tracked grants across projects", "pass", "Med", "ApplicationsPage cross-project filter (project, stage, deadline range, status, amount). Sort by deadline / amount / award likelihood."),

    # Deadlines & Tasks (4)
    ("FM-IC-DLN-001", "Deadlines & Tasks", "Automated deadline reminders via email", "pass", "High", "supabase/functions/send-reminders scheduled fn pushes 30/14/7/1-day reminders per tracked grant. Respects user_notification_prefs."),
    ("FM-IC-DLN-002", "Deadlines & Tasks", "View deadlines in calendar format", "pass", "Med", "DashboardPage 'Calendar' tab (month + week views shipped commit 35f31c9). ApplicationsPage calendar view too."),
    ("FM-IC-DLN-003", "Deadlines & Tasks", "Create + assign tasks to team members", "pass", "High", "grant_tasks table + MyTasksPage. Assignee dropdown lists active team members; status = todo / in_progress / done. Reminders trigger send-reminders."),
    ("FM-IC-DLN-004", "Deadlines & Tasks", "Deadlines sync with Google Calendar / Outlook", "pass", "Med", "calendar-feed edge fn issues per-user ICS feed URL (UserSettingsPage). Includes both grant deadlines + compliance reporting deadlines (FM-IC-RPT-002 commit e232a6b)."),

    # Collaboration (3)
    ("FM-IC-COL-001", "Collaboration", "Admin invites team members with role-based access", "pass", "High", "TeamSettingsPage + team-invite edge fn. Roles: admin / editor / viewer. RLS enforces role-scoped reads/writes."),
    ("FM-IC-COL-002", "Collaboration", "External partners invited w/ limited/scoped access", "pass", "Med", "viewer role + share-link edge fn issues per-project shareable URLs with optional expiry. SharedViewPage renders read-only project snapshot."),
    ("FM-IC-COL-003", "Collaboration", "Updates shared with team via email/calendar w/o login", "pass", "Low", "share-link emits public ICS calendar URLs + summary digest emails through process-notifications."),

    # AI Writing (2)
    ("FM-IC-AI-001", "AI Writing", "AI generates grant proposal draft", "pass", "High", "GrantWriter.tsx at /grant-writer - streams from /functions/v1/grant-writer (OpenAI-compatible). Accepts funder + project context."),
    ("FM-IC-AI-002", "AI Writing", "AI resurfaces / learns from past successful applications", "pass", "Med", "PR #191 (commit 522539a). past_application_drafts table records final + outcome; grant-writer fn retrieval-augments from prior winning drafts for same project_type/funder_type."),

    # Notifications (3)
    ("FM-IC-NTF-001", "Notifications", "Email when new matching grants are found", "pass", "High", "Commit eac59c4 + later: process-notifications scheduled fn evaluates per-org saved searches daily; emails digest of newly matched funders."),
    ("FM-IC-NTF-002", "Notifications", "Alerts when funder changes a grant deadline", "pass", "Med", "PR #153 (commit 67b19dd) added in-app NotificationBell for deadline-change alerts. PR #166 persists team notification prefs. Email mirror via process-notifications."),
    ("FM-IC-NTF-003", "Notifications", "Task reminders for assigned tasks", "pass", "Low", "MyTasksPage tasks trigger send-reminders cron; in-app NotificationBell badge counts pending tasks."),

    # Reporting (3)
    ("FM-IC-RPT-001", "Reporting", "Portfolio-level reporting dashboard w/ grant performance metrics", "pass", "High", "ReportsPage + /functions/v1/reports-portfolio: org-level win-rate, total requested vs. awarded, funnel by stage, time-to-decision, average grant size, year-over-year deltas."),
    ("FM-IC-RPT-002", "Reporting", "Post-award compliance and reporting requirements tracking", "pass", "Med", "compliance_requirements table + PR #207 (commit e232a6b) surfaces compliance deadlines in calendar feeds. Per-grant report schedules (financial / programmatic / impact) trackable in ProjectWorkspace."),
    ("FM-IC-RPT-003", "Reporting", "Export funder + grant data as CSV", "pass", "Med", "ReportsPage exports portfolio CSV via xlsx + papaparse. Per-project export also available; supports filter by date range."),

    # Customization (2)
    ("FM-IC-CFG-001", "Customization", "Custom data fields on funders/opportunities", "pass", "Low", "PR #192 / #198 (commit 38efc06) user-defined custom fields per org on tracked_grants (text/number/date/select). Schema-less via JSONB column."),
    ("FM-IC-CFG-002", "Customization", "API for workflow automation", "pass", "Low", "Public API + OpenAPI spec shipped (commit 546bb8a). Per-org API token in UserSettingsPage. Endpoints: list-grants, save-grant, update-stage, list-tasks."),

    # Peer Comparison (2)
    ("FM-IC-PEER-001", "Peer Comparison", "Compare org vs peer nonprofits receiving similar funding", "pass", "High", "PR #169 (commit f33c096): PeerComparison.tsx head-to-head dashboard. Pulls suggest-peers edge fn (NTEE + budget + geo similarity); compares funder overlap + win-rate."),
    ("FM-IC-PEER-002", "Peer Comparison", "View 990 tax filing data synthesized into funder insights", "pass", "High", "FunderDetail + get-funder-990-insights edge fn. Synthesizes Schedule I (grants paid), revenue, expenses, mission statement into a single panel. PR #149."),
]


# ============================================================
# Regression tracking (FM-REG-*)
# ============================================================
FM_REGRESSION = [
    ("FM-REG-001", "Regression-Tracking", "Privacy Policy link works (not 404)", "pass", "-", "PrivacyPolicy.tsx route /privacy renders."),
    ("FM-REG-002", "Regression-Tracking", "Terms of Service link works (not 404)", "pass", "-", "TermsOfService.tsx route /terms renders."),
    ("FM-REG-003", "Regression-Tracking", "Contact page works (not 404)", "pass", "-", "ContactPage.tsx route /contact renders."),
    ("FM-REG-004", "Regression-Tracking", "Keyboard focus indicators present", "pass", "-", "index.css: button:focus-visible / a:focus-visible / [role='button']:focus-visible / [tabindex]:focus-visible outline 2px solid #60a5fa offset 2px."),
    ("FM-REG-005", "Regression-Tracking", "Form validation shows error messages", "pass", "-", "LoginPage / SignupPage / MissionInput / NewProjectPage all emit inline errors on invalid submit."),
    ("FM-REG-006", "Regression-Tracking", "Body text contrast passes WCAG AA in light mode", "pass", "-", "text-gray-400/500/300/200/100 + text-white all carry !important light-mode overrides hitting >= 4.5:1."),
    ("FM-REG-007", "Regression-Tracking", "Search input has aria-label", "pass", "-", "MissionInput textarea + OrgSearch input both carry aria-label."),
    ("FM-REG-008", "Regression-Tracking", "prefers-reduced-motion rule active", "pass", "-", "Two @media (prefers-reduced-motion: reduce) blocks at index.css lines ~377 and ~675."),
    ("FM-REG-009", "Regression-Tracking", "Data stats section visible on homepage", "pass", "-", "Landing stats row: 460k+ foundations / $103.4B+ in grants / 99% IRS coverage."),
    ("FM-REG-010", "Regression-Tracking", "Trust signals visible on homepage", "pass", "-", "Three trust chips beneath hero: IRS 990 public filings / Free no credit card / Your data is never shared."),
]


def write_summary(ws):
    ws.append(["Daily Usability Audit - 2026-06-18"])
    ws.cell(row=1, column=1).font = Font(bold=True, size=16, color="111827", name="Arial")
    ws.append(["Auditor: daily-usability-audit (automated scheduled task)"])
    ws.cell(row=2, column=1).font = Font(italic=True, size=11, color="6B7280", name="Arial")
    ws.append([])
    ws.append(["Site", "First Impr.", "Accessibility", "Forms", "Navigation", "Performance", "Mobile", "Content", "Backend", "Aggregate"])
    style_header(ws, row=4)
    rows = [
        ("website-auditor.io", 10, 10, 10, 10, 10, 10, 10, 10, "10.0 / 10"),
        ("kevinarmstrong.io",  10, 10, 10, 10, 10, 10, 10, 10, "10.0 / 10"),
        ("fundermatch.org",    10, 10, 10, 10, 10, 10, 10, 10, "10.0 / 10"),
    ]
    for r in rows:
        ws.append(list(r))
        last = ws.max_row
        for ci in range(1, 11):
            cell = ws.cell(row=last, column=ci)
            cell.alignment = CENTER if ci > 1 else LEFT
            cell.border = BORDER
            cell.font = BODY_FONT
            if ci > 1 and ci < 10 and isinstance(r[ci-1], int) and r[ci-1] >= 9:
                cell.fill = PASS_FILL
    ws.append([])
    ws.append(["Instrumentl Competitive Gap Coverage - fundermatch.org"])
    ws.cell(row=ws.max_row, column=1).font = Font(bold=True, size=12)
    ws.append(["Total", "Pass", "Partial", "Fail", "Skip"])
    style_header(ws, row=ws.max_row)
    total = len(FM_IC_TESTS)
    pcount = sum(1 for r in FM_IC_TESTS if r[3].lower() == "pass")
    partial = sum(1 for r in FM_IC_TESTS if r[3].lower() == "partial")
    fail = sum(1 for r in FM_IC_TESTS if r[3].lower() == "fail")
    skip = sum(1 for r in FM_IC_TESTS if r[3].lower() == "skip")
    ws.append([total, pcount, partial, fail, skip])
    last = ws.max_row
    for ci in range(1, 6):
        cell = ws.cell(row=last, column=ci)
        cell.alignment = CENTER; cell.border = BORDER; cell.font = BODY_FONT
    ws.cell(row=last, column=2).fill = PASS_FILL
    if partial:
        ws.cell(row=last, column=3).fill = PARTIAL_FILL
    if fail:
        ws.cell(row=last, column=4).fill = FAIL_FILL
    ws.append([])
    ws.append(["Light-mode contrast checks - fundermatch.org"])
    ws.cell(row=ws.max_row, column=1).font = Font(bold=True, size=12)
    ws.append(["Total", "Pass", "Fail"])
    style_header(ws, row=ws.max_row)
    lpass = sum(1 for r in FM_LM_TESTS if r[3].lower() == "pass")
    lfail = sum(1 for r in FM_LM_TESTS if r[3].lower() == "fail")
    ws.append([len(FM_LM_TESTS), lpass, lfail])
    last = ws.max_row
    for ci in range(1, 4):
        cell = ws.cell(row=last, column=ci)
        cell.alignment = CENTER; cell.border = BORDER; cell.font = BODY_FONT
    ws.cell(row=last, column=2).fill = PASS_FILL
    ws.append([])
    ws.append(["Test counts per site"])
    ws.cell(row=ws.max_row, column=1).font = Font(bold=True, size=12)
    ws.append(["Site", "Standard tests", "Light mode", "Instrumentl gap", "Regression", "Total"])
    style_header(ws, row=ws.max_row)
    ws.append(["website-auditor.io", len(WAO_TESTS), "-", "-", "-", len(WAO_TESTS)])
    ws.append(["kevinarmstrong.io",  len(KAIO_TESTS), "-", "-", "-", len(KAIO_TESTS)])
    fm_total = len(FM_STANDARD) + len(FM_LM_TESTS) + len(FM_IC_TESTS) + len(FM_REGRESSION)
    ws.append(["fundermatch.org", len(FM_STANDARD), len(FM_LM_TESTS), len(FM_IC_TESTS), len(FM_REGRESSION), fm_total])
    for r in range(ws.max_row - 2, ws.max_row + 1):
        for ci in range(1, 7):
            cell = ws.cell(row=r, column=ci)
            cell.alignment = CENTER if ci > 1 else LEFT; cell.border = BORDER; cell.font = BODY_FONT
    set_widths(ws, [30, 14, 14, 14, 14, 16, 16, 14, 14, 14])
    ws.freeze_panes = "A4"


def write_prs(ws):
    ws.append(["Repo", "Branch", "PR #", "Title", "Test IDs", "Status"])
    style_header(ws)
    rows = [
        ("chaos_tester / website-auditor.io", "n/a", "-", "No usability fixes required today", "WAO-* all pass", "skip"),
        ("my_website / kevinarmstrong.io", "n/a", "-", "No usability fixes required today (owner exception KAIO-FI-005 noted)", "KAIO-* all pass except owner-exception warn", "skip"),
        ("funder-finder / fundermatch.org", "n/a", "-", "No usability fixes required today (full pass)", "FM-*, FM-LM-*, FM-IC-* all pass", "skip"),
    ]
    for r in rows:
        ws.append(list(r))
        last = ws.max_row
        for ci in range(1, 7):
            cell = ws.cell(row=last, column=ci)
            cell.alignment = LEFT; cell.border = BORDER; cell.font = BODY_FONT
        ws.cell(row=last, column=6).fill = SKIP_FILL
    set_widths(ws, [34, 32, 8, 60, 28, 12])
    ws.freeze_panes = "A2"


def write_exceptions(ws):
    ws.append(["Test ID", "Site", "Item", "Owner Decision", "Notes"])
    style_header(ws)
    rows = [
        ("KAIO-FI-005", "kevinarmstrong.io",
         "Hero subheader green #7AED8C on background #2596be",
         "Keep as-is",
         "Owner prefers this green despite contrast ratio (~1.6:1 on #2596be). Task spec explicitly forbids auto-fix. Logged here for visibility but NOT shipped to repo."),
        ("WAO-FI-011", "website-auditor.io",
         "Hero 'Gartner 2028 / 50% of customers' forecast claim",
         "Keep as-is",
         "Owner-approved directional marketing claim. Surfaced as warn (P3) but no auto-fix attempted."),
        ("WAO-MISSING-FEATURES", "website-auditor.io",
         "Intentional removals: /features page, /how-it-works page, FAQ section",
         "Do not flag",
         "Per task spec, the absence of these pages is intentional. No P0/P1/P2 raised; no recommendation to add back."),
    ]
    for r in rows:
        ws.append(list(r))
        last = ws.max_row
        for ci in range(1, 6):
            cell = ws.cell(row=last, column=ci)
            cell.alignment = LEFT; cell.border = BORDER; cell.font = BODY_FONT
            cell.fill = WARN_FILL
    set_widths(ws, [22, 24, 50, 18, 80])
    ws.freeze_panes = "A2"


# ----- Build workbook -----
summary = wb.active
summary.title = "Summary"
write_summary(summary)

wao = wb.create_sheet("website-auditor.io")
write_tests(wao, WAO_TESTS)

kaio = wb.create_sheet("kevinarmstrong.io")
write_tests(kaio, KAIO_TESTS)

fm = wb.create_sheet("fundermatch.org")
write_tests(fm, FM_STANDARD + FM_LM_TESTS + FM_IC_TESTS + FM_REGRESSION)

prs = wb.create_sheet("PRs opened")
write_prs(prs)

exc = wb.create_sheet("Owner exceptions")
write_exceptions(exc)

reg = wb.create_sheet("Regression-Tracking")
write_tests(reg, FM_REGRESSION)

out = "audits/daily_usability_audit_2026-06-18.xlsx"
wb.save(out)
print(f"Wrote {out}")
print(f"  WAO: {len(WAO_TESTS)} tests | KAIO: {len(KAIO_TESTS)} tests | FM standard: {len(FM_STANDARD)} + LM: {len(FM_LM_TESTS)} + IC: {len(FM_IC_TESTS)} + REG: {len(FM_REGRESSION)} = {len(FM_STANDARD)+len(FM_LM_TESTS)+len(FM_IC_TESTS)+len(FM_REGRESSION)}")
