"""Build the daily usability audit Excel report for 2026-06-11.

Sheets: Summary, website-auditor.io, kevinarmstrong.io, fundermatch.org,
PRs opened, Owner exceptions, Regression-Tracking.

Data collected via live HTTP probes against production (curl) and direct
inspection of the cloned repos on 2026-06-11:
  - SpikeyCoder/chaos_tester @ 447d5b7
  - SpikeyCoder/my_website   @ 8c72a6a
  - SpikeyCoder/funder-finder @ b7960a3

Generated by the daily-usability-audit scheduled task.
"""
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = Workbook()

HEADER_FILL = PatternFill(start_color="1F2937", end_color="1F2937", fill_type="solid")
HEADER_FONT = Font(bold=True, color="FFFFFF", size=11, name="Arial")
BODY_FONT = Font(name="Arial", size=10)
PASS_FILL = PatternFill(start_color="D1FAE5", end_color="D1FAE5", fill_type="solid")
FAIL_FILL = PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid")
WARN_FILL = PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid")
SKIP_FILL = PatternFill(start_color="E5E7EB", end_color="E5E7EB", fill_type="solid")
INFO_FILL = PatternFill(start_color="DBEAFE", end_color="DBEAFE", fill_type="solid")
PARTIAL_FILL = PatternFill(start_color="FED7AA", end_color="FED7AA", fill_type="solid")
THIN = Side(border_style="thin", color="D1D5DB")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
LEFT = Alignment(horizontal="left", vertical="top", wrap_text=True)


def style_header(ws, row=1):
    for c in ws[row]:
        c.fill = HEADER_FILL
        c.font = HEADER_FONT
        c.alignment = CENTER
        c.border = BORDER


def set_widths(ws, widths):
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w


def status_fill(s):
    s = (s or "").lower()
    return {
        "pass": PASS_FILL, "fail": FAIL_FILL, "warn": WARN_FILL,
        "warning": WARN_FILL, "skip": SKIP_FILL, "info": INFO_FILL,
        "partial": PARTIAL_FILL,
    }.get(s)


def write_tests(ws, tests):
    ws.append(["Test ID", "Category", "Test", "Status", "Severity", "Notes"])
    style_header(ws)
    for row in tests:
        ws.append(list(row))
        last_row = ws.max_row
        fill = status_fill(row[3])
        for ci in range(1, 7):
            cell = ws.cell(row=last_row, column=ci)
            cell.alignment = LEFT
            cell.border = BORDER
            cell.font = BODY_FONT
            if fill is not None:
                cell.fill = fill
    set_widths(ws, [14, 24, 60, 10, 10, 80])
    ws.freeze_panes = "A2"


# ============================================================
# WEBSITE-AUDITOR.IO  (chaos_tester @ 447d5b7)
# ============================================================
WAO_TESTS = [
    # First Impressions (12)
    ("WAO-FI-001", "First Impressions", "Homepage explains product (AI visibility + security + perf)", "pass", "-", "Live GET / returns 200; <title> 'Free Website Audit Tool — AI Visibility, Security & Performance Scanner | Website Auditor'."),
    ("WAO-FI-002", "First Impressions", "Value proposition immediately obvious", "pass", "-", "Hero 'Does ChatGPT recommend your business?' + URL input + 'Check my site' button above the fold."),
    ("WAO-FI-003", "First Impressions", "Primary CTA clear and compelling", "pass", "-", "'Check my site' submit button anchors the hero form; 'View Sample Report' secondary card surfaces /sample-report."),
    ("WAO-FI-004", "First Impressions", "GET / responds quickly through Cloudflare edge", "pass", "-", "HTTP/2 200 from Cloudflare edge; cf-cache-status DYNAMIC; small HTML payload (<50 KB)."),
    ("WAO-FI-005", "First Impressions", "Visual hierarchy (one H1, multiple H2/H3)", "pass", "-", "1 H1 ('Does ChatGPT recommend your business?'); H2s/H3s present for sections."),
    ("WAO-FI-006", "First Impressions", "Trust signals on homepage", "pass", "-", "Industry strip + testimonials (Jake Morrison, Sarah Patel) + sample-report preview retained."),
    ("WAO-FI-007", "First Impressions", "Navigation intuitive (3 top-level items)", "pass", "-", "Sample Report / API / Contact — short jargon-free."),
    ("WAO-FI-008", "First Impressions", "Hero works on mobile (viewport meta correct)", "pass", "-", "<meta viewport='width=device-width, initial-scale=1.0'>; hamburger #navToggle with aria-controls=mainNav."),
    ("WAO-FI-009", "First Impressions", "No broken images on home", "pass", "-", "Hero is inline SVG; logo.svg + favicon.svg both 200."),
    ("WAO-FI-010", "First Impressions", "Default body font readable", "pass", "-", "Inter @ 16px base; JetBrains Mono for code; preconnect to fonts.googleapis.com + fonts.gstatic.com."),
    ("WAO-FI-011", "First Impressions", "Hero Gartner claim — honesty / non-misleading", "warn", "P3", "Owner-info per prior audit. Hero still cites 'By 2028, 50% of customers will find your competitors through AI according to Gartner'. Owner exception — kept as directional marketing forecast."),
    ("WAO-FI-012", "First Impressions", "Above-the-fold CTA reachable without scroll", "pass", "-", "URL input + Check-my-site button inside .landing-hero render above the fold at 1280x800."),

    # Accessibility (16)
    ("WAO-AX-001", "Accessibility", "lang attribute set on <html>", "pass", "-", "templates/base.html: <html lang=\"en\">."),
    ("WAO-AX-002", "Accessibility", "Skip-to-content link present", "pass", "-", "<a href=\"#main-content\" class=\"skip-link\"> in base.html immediately after <body>."),
    ("WAO-AX-003", "Accessibility", "All images have alt or role='presentation'", "pass", "-", "logo.svg uses alt=\"\" + aria-hidden=\"true\" (decorative). SVG icons use focusable=\"false\". No <img> without alt found."),
    ("WAO-AX-004", "Accessibility", "Hamburger button has aria-expanded + aria-controls", "pass", "-", "id=\"navToggle\" with aria-label='Toggle navigation menu' aria-expanded='false' aria-controls='mainNav'."),
    ("WAO-AX-005", "Accessibility", "URL input has aria-label", "pass", "-", "<input type=\"url\" id=\"base_url\" aria-label=\"Website URL to audit\"> in dashboard.html."),
    ("WAO-AX-006", "Accessibility", "Submit button has aria-label", "pass", "-", "<button class=\"btn-audit\" aria-label=\"Check my site\">."),
    ("WAO-AX-007", "Accessibility", "Form submit announces busy state to AT", "pass", "-", "static/js/dashboard.js sets this.setAttribute('aria-busy','true') on submit; clears on response."),
    ("WAO-AX-008", "Accessibility", "color-scheme + theme-color meta set", "pass", "-", "<meta name=\"theme-color\" content=\"#0f172a\"> + <meta name=\"color-scheme\" content=\"dark light\">."),
    ("WAO-AX-009", "Accessibility", "Heading hierarchy on dashboard (no skipped levels)", "pass", "-", "H1 hero → H2 'What We Check' + 'Ready to Improve Your Website?' → H3 feature cards. No H1→H3 jumps."),
    ("WAO-AX-010", "Accessibility", "Form labels associated with all inputs", "pass", "-", "Required fields use either <label for=…> or aria-label on inputs in dashboard.html."),
    ("WAO-AX-011", "Accessibility", "Focus indicators present on interactive elements", "pass", "-", "base.css :focus-visible outline 2px solid var(--accent) preserved on .btn, .btn-audit, a, input."),
    ("WAO-AX-012", "Accessibility", "Touch targets >= 32x32 on mobile", "pass", "-", "WAO-MOB-001 from 2026-06-09 audit bumped #biz-name-wrong-btn to min-height:32px; padding:4px 8px."),
    ("WAO-AX-013", "Accessibility", "prefers-reduced-motion handling", "pass", "-", "base.css @media (prefers-reduced-motion: reduce) { animation:none !important; transition:none !important }."),
    ("WAO-AX-014", "Accessibility", "ARIA landmarks present", "pass", "-", "<header>, <main id=\"main-content\">, <footer> all present in base.html template."),
    ("WAO-AX-015", "Accessibility", "Body text contrast >= 4.5:1 (WCAG AA)", "pass", "-", "Inter 16px on dark surface; --text #e2e8f0 on #0f172a approx 13:1."),
    ("WAO-AX-016", "Accessibility", "API upsell button contrast >= 4.5:1", "pass", "-", "WCAG 1.4.3 fix (2026-05-11): indigo-600 #4f46e5 on white approx 6.0:1; hover #4338ca approx 7.5:1."),

    # Forms & Inputs (12)
    ("WAO-FORM-001", "Forms & Inputs", "URL input accepts valid URLs", "pass", "-", "type=\"url\" input with required attribute; browser-native URL validation."),
    ("WAO-FORM-002", "Forms & Inputs", "Submit blocked when URL empty", "pass", "-", "Button starts disabled; syncAuditBtnState() in dashboard.js enables only when URL valid + biz info present."),
    ("WAO-FORM-003", "Forms & Inputs", "Form provides feedback on submit", "pass", "-", "loading-indicator overlay appears below the search bar; showAuditSpinner() called."),
    ("WAO-FORM-004", "Forms & Inputs", "Rate limit 429 surfaces friendly message", "pass", "-", "fetch handler: status === 429 -> showRateLimitMessage(body.message || 'Too many requests')."),
    ("WAO-FORM-005", "Forms & Inputs", "CSRF token included on form", "pass", "-", "<input type=\"hidden\" name=\"csrf_token\" value=\"{{ csrf_token() }}\">."),
    ("WAO-FORM-006", "Forms & Inputs", "autocomplete=\"url\" on URL field", "pass", "-", "<input type=\"url\" autocomplete=\"url\"> set in dashboard.html."),
    ("WAO-FORM-007", "Forms & Inputs", "Placeholder text useful + readable", "pass", "-", "placeholder=\"Enter your website URL (e.g., https://yourbusiness.com)\" — example reads clearly."),
    ("WAO-FORM-008", "Forms & Inputs", "Form error recovery (submit-fix-resubmit)", "pass", "-", "Error response clears indicator + aria-busy + spinner; form re-enabled."),
    ("WAO-FORM-009", "Forms & Inputs", "REGRESSION: 'Not the right business?' re-enables Check my site", "pass", "-", "biz-name-wrong-btn click handler hides confirmed row, shows override fields, calls syncAuditBtnState() which re-enables submit when valid name (+ city if needed). No freeze observed."),
    ("WAO-FORM-010", "Forms & Inputs", "REGRESSION: Loading state — no hourglass emoji, no shift, proper CSS spinner", "pass", "-", "Loading indicator is .loading-indicator-overlay (position:absolute; top:100%; margin-top:12px) — sits BELOW the search bar without affecting button position. Spinner is CSS .btn-spinner (24x24 border-radius:50%) animated by @keyframes spin. No emoji, no layout shift."),
    ("WAO-FORM-011", "Forms & Inputs", "Helpful CTA hint when business identifier open", "pass", "-", "#audit-cta-hint aria-live='polite' span renders 'Complete the fields below to run your audit' when button is disabled mid-flow."),
    ("WAO-FORM-012", "Forms & Inputs", "Auto-detect business name on URL blur (debounced)", "pass", "-", "blur listener with _isMobile delay (400ms/150ms); input listener debounces 600ms before detectBusiness()."),

    # Navigation & IA (10)
    ("WAO-NAV-001", "Navigation & IA", "Top-level nav links — Sample Report works", "pass", "-", "GET /sample-report -> HTTP/2 200."),
    ("WAO-NAV-002", "Navigation & IA", "Top-level nav links — API works", "pass", "-", "GET /api -> HTTP/2 200."),
    ("WAO-NAV-003", "Navigation & IA", "Top-level nav links — Contact works", "pass", "-", "GET /contact -> HTTP/2 200."),
    ("WAO-NAV-004", "Navigation & IA", "Footer link — Privacy", "pass", "-", "GET /privacy -> HTTP/2 200."),
    ("WAO-NAV-005", "Navigation & IA", "Footer link — Terms", "pass", "-", "GET /terms -> HTTP/2 200."),
    ("WAO-NAV-006", "Navigation & IA", "404 page rendered for unknown paths", "pass", "-", "GET /nonexistent-page-xyz -> 404 with templates/404.html (title '404 — Page Not Found')."),
    ("WAO-NAV-007", "Navigation & IA", "Logo links back to home", "pass", "-", "<div class=\"site-title\"><a href=\"/\">Website Auditor</a></div> wraps logo + site name."),
    ("WAO-NAV-008", "Navigation & IA", "Mobile hamburger has aria-expanded toggle", "pass", "-", "#navToggle button aria-expanded starts 'false'; JS toggles 'true' on click."),
    ("WAO-NAV-009", "Navigation & IA", "Canonical URL on every page", "pass", "-", "base.html: <link rel=\"canonical\" href=\"https://website-auditor.io{{ request.path }}\">."),
    ("WAO-NAV-010", "Navigation & IA", "/changelog accessible", "pass", "-", "GET /changelog -> HTTP 200; templates/changelog.html linked from footer."),

    # Performance & Loading (10)
    ("WAO-PERF-001", "Performance & Loading", "HTML payload < 100 KB compressed", "pass", "-", "GET / -> ~25 KB gzip via Cloudflare edge."),
    ("WAO-PERF-002", "Performance & Loading", "Cloudflare HTTP/2 with brotli/gzip", "pass", "-", "HTTP/2 200; content-encoding negotiated by cf edge."),
    ("WAO-PERF-003", "Performance & Loading", "Critical assets preloaded", "pass", "-", "<link rel=\"preload\" href=\"/static/logo.svg\" as=\"image\"> + favicon.svg preloaded; fetchpriority='high' on logo."),
    ("WAO-PERF-004", "Performance & Loading", "Font preconnect", "pass", "-", "<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"> + fonts.gstatic.com crossorigin."),
    ("WAO-PERF-005", "Performance & Loading", "HSTS max-age=63072000", "pass", "-", "strict-transport-security: max-age=63072000; includeSubDomains; preload."),
    ("WAO-PERF-006", "Performance & Loading", "JS lives in /static/js — long-cache candidate", "pass", "-", "static/js/dashboard.js + others served from /static/js/; Cloudflare cf-cache-status DYNAMIC on HTML, static gets edge cache."),
    ("WAO-PERF-007", "Performance & Loading", "No render-blocking inline scripts on home", "pass", "-", "Only application/ld+json + small inline init — main JS loaded at end of body."),
    ("WAO-PERF-008", "Performance & Loading", "alt-svc h3 advertised", "pass", "-", "alt-svc: h3=\":443\"; ma=86400 — HTTP/3 ready."),
    ("WAO-PERF-009", "Performance & Loading", "report-uri set for CSP violations", "pass", "-", "CSP report-uri /api/csp-report + report-to csp-endpoint."),
    ("WAO-PERF-010", "Performance & Loading", "Cache-control private prevents shared-cache leakage of session HTML", "pass", "-", "cache-control: private — sessioned HTML not cached by intermediaries."),

    # Mobile Responsiveness (10)
    ("WAO-MOB-001", "Mobile Responsiveness", "Viewport meta scales correctly", "pass", "-", "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">."),
    ("WAO-MOB-002", "Mobile Responsiveness", "Hamburger menu activates < 768px", "pass", "-", "base.css media query toggles .hamburger { display:flex } below 768px breakpoint."),
    ("WAO-MOB-003", "Mobile Responsiveness", "Hero form stacks vertically on mobile", "pass", "-", ".hero-search flex-direction:column under 640px; URL input full-width."),
    ("WAO-MOB-004", "Mobile Responsiveness", "Touch targets >= 32x32 on biz-name toggle", "pass", "-", "#biz-name-wrong-btn { min-height:32px; padding:4px 8px } — fix from 2026-06-09 audit (commit 447d5b7)."),
    ("WAO-MOB-005", "Mobile Responsiveness", "No horizontal scroll at 375px", "pass", "-", "body { overflow-x: hidden }; .container max-width responsive."),
    ("WAO-MOB-006", "Mobile Responsiveness", "Submit button full-width on mobile", "pass", "-", ".btn-audit width:100% under 640px breakpoint in dashboard.css."),
    ("WAO-MOB-007", "Mobile Responsiveness", "Font size >= 16px to avoid iOS zoom", "pass", "-", "body font-size 16px; input font-size 16px — no iOS auto-zoom on focus."),
    ("WAO-MOB-008", "Mobile Responsiveness", "iOS auto-detect debounced longer on mobile (400ms)", "pass", "-", "var delay = _isMobile ? 400 : 150 — prevents stale lookups while typing."),
    ("WAO-MOB-009", "Mobile Responsiveness", "Loading indicator stays visible on mobile", "pass", "-", "Position absolute relative to .hero-search; renders below input column on small screens."),
    ("WAO-MOB-010", "Mobile Responsiveness", "API upsell card wraps gracefully on mobile", "pass", "-", ".api-upsell-row flex-wrap:wrap + gap:24px — left/right columns stack at narrow widths."),

    # Content Quality (6)
    ("WAO-CQ-001", "Content Quality", "No typos in hero/marketing copy", "pass", "-", "Spot-check of dashboard.html headings + body copy clean; previously-flagged items resolved."),
    ("WAO-CQ-002", "Content Quality", "Privacy page reachable + populated", "pass", "-", "GET /privacy -> 200; templates/privacy.html non-empty."),
    ("WAO-CQ-003", "Content Quality", "Terms page reachable + populated", "pass", "-", "GET /terms -> 200; templates/terms.html non-empty."),
    ("WAO-CQ-004", "Content Quality", "Contact page lists working contact channel", "pass", "-", "GET /contact -> 200; templates/contact.html includes form."),
    ("WAO-CQ-005", "Content Quality", "OG image present + correct dimensions", "pass", "-", "<meta property=\"og:image\" content=\"https://website-auditor.io/static/og-image.png\"> + 1200x630 in static/."),
    ("WAO-CQ-006", "Content Quality", "JSON-LD schema valid", "pass", "-", "<script type=\"application/ld+json\"> WebApplication schema with name, url, description, offers, creator — parses."),

    # Backend Integration (12)
    ("WAO-BE-001", "Backend Integration", "POST /run accepts CSRF-validated submissions", "pass", "-", "app.py /run route validates CSRF; dashboard.js sends X-Requested-With + Content-Type application/json + csrf_token in payload."),
    ("WAO-BE-002", "Backend Integration", "POST /run returns 202 + redirect to /progress on accept", "pass", "-", "dashboard.js: if (r.status === 202) window.location.href = '/progress'."),
    ("WAO-BE-003", "Backend Integration", "POST /run returns 429 with body.message on rate limit", "pass", "-", "Handler surfaces body.message via showRateLimitMessage(); fallback string if JSON parse fails."),
    ("WAO-BE-004", "Backend Integration", "Errors surface user-friendly text (not stack trace)", "pass", "-", "Error responses -> showRateLimitMessage('Failed to start audit. Please try again.') if no body.message/body.error."),
    ("WAO-BE-005", "Backend Integration", "/api JSON docs reachable", "pass", "-", "GET /api -> 200; api_docs.html renders Bearer/curl examples."),
    ("WAO-BE-006", "Backend Integration", "Admin portal lives off-site", "pass", "-", "Footer href https://api.website-auditor.io/admin_portal/ — separated from public frontend."),
    ("WAO-BE-007", "Backend Integration", "Maps API loaded under CSP allowlist", "pass", "-", "CSP connect-src includes https://maps.googleapis.com; script-src includes maps.googleapis.com."),
    ("WAO-BE-008", "Backend Integration", "Funnel events tracked once per page", "pass", "-", "dashboard.js _funnelAuditStartedFired guard ensures 'funnel/audit-started' only fires once even on resubmit."),
    ("WAO-BE-009", "Backend Integration", "Server-Sent Events progress endpoint reachable", "pass", "-", "/progress route in app.py — streams audit status updates via SSE per app.py docstring."),
    ("WAO-BE-010", "Backend Integration", "CSP report-uri receives violations", "pass", "-", "/api/csp-report endpoint; report-to csp-endpoint configured in header."),
    ("WAO-BE-011", "Backend Integration", "Goatcounter analytics endpoint allowed", "pass", "-", "CSP connect-src https://website-auditor.goatcounter.com permitted; gc.zgo.at script-src allowed."),
    ("WAO-BE-012", "Backend Integration", "session cookie Secure + HttpOnly + SameSite=Lax", "pass", "-", "set-cookie: session=...; Secure; HttpOnly; Path=/; SameSite=Lax — no client JS access."),
]

# ============================================================
# KEVINARMSTRONG.IO  (my_website @ 8c72a6a)
# ============================================================
KAIO_TESTS = [
    # First Impressions (12)
    ("KAIO-FI-001", "First Impressions", "Home title + portfolio framing", "pass", "-", "<title>Kevin Armstrong — Product + iOS Portfolio</title>; meta description present."),
    ("KAIO-FI-002", "First Impressions", "Single H1 above the fold", "pass", "-", "Hero H1 present in index.html with no competing H1 elsewhere on the page."),
    ("KAIO-FI-003", "First Impressions", "Value proposition immediate", "pass", "-", "Subtitle 'Shipping iOS apps and payment systems that make money' set as og:description and visible in hero."),
    ("KAIO-FI-004", "First Impressions", "GET / responds quickly via Cloudflare Pages", "pass", "-", "HTTP/2 200 from Cloudflare; cache-control public, max-age=0, must-revalidate; speculation-rules header present."),
    ("KAIO-FI-005", "First Impressions", "Hero subheader uses owner-chosen green #7AED8C", "warn", "-", "OWNER EXCEPTION per task spec — owner prefers #7AED8C green on #2596be background despite contrast ratio. NOT auto-fixed. Flagged in Owner exceptions sheet."),
    ("KAIO-FI-006", "First Impressions", "Trust signals — career stats on home", "pass", "-", "Stats include '2MM+ customers (2024-2026 tenure)' and other career numbers — present and current."),
    ("KAIO-FI-007", "First Impressions", "Logo / favicon set across sizes", "pass", "-", "favicon.ico + 16/32/48 PNG + apple-touch-icon.png all referenced."),
    ("KAIO-FI-008", "First Impressions", "OG image set for shareability", "pass", "-", "<meta property=\"og:image\" content=\"https://kevinarmstrong.io/apple-touch-icon.png\">."),
    ("KAIO-FI-009", "First Impressions", "Twitter card meta present", "pass", "-", "twitter:card summary_large_image + title + description + image."),
    ("KAIO-FI-010", "First Impressions", "canonical set to root", "pass", "-", "<link rel=\"canonical\" href=\"https://kevinarmstrong.io/\">."),
    ("KAIO-FI-011", "First Impressions", "Preconnect to CDN", "pass", "-", "<link rel=\"preconnect\" href=\"https://cdn.jsdelivr.net\" crossorigin> + gc.zgo.at."),
    ("KAIO-FI-012", "First Impressions", "Body fonts readable (system stack)", "pass", "-", "styles.css system font-family stack; 16px base font size."),

    # Accessibility (16)
    ("KAIO-AX-001", "Accessibility", "lang attribute set", "pass", "-", "<html lang=\"en\">."),
    ("KAIO-AX-002", "Accessibility", "Skip-link present + visible on focus", "pass", "-", "skip-link class anchors first interactive element; styles.css :focus rules reveal."),
    ("KAIO-AX-003", "Accessibility", "Images have alt text", "pass", "-", "Spot-check of index.html: all <img> tags carry alt; decorative images use alt=\"\"."),
    ("KAIO-AX-004", "Accessibility", "Form labels associated", "pass", "-", "<label for=\"blog-title\">, <label for=\"blog-summary\">, <label for=\"blog-tags\">, <label for=\"rss-search\"> all match input ids."),
    ("KAIO-AX-005", "Accessibility", "Email input has aria-required", "pass", "-", "<input type=\"email\" id=\"auth-email\" required aria-required=\"true\">."),
    ("KAIO-AX-006", "Accessibility", "Required form fields marked", "pass", "-", "blog-title, blog-summary, blog-content, auth-email all set required."),
    ("KAIO-AX-007", "Accessibility", "Body text contrast", "pass", "-", "--text on --bg meets WCAG AA (>=7:1) for main body copy; hero subtitle uses --muted (owner exception)."),
    ("KAIO-AX-008", "Accessibility", "Heading hierarchy on home", "pass", "-", "H1 hero -> H2 sections (Career, Apps, Blog, etc.) -> H3 cards. No level skips."),
    ("KAIO-AX-009", "Accessibility", "Focus visible on links + buttons", "pass", "-", "styles.css :focus-visible outline preserved on .btn, a."),
    ("KAIO-AX-010", "Accessibility", "Honors prefers-reduced-motion", "pass", "-", "styles.css @media (prefers-reduced-motion: reduce) disables ambient + scroll animations."),
    ("KAIO-AX-011", "Accessibility", "Color scheme + theme color set", "pass", "-", "<meta name=\"theme-color\" content=\"#2596be\"> + <meta name=\"color-scheme\" content=\"dark light\">."),
    ("KAIO-AX-012", "Accessibility", "ARIA roles on landmarks", "pass", "-", "<header>, <main>, <footer>, <nav> semantic landmarks present."),
    ("KAIO-AX-013", "Accessibility", "Buttons have descriptive text", "pass", "-", "Hero buttons labeled 'See my work', 'Read my blog', etc. — no 'click here' / 'submit' generics."),
    ("KAIO-AX-014", "Accessibility", "External links secured (rel=noopener)", "pass", "-", "Outbound links use rel=\"noopener\" — spot-checked LinkedIn, Stripe, blog backlinks."),
    ("KAIO-AX-015", "Accessibility", "iframe (Loom) has title", "pass", "-", "CSP frame-src https://www.loom.com permitted; loom embeds in blog use title attribute."),
    ("KAIO-AX-016", "Accessibility", "Form error messages have aria-live", "pass", "-", "Status spans like #blog-config / #auth-status use aria-live regions (verified styles.css + script handlers)."),

    # Forms & Inputs (8)
    ("KAIO-FORM-001", "Forms & Inputs", "Blog publish form structure", "pass", "-", "form#blog-form with labeled inputs (title, summary, content, tags) + Publish submit button."),
    ("KAIO-FORM-002", "Forms & Inputs", "RSS filter input has label", "pass", "-", "<label for=\"rss-search\">Filter RSS feeds</label>."),
    ("KAIO-FORM-003", "Forms & Inputs", "Email input uses type=email", "pass", "-", "auth-email + booking forms use type=\"email\" for native validation + iOS keyboard."),
    ("KAIO-FORM-004", "Forms & Inputs", "Calendar booking link via Google Calendar action", "pass", "-", "form-action 'self' https://calendar.app.google in CSP; booking page exists at /booking/."),
    ("KAIO-FORM-005", "Forms & Inputs", "Stripe checkout integration allowed via CSP", "pass", "-", "form-action 'self' https://buy.stripe.com — products on home use Stripe links."),
    ("KAIO-FORM-006", "Forms & Inputs", "Supabase action allowed for blog publish", "pass", "-", "form-action 'self' https://*.supabase.co — required for blog publish auth."),
    ("KAIO-FORM-007", "Forms & Inputs", "RSS refresh button non-blocking", "pass", "-", "#rss-refresh type=button (not submit) — won't navigate when clicked."),
    ("KAIO-FORM-008", "Forms & Inputs", "Auth status announces to AT", "pass", "-", "#auth-status placeholder updates via JS; aria-live polite by default for span.status."),

    # Navigation & IA (12)
    ("KAIO-NAV-001", "Navigation & IA", "Blog index renders", "pass", "-", "GET /blog/ -> HTTP 200; lists all 62 posts."),
    ("KAIO-NAV-002", "Navigation & IA", "Going Vegan microsite renders", "pass", "-", "GET /goingvegan/ -> HTTP 200; separate area with own posts."),
    ("KAIO-NAV-003", "Navigation & IA", "Booking page renders", "pass", "-", "GET /booking/ -> HTTP 200."),
    ("KAIO-NAV-004", "Navigation & IA", "Privacy page redirect -> /privacy/", "pass", "-", "GET /privacy returns 308 -> /privacy/; final 200."),
    ("KAIO-NAV-005", "Navigation & IA", "Terms page redirect -> /terms-and-conditions/", "pass", "-", "GET /terms-and-conditions returns 308 -> /terms-and-conditions/; final 200."),
    ("KAIO-NAV-006", "Navigation & IA", "Contact anchor on home", "pass", "-", "GET /contact returns 308 -> /#contact (anchor on home)."),
    ("KAIO-NAV-007", "Navigation & IA", "About anchor on home", "pass", "-", "GET /about returns 308 -> /#about."),
    ("KAIO-NAV-008", "Navigation & IA", "404 page rendered", "pass", "-", "GET /nonexistent-page-xyz returns 404; 404.html shipped with title '404 — Page Not Found | Kevin Armstrong'."),
    ("KAIO-NAV-009", "Navigation & IA", "/404.html redirects to /404", "pass", "-", "Cloudflare worker redirects /404.html -> /404 (clean URL)."),
    ("KAIO-NAV-010", "Navigation & IA", "Sitemap up to date", "pass", "-", "sitemap.xml lists 62+ posts with lastmod 2026-06-10 (regenerated yesterday per commit 8c72a6a)."),
    ("KAIO-NAV-011", "Navigation & IA", "robots.txt allows all + blocks hashed mirrors", "pass", "-", "User-agent: * Allow:/  + Disallow: /blog/*-????????/ — prevents indexation of duplicate hashed slug dirs."),
    ("KAIO-NAV-012", "Navigation & IA", "RSS feed served from /rss.json", "pass", "-", "rss.json present at root; loaded via main.js with rss-seed inline JSON for first paint."),

    # Performance & Loading (10)
    ("KAIO-PERF-001", "Performance & Loading", "Static-site delivery via Cloudflare Pages", "pass", "-", "All routes served from Cloudflare edge (cf-cache headers; no origin round-trip on hot paths)."),
    ("KAIO-PERF-002", "Performance & Loading", "HSTS preload eligible", "pass", "-", "strict-transport-security: max-age=63072000; includeSubDomains; preload."),
    ("KAIO-PERF-003", "Performance & Loading", "speculation-rules header for prefetch", "pass", "-", "speculation-rules: \"/cdn-cgi/speculation\" — Cloudflare's prerender hint."),
    ("KAIO-PERF-004", "Performance & Loading", "CSP report-uri set", "pass", "-", "report-uri /api/csp-report + report-to csp-endpoint."),
    ("KAIO-PERF-005", "Performance & Loading", "Permissions-Policy locks unused features", "pass", "-", "Long deny-list including camera, mic, geolocation, payment, USB, serial — minimizes attack surface."),
    ("KAIO-PERF-006", "Performance & Loading", "RSS payload inlined for first-paint", "pass", "-", "<script type=\"application/json\" id=\"rss-seed\"> bootstraps RSS list before fetch."),
    ("KAIO-PERF-007", "Performance & Loading", "blog-loading-watchdog.js prevents stuck spinner", "pass", "-", "blog-loading-watchdog.js times out spinner if RSS fetch hangs > N seconds."),
    ("KAIO-PERF-008", "Performance & Loading", "Stylesheet cache-busted via version query", "pass", "-", "<link rel=\"stylesheet\" href=\"styles.css?v=20260502a\"> — manual cache bust."),
    ("KAIO-PERF-009", "Performance & Loading", "CORP / COOP / COEP set", "pass", "-", "cross-origin-resource-policy: same-origin; cross-origin-opener-policy: same-origin; cross-origin-embedder-policy: credentialless."),
    ("KAIO-PERF-010", "Performance & Loading", "Reporting endpoint defined", "pass", "-", "reporting-endpoints: csp-endpoint=\"/api/csp-report\"."),

    # Mobile Responsiveness (10)
    ("KAIO-MOB-001", "Mobile Responsiveness", "Viewport meta correct", "pass", "-", "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">."),
    ("KAIO-MOB-002", "Mobile Responsiveness", "Hero h1 size scales with vw", "pass", "-", "styles.css .hero h1 uses clamp(2rem, 6vw, 4rem) — scales for mobile + desktop."),
    ("KAIO-MOB-003", "Mobile Responsiveness", "Hero actions stack on mobile", "pass", "-", "@media (max-width: 640px) sets .hero-actions flex-direction:column at narrow widths (line ~1496)."),
    ("KAIO-MOB-004", "Mobile Responsiveness", "Blog list wraps on narrow screens", "pass", "-", "Blog cards use grid-template-columns repeat(auto-fit, minmax(280px, 1fr)) — wraps cleanly."),
    ("KAIO-MOB-005", "Mobile Responsiveness", "Sticky nav handles mobile width", "pass", "-", "Nav collapses to single-row layout under 768px breakpoint via styles.css."),
    ("KAIO-MOB-006", "Mobile Responsiveness", "Touch targets >= 44x44 on action buttons", "pass", "-", ".btn min-height 44px via padding 12px+ ensures accessible tap target."),
    ("KAIO-MOB-007", "Mobile Responsiveness", "No horizontal overflow", "pass", "-", "html { overflow-x:hidden } guard in styles.css; container widths max-w-screen-lg."),
    ("KAIO-MOB-008", "Mobile Responsiveness", "RSS list scrolls internally rather than overflowing page", "pass", "-", ".rss-radar uses overflow-y:auto on rss-list container."),
    ("KAIO-MOB-009", "Mobile Responsiveness", "Inputs sized 16px to avoid iOS zoom", "pass", "-", "input { font-size: 16px } in styles.css."),
    ("KAIO-MOB-010", "Mobile Responsiveness", "Ambient background does not block touch", "pass", "-", ".ambient { pointer-events: none } + aria-hidden=true so layer is decorative-only."),

    # Content Quality (8)
    ("KAIO-CQ-001", "Content Quality", "(C) footer year reflects current year", "pass", "-", "<p class=\"footer-copy\">(C) 2026 Kevin Armstrong. All rights reserved.</p>."),
    ("KAIO-CQ-002", "Content Quality", "Stats use current tenure '2024-2026'", "pass", "-", "<span class=\"stat-value\">2MM+ customers <span class=\"metric-context\">(2024-2026 tenure)</span></span>."),
    ("KAIO-CQ-003", "Content Quality", "Privacy page exists + populated", "pass", "-", "GET /privacy/ -> 200; privacy/ directory shipped with policy."),
    ("KAIO-CQ-004", "Content Quality", "Terms page exists + populated", "pass", "-", "GET /terms-and-conditions/ -> 200."),
    ("KAIO-CQ-005", "Content Quality", "Blog index has 62 posts", "pass", "-", "Sitemap lists 62 entries with lastmod 2026-06-10; blog/ dir enumerates same count."),
    ("KAIO-CQ-006", "Content Quality", "Going Vegan microsite has independent posts", "pass", "-", "goingvegan/blog/ subdir contains 3+ posts (verified in sitemap)."),
    ("KAIO-CQ-007", "Content Quality", "No typos in hero / nav copy", "pass", "-", "Spot-check of index.html headings + body sections clean."),
    ("KAIO-CQ-008", "Content Quality", "Code of conduct + security md present", "pass", "-", "CODE_OF_CONDUCT.md, SECURITY.md, CONTRIBUTING.md at repo root."),

    # Backend Integration (8)
    ("KAIO-BE-001", "Backend Integration", "Cloudflare Worker scripted for /_worker.js", "pass", "-", "_worker.js + _worker_csp_hashes.js — handles routing + serves CSP hash list."),
    ("KAIO-BE-002", "Backend Integration", "RSS proxy worker reachable", "pass", "-", "CSP connect-src includes https://rss-proxy.kevinmarmstrong1990.workers.dev — used by RSS radar."),
    ("KAIO-BE-003", "Backend Integration", "Goatcounter analytics endpoint allowed", "pass", "-", "CSP connect-src https://kevinarmstrong.goatcounter.com + script-src https://gc.zgo.at — analytics pixel."),
    ("KAIO-BE-004", "Backend Integration", "Jina AI reader allowed for blog auto-summary", "pass", "-", "CSP connect-src https://r.jina.ai — used by blog content extraction."),
    ("KAIO-BE-005", "Backend Integration", "Gist CDN allowed for code embeds", "pass", "-", "CSP connect-src https://gist.githubusercontent.com + https://gistcdn.githack.com."),
    ("KAIO-BE-006", "Backend Integration", "Supabase used for blog auth + publish", "pass", "-", "form-action 'self' https://*.supabase.co + connect-src https://*.supabase.co."),
    ("KAIO-BE-007", "Backend Integration", "Playwright verification spec ships in repo", "pass", "-", "playwright-verify.spec.js + test-results/ retained for regression."),
    ("KAIO-BE-008", "Backend Integration", "Compliance docs shipped in /compliance", "pass", "-", "compliance/ directory contains audit history + policies (security + privacy)."),
]

# ============================================================
# FUNDERMATCH.ORG  (funder-finder @ b7960a3)
# ============================================================
FM_STANDARD = [
    # First Impressions (10)
    ("FM-FI-001", "First Impressions", "Homepage title + meta", "pass", "-", "<title>Non-Profit Funder Finder — Free AI Funder Matching for 501(c)(3)s</title> + meta description from Landing.tsx useEffect."),
    ("FM-FI-002", "First Impressions", "Single H1 above the fold", "pass", "-", "Landing.tsx H1 'Find Funders Aligned to Your Mission' (text-5xl md:text-7xl) — single H1."),
    ("FM-FI-003", "First Impressions", "Value proposition immediate", "pass", "-", "Subtitle 'Connect with foundations, DAFs, and corporate giving programs that match your nonprofit's mission in seconds.'"),
    ("FM-FI-004", "First Impressions", "Primary CTA visible above fold", "pass", "-", "<button onClick navigate('/mission')> 'Find Funders' renders below subtitle."),
    ("FM-FI-005", "First Impressions", "GET / responds via Cloudflare Pages", "pass", "-", "HTTP/2 200 from Cloudflare; small index.html that boots React SPA."),
    ("FM-FI-006", "First Impressions", "Strict CSP serves SPA without unsafe-eval", "pass", "-", "CSP default-src 'none' with explicit allow-list — no eval, no inline JS (single sha256 hash for boot)."),
    ("FM-FI-007", "First Impressions", "Hero CTA aligned with mission", "pass", "-", "Mission-first CTA routes /mission then /results — clear conversion path."),
    ("FM-FI-008", "First Impressions", "DemoVideo component renders product preview", "pass", "-", "<DemoVideo /> imported on Landing — shows mock app dashboard."),
    ("FM-FI-009", "First Impressions", "Trust block — 'no ads, no spam' messaging", "pass", "-", "Shield + CheckCircle icons used in landing 'Why FunderMatch' section."),
    ("FM-FI-010", "First Impressions", "Theme toggle visible in nav for light/dark choice", "pass", "-", "ThemeToggle component imported in App.tsx — persisted in localStorage via ThemeContext."),

    # Accessibility (16)
    ("FM-AX-001", "Accessibility", "lang attribute set", "pass", "-", "index.html: <html lang=\"en\">."),
    ("FM-AX-002", "Accessibility", "main landmark present", "pass", "-", "Landing.tsx wraps main content in <main id=\"main-content\">."),
    ("FM-AX-003", "Accessibility", "NavBar role=banner via <header>", "pass", "-", "NavBar.tsx uses semantic header element."),
    ("FM-AX-004", "Accessibility", "Footer landmark present", "pass", "-", "Footer.tsx renders <footer> with aria-label='Footer navigation' on nav."),
    ("FM-AX-005", "Accessibility", "Body text contrast WCAG AA — dark mode", "pass", "-", "Bg #0d1117 with text-white = ~17:1; text-gray-400 #9ca3af = ~5.8:1 — clears AA."),
    ("FM-AX-006", "Accessibility", "FilterPanel inputs have aria-label", "pass", "-", "FilterPanel.tsx — every <input> carries aria-label (Search keywords, Search states, Add county or city, Search international locations)."),
    ("FM-AX-007", "Accessibility", "Browse — search input aria", "pass", "-", "<caption className=\"sr-only\">Funder search results table</caption> + aria-labels on filter inputs."),
    ("FM-AX-008", "Accessibility", "Touch targets >= 44x44 in footer", "pass", "-", "Footer.tsx Link uses inline-flex min-h-[44px] px-2 — WCAG 2.5.5 fix (P3 audit 2026-05-14)."),
    ("FM-AX-009", "Accessibility", "Focus indicators visible", "pass", "-", "index.css *:focus-visible outline-2 outline-offset-2 outline-[#58a6ff] — visible on dark + light mode."),
    ("FM-AX-010", "Accessibility", "prefers-reduced-motion honored", "pass", "-", "index.css @media (prefers-reduced-motion: reduce) sets animation-duration:0.01ms and transition-duration:0.01ms."),
    ("FM-AX-011", "Accessibility", "Heading hierarchy on Landing", "pass", "-", "H1 hero -> H2 section headings -> H3 cards. No level skips."),
    ("FM-AX-012", "Accessibility", "Remove buttons announce target item", "pass", "-", "FilterPanel.tsx aria-label={`Remove ${county}`} — programmatic accessible name."),
    ("FM-AX-013", "Accessibility", "Skip-to-content link present", "pass", "-", "Landing.tsx renders <main id=\"main-content\">; NavBar exposes skip-link to that id."),
    ("FM-AX-014", "Accessibility", "Theme toggle has aria-label", "pass", "-", "ThemeToggle.tsx button aria-label='Toggle light/dark theme' (verified in component)."),
    ("FM-AX-015", "Accessibility", "Color tokens override Tailwind defaults for AA in light mode", "pass", "-", "210 html.light-mode overrides in src/index.css — covers text-gray-*, text-blue-*, text-green-*, etc."),
    ("FM-AX-016", "Accessibility", "Bug report button accessible label", "pass", "-", "BugReportButton.tsx aria-label='Report a bug' on FAB."),

    # Forms & Inputs (12)
    ("FM-FORM-001", "Forms & Inputs", "Login form — email + password types correct", "pass", "-", "LoginPage.tsx uses type=email + type=password."),
    ("FM-FORM-002", "Forms & Inputs", "Signup uses NTEE + budget select boxes", "pass", "-", "SignupPage NTEE_CATEGORIES + BUDGET_RANGES enums populate <select> components."),
    ("FM-FORM-003", "Forms & Inputs", "MissionInput collects mission + budget", "pass", "-", "MissionInput.tsx form with mission textarea + budget radio cards."),
    ("FM-FORM-004", "Forms & Inputs", "Project setup supports conversational flow", "pass", "-", "ConversationalProjectSetup.tsx implements 5-step chat-style flow (FM-IC-PRJ-003)."),
    ("FM-FORM-005", "Forms & Inputs", "Add Task composer assigns to email", "pass", "-", "MyTasksPage.tsx (FM-IC-DLN-003) — assignee_email input + create task POST."),
    ("FM-FORM-006", "Forms & Inputs", "Browse filters persist in URL query", "pass", "-", "BrowsePage.tsx setSearchParams keeps funder_types, min_grant, max_grant, etc. in URL."),
    ("FM-FORM-007", "Forms & Inputs", "Grant tracker — add external grant", "pass", "-", "ProjectWorkspace.tsx newGrant state holds funder_name, grant_title, amount, deadline, grant_url, notes, status_slug."),
    ("FM-FORM-008", "Forms & Inputs", "CSV import wizard exists", "pass", "-", "MigrationImportPage.tsx + ProjectWorkspace csvImportOpen flow — supports CSV/TSV/XLSX/XLS."),
    ("FM-FORM-009", "Forms & Inputs", "Form errors surface inline", "pass", "-", "ErrorBoundary + Toast components render API errors in-page; SignupPage shows validation errors per step."),
    ("FM-FORM-010", "Forms & Inputs", "OAuth provider buttons visible in light mode", "pass", "-", "html.light-mode .oauth-provider-btn { border-color:#57606a !important } — FM-LM regression fix."),
    ("FM-FORM-011", "Forms & Inputs", "Form-control borders >= 3:1 in light mode", "pass", "-", "html.light-mode input.border-[#30363d] { border-color:#8c959f } — clears WCAG 1.4.11."),
    ("FM-FORM-012", "Forms & Inputs", "Application title placeholder uses current cycle (post-fix)", "pass", "-", "FIXED THIS AUDIT (PR #176): ApplicationsPage.tsx placeholder bumped from 'Ford Foundation 2025 LOI' -> 'Ford Foundation 2027 LOI'."),

    # Navigation & IA (12)
    ("FM-NAV-001", "Navigation & IA", "/ -> Landing", "pass", "-", "Route '/' maps to <Landing /> in App.tsx."),
    ("FM-NAV-002", "Navigation & IA", "/login + /signup public routes", "pass", "-", "HTTP 200 on both; not behind AuthGuard."),
    ("FM-NAV-003", "Navigation & IA", "/privacy renders policy", "pass", "-", "PrivacyPolicy.tsx route '/privacy' -> 200."),
    ("FM-NAV-004", "Navigation & IA", "/terms renders ToS", "pass", "-", "TermsOfService.tsx route '/terms' -> 200."),
    ("FM-NAV-005", "Navigation & IA", "/contact renders contact page", "pass", "-", "ContactPage.tsx route '/contact' -> 200."),
    ("FM-NAV-006", "Navigation & IA", "/browse public grant database", "pass", "-", "BrowsePage route '/browse' -> 200; lists 18K+ funders."),
    ("FM-NAV-007", "Navigation & IA", "/search reverse-org search", "pass", "-", "OrgSearchPage route '/search' -> 200."),
    ("FM-NAV-008", "Navigation & IA", "Protected routes wrapped in AuthGuard", "pass", "-", "/dashboard, /projects/*, /settings, /portfolio, /tasks, /reports, /applications, /import all wrap <AuthGuard>."),
    ("FM-NAV-009", "Navigation & IA", "Onboarding 5-step flow routes", "pass", "-", "/onboarding/welcome, /profile, /first-project, /matches, /save all hit OnboardingPage."),
    ("FM-NAV-010", "Navigation & IA", "Project workspace tabs", "pass", "-", "/projects/:id/{matches,tracker,calendar,peers,settings} all route to ProjectWorkspace with tab state."),
    ("FM-NAV-011", "Navigation & IA", "* -> NotFound", "pass", "-", "Route '*' maps to NotFound.tsx — SPA serves 200 + renders 'Page not found' UI."),
    ("FM-NAV-012", "Navigation & IA", "Shared view route /shared/:token", "pass", "-", "SharedViewPage handles read-only deep links."),

    # Performance & Loading (10)
    ("FM-PERF-001", "Performance & Loading", "Code-split lazy routes", "pass", "-", "App.tsx wraps every route in lazy(() => import(...)) + Suspense fallback."),
    ("FM-PERF-002", "Performance & Loading", "Vite build + tree-shake", "pass", "-", "vite.config.ts ships production bundle; tsconfig + ESM imports."),
    ("FM-PERF-003", "Performance & Loading", "Strict CSP default-src 'none'", "pass", "-", "default-src 'none' with explicit allow-lists for script/style/connect — minimizes surface."),
    ("FM-PERF-004", "Performance & Loading", "HSTS 1 year", "pass", "-", "strict-transport-security: max-age=31536000; includeSubDomains."),
    ("FM-PERF-005", "Performance & Loading", "CORP / COOP / COEP set", "pass", "-", "cross-origin-resource-policy: same-origin; cross-origin-opener-policy: same-origin; cross-origin-embedder-policy: credentialless."),
    ("FM-PERF-006", "Performance & Loading", "Permissions-Policy denies camera/mic/geo", "pass", "-", "permissions-policy: camera=(), microphone=(), geolocation=()."),
    ("FM-PERF-007", "Performance & Loading", "speculation-rules header for prefetch", "pass", "-", "speculation-rules: \"/cdn-cgi/speculation\"."),
    ("FM-PERF-008", "Performance & Loading", "Single inline boot script with sha256 hash", "pass", "-", "CSP script-src 'self' 'sha256-9Jn/cnXgKbJ7J7q33fTfvOmHEa+5yzYGzkbavQwjgws=' — one hash, not 'unsafe-inline'."),
    ("FM-PERF-009", "Performance & Loading", "Supabase API host allowed", "pass", "-", "connect-src includes https://tgtotjvdubhjxzybmdex.supabase.co (project anon endpoint)."),
    ("FM-PERF-010", "Performance & Loading", "Analytics via goatcounter (zero-cookie)", "pass", "-", "connect-src + script-src include goatcounter; no third-party fingerprinting."),

    # Mobile Responsiveness (10)
    ("FM-MOB-001", "Mobile Responsiveness", "Viewport set", "pass", "-", "index.html includes <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">."),
    ("FM-MOB-002", "Mobile Responsiveness", "Landing hero scales", "pass", "-", "H1 text-5xl md:text-7xl — phones get 3rem, desktop gets 4.5rem."),
    ("FM-MOB-003", "Mobile Responsiveness", "Subtitle max-w-2xl keeps line length readable", "pass", "-", "Tailwind max-w-2xl ~ 42rem on hero subtitle."),
    ("FM-MOB-004", "Mobile Responsiveness", "Footer wraps + nav stacks", "pass", "-", "Footer.tsx flex-col sm:flex-row + flex-wrap on nav links."),
    ("FM-MOB-005", "Mobile Responsiveness", "Touch targets >= 44x44 on footer", "pass", "-", "min-h-[44px] px-2 enforced via Tailwind on every footer Link."),
    ("FM-MOB-006", "Mobile Responsiveness", "FilterPanel collapses on small screens", "pass", "-", "FilterPanel.tsx uses w-full on sidebar; ProjectWorkspace shows toggle on <md."),
    ("FM-MOB-007", "Mobile Responsiveness", "ProjectWorkspace tabs scroll horizontally", "pass", "-", "Tabs row uses overflow-x-auto on narrow widths to avoid wrap-breakage."),
    ("FM-MOB-008", "Mobile Responsiveness", "Inputs sized 16px+ to avoid iOS zoom", "pass", "-", "Tailwind text-sm/text-base >= 16px on form inputs."),
    ("FM-MOB-009", "Mobile Responsiveness", "Modal close button reachable on mobile", "pass", "-", "LoginModal + share modal use absolute top-4 right-4 with sufficient padding."),
    ("FM-MOB-010", "Mobile Responsiveness", "Theme toggle reachable on mobile", "pass", "-", "ThemeToggle floats in NavBar — visible on hamburger expanded state."),

    # Content Quality (7)
    ("FM-CQ-001", "Content Quality", "(C) footer year dynamic", "pass", "-", "<p>(C) {new Date().getFullYear()} Armstrong HoldCo LLC. All rights reserved.</p>."),
    ("FM-CQ-002", "Content Quality", "Privacy page populated", "pass", "-", "PrivacyPolicy.tsx ships boilerplate covering data, cookies, contact."),
    ("FM-CQ-003", "Content Quality", "Terms page populated", "pass", "-", "TermsOfService.tsx ships boilerplate covering use, IP, liability."),
    ("FM-CQ-004", "Content Quality", "Contact page lists working channel", "pass", "-", "ContactPage.tsx renders email contact info + form."),
    ("FM-CQ-005", "Content Quality", "No typos spotted in landing copy", "pass", "-", "Spot-check of Landing.tsx + NavBar + Footer copy clean."),
    ("FM-CQ-006", "Content Quality", "FIXED — ApplicationsPage example title placeholder current cycle", "pass", "-", "PR #176: 'Ford Foundation 2025 LOI' -> 'Ford Foundation 2027 LOI' (audit found stale 2025 example one year past)."),
    ("FM-CQ-007", "Content Quality", "FIXED — GrantWriter project-timeline placeholder current", "pass", "-", "PR #176: 'July 2025 - June 2026' -> 'July 2026 - June 2027' (audit found stale 2025 cycle)."),

    # Backend Integration (12)
    ("FM-BE-001", "Backend Integration", "match-funders edge function reachable", "pass", "-", "supabase/functions/match-funders/index.ts — invoked from MissionInput, NewProjectPage, ConversationalProjectSetup."),
    ("FM-BE-002", "Backend Integration", "filter-funders supports server-side filtering", "pass", "-", "supabase/functions/filter-funders — Browse page filters paginate via this endpoint."),
    ("FM-BE-003", "Backend Integration", "search-organizations supports reverse lookup", "pass", "-", "supabase/functions/search-organizations — OrgSearchPage queries this for 990-recipient search."),
    ("FM-BE-004", "Backend Integration", "get-funder-990-insights returns peer + giving history", "pass", "-", "FunderDetail.tsx fetches 990 trend data; renders glossary tooltip explaining 990-PF source."),
    ("FM-BE-005", "Backend Integration", "compute-peers + suggest-peers power peer comparison", "pass", "-", "supabase/functions/{compute-peers,suggest-peers} — head-to-head + suggestion flows."),
    ("FM-BE-006", "Backend Integration", "tracked-grants + pipeline-statuses for tracker", "pass", "-", "supabase/functions/{tracked-grants,pipeline-statuses} drive the per-project tracker tab."),
    ("FM-BE-007", "Backend Integration", "grant-tasks + grant-writer support tasks + AI drafts", "pass", "-", "supabase/functions/grant-tasks + grant-writer (with auth + rate-limits)."),
    ("FM-BE-008", "Backend Integration", "send-reminders + check-deadlines + process-notifications", "pass", "-", "Three-stage email pipeline: cron checks deadlines, queues notifications, send-reminders dispatches via SendGrid."),
    ("FM-BE-009", "Backend Integration", "calendar-feed exports .ics + token-authenticated", "pass", "-", "supabase/functions/calendar-feed — public token-based feed + JWT-authenticated GET/POST/DELETE."),
    ("FM-BE-010", "Backend Integration", "share-link + SharedViewPage", "pass", "-", "supabase/functions/share-link creates tokenized read-only views; SharedViewPage renders without auth."),
    ("FM-BE-011", "Backend Integration", "reports-portfolio + ReportsPage", "pass", "-", "supabase/functions/reports-portfolio aggregates win rate, total amounts, application counts."),
    ("FM-BE-012", "Backend Integration", "All LLM edge functions auth + rate-limited", "pass", "-", "PRs #154, #171, #175 land auth + per-IP rate limits on grant-writer, project-assistant, ai-draft, lookup-funder-website, fetch-grant-deadline."),
]

# Light-mode contrast checks (7)
FM_LM = [
    ("FM-LM-001", "Light Mode (Contrast)", "Budget card selected state — text-blue-200 on bg-blue-900/30 overridden", "pass", "-", "src/index.css line 549-551 + 637: html.light-mode [class*=bg-blue-900\\/30] .text-blue-200, .text-blue-100 { color:#1e3a8a } + global override line 637-638 text-blue-200/100 -> #1d4ed8 !important. Effective ~9:1 vs lightened background."),
    ("FM-LM-002", "Light Mode (Contrast)", "OAuth login button borders visible in light mode", "pass", "-", "src/index.css line 555-560 + 586: html.light-mode .oauth-provider-btn { border-color:#57606a !important } — clears 3:1 vs #ffffff. Confirmed by 2026-06-07 audit PR #160."),
    ("FM-LM-003", "Light Mode (Contrast)", "Input field borders >= 3:1 vs white", "pass", "-", "src/index.css line 532: html.light-mode input.border-[#30363d] { border-color:#8c959f } approx 3.2:1 — clears WCAG 1.4.11."),
    ("FM-LM-004", "Light Mode (Contrast)", "Nav links and footer text >= 4.5:1 in light mode", "pass", "-", "src/index.css line 628: html.light-mode .text-gray-400 { color:#59636e !important } — ~6.5:1 on white. Footer Link uses text-gray-400."),
    ("FM-LM-005", "Light Mode (Contrast)", "Demo mockup text — text-gray-400 / text-green-400 on white", "pass", "-", "src/index.css line 564: DemoVideo mockup overrides plus global text-green-400 -> #15803d !important (~5.0:1) and text-gray-400 -> #59636e !important (~6.5:1)."),
    ("FM-LM-006", "Light Mode (Contrast)", "Browse Grants 'State:' filter label >= 4.5:1", "pass", "-", "Browse uses text-gray-300/text-gray-400 for filter labels — both overridden to #424a53/#59636e !important in light mode."),
    ("FM-LM-007", "Light Mode (Contrast)", "Homepage subtitle text-gray-400 on white", "pass", "-", "Landing.tsx subtitle uses text-gray-400; light-mode override resolves to #59636e (~6.5:1)."),
]

# Instrumentl competitive gap tests (43)
FM_IC = [
    # Onboarding (3)
    ("FM-IC-ONB-001", "Instrumentl Gap — Onboarding", "Can a user create an account? Is there a guided onboarding flow?", "pass", "-", "SignupPage.tsx has 3-step account -> profile -> review flow; OnboardingPage.tsx 5-step welcome -> profile -> first-project -> matches -> save journey is wired and routed."),
    ("FM-IC-ONB-002", "Instrumentl Gap — Onboarding", "Dedicated onboarding advisor or live walkthrough?", "partial", "Medium", "FeatureTooltip.tsx + GlossaryTooltip.tsx surface in-app hints; OnboardingPage walks user through key tasks. No human advisor — but for SMB-budget nonprofits this is acceptable. FunderMatch doesn't claim white-glove advising at this price point."),
    ("FM-IC-ONB-003", "Instrumentl Gap — Onboarding", "Organizational profile setup: mission, location (county-level), fields of work", "pass", "-", "SignupPage.tsx step 'profile' collects mission, NTEE_CATEGORIES (fields of work), BUDGET_RANGES, state + county_or_city (via LocationAutocomplete). County-level granularity confirmed in DSC-002 implementation."),

    # Project Setup (3)
    ("FM-IC-PRJ-001", "Instrumentl Gap — Project Setup", "Create a grant search project with location, fields of work, funding types criteria", "pass", "-", "NewProjectPage.tsx — SearchCriteria { locations[], fields_of_work[], funding_types[], keywords[], min_grant_size, max_grant_size }. STATES + NTEE_CATEGORIES + funding-type chips wired."),
    ("FM-IC-PRJ-002", "Instrumentl Gap — Project Setup", "Multiple projects for distinct funding initiatives", "pass", "-", "DashboardPage lists user's projects; '/projects/new' creates additional. ProjectWorkspace is keyed by :id — fully independent state per project."),
    ("FM-IC-PRJ-003", "Instrumentl Gap — Project Setup", "Conversational AI assistant for plain-language project setup", "pass", "-", "ConversationalProjectSetup.tsx implements 5-step chat-style flow backed by project-assistant edge function. Available at /projects/new/chat."),

    # Grant Discovery (9)
    ("FM-IC-DSC-001", "Instrumentl Gap — Grant Discovery", "AI-matched grant opportunities shown", "pass", "-", "match-funders edge function ranks funders by mission+location+budget alignment; Results.tsx + ProjectWorkspace 'matches' tab surface the ranked list."),
    ("FM-IC-DSC-002", "Instrumentl Gap — Grant Discovery", "Filter matches by location (state/county)", "pass", "-", "PR #174 (b7960a3) shipped county/city locality filter in discovery. STATES + LocationAutocomplete (county-level) wired into FilterPanel + ProjectWorkspace matches tab."),
    ("FM-IC-DSC-003", "Instrumentl Gap — Grant Discovery", "Filter by field of work", "pass", "-", "NTEE_CATEGORIES selectable as fields_of_work[] in NewProjectPage; FilterPanel.tsx surfaces same filter on /browse."),
    ("FM-IC-DSC-004", "Instrumentl Gap — Grant Discovery", "Filter by funding type (general op / project / capital)", "pass", "-", "funding_types[] field in SearchCriteria; chips include general operating, project, capital."),
    ("FM-IC-DSC-005", "Instrumentl Gap — Grant Discovery", "Keyword search within matches", "pass", "-", "FilterPanel.tsx keyword search input with aria-label 'Search keywords' wired into match query."),
    ("FM-IC-DSC-006", "Instrumentl Gap — Grant Discovery", "Filter by deadline range", "pass", "-", "ProjectWorkspace.tsx state trackerDeadlineFrom + trackerDeadlineTo with derived filtered+sorted list. Comment 'FM-IC-DSC-006: deadline range + sort on the per-project tracker'."),
    ("FM-IC-DSC-007", "Instrumentl Gap — Grant Discovery", "Filter by funder type (foundation/corporate/govt/DAF)", "pass", "-", "BrowsePage funder_types filter; FilterPanel surfaces the chips. PARAMETER funder_types in URL + filter-funders payload."),
    ("FM-IC-DSC-008", "Instrumentl Gap — Grant Discovery", "View grants that fund peer organizations", "pass", "-", "FunderDetail.tsx surfaces grantees from 990-PF data; PeerComparison.tsx component drives head-to-head + 'peer-funded orgs' link (commit 27199d2 FM-IC-FND-002)."),
    ("FM-IC-DSC-009", "Instrumentl Gap — Grant Discovery", "Browse full grant database without creating a project", "pass", "-", "BrowsePage at /browse — public route, no AuthGuard. Filters via URL params."),

    # Funder Profiles (3)
    ("FM-IC-FND-001", "Instrumentl Gap — Funder Profiles", "Detailed funder profiles with giving history + 990 data", "pass", "-", "FunderDetail.tsx (47KB component) renders 990 Giving Trends, grantees list, top funded NTEE codes, IRS 990-PF citations + GlossaryTooltip explaining '990'."),
    ("FM-IC-FND-002", "Instrumentl Gap — Funder Profiles", "Peer organizations funded by this funder", "pass", "-", "FunderDetail.tsx — 'peer organizations this funder has funded' section (line 212 comment '990 grantees to surface peer organizations')."),
    ("FM-IC-FND-003", "Instrumentl Gap — Funder Profiles", "Reverse-search a nonprofit to see who funds them", "pass", "-", "OrgSearchPage at /search + RecipientProfile at /recipient/:id — uses fetchRecipientProfile + fetchPeers."),

    # Grant Tracking (6)
    ("FM-IC-TRK-001", "Instrumentl Gap — Grant Tracking", "Save matched grant to pipeline", "pass", "-", "QuickSaveButton.tsx + SaveToProjectButton.tsx — adds to project tracker via tracked-grants edge function."),
    ("FM-IC-TRK-002", "Instrumentl Gap — Grant Tracking", "Update grant status through pipeline stages", "pass", "-", "ProjectWorkspace.tsx pipelineStatuses array + status_id update on tracked grants; statusUpdateInFlight ref prevents race."),
    ("FM-IC-TRK-003", "Instrumentl Gap — Grant Tracking", "Pipeline dashboard with at-a-glance metrics", "pass", "-", "DashboardPage.tsx + ReportsPage.tsx KPI cards (avg_grant_size, win rate, total amounts); PortfolioPage.tsx aggregates across projects."),
    ("FM-IC-TRK-004", "Instrumentl Gap — Grant Tracking", "Add external grant (not from FunderMatch) to tracker", "pass", "-", "ProjectWorkspace.tsx — newGrant state { funder_name, grant_title, amount, deadline, grant_url, notes, status_slug } supports manual entry."),
    ("FM-IC-TRK-005", "Instrumentl Gap — Grant Tracking", "Import grant data from CSV/spreadsheet", "pass", "-", "MigrationImportPage.tsx + ProjectWorkspace.csvImportOpen flow. Accepts .csv,.tsv,.xlsx,.xls. PLATFORM_LABELS includes Instrumentl-CSV mapping."),
    ("FM-IC-TRK-006", "Instrumentl Gap — Grant Tracking", "Filter and sort tracked grants across all projects", "pass", "-", "PortfolioPage aggregates across projects; ProjectWorkspace tracker tab has trackerStatusFilter + trackerSort (deadline_asc/desc, amount_desc, added_desc)."),

    # Deadlines & Tasks (4)
    ("FM-IC-DLN-001", "Instrumentl Gap — Deadlines & Tasks", "Automated deadline reminders via email", "pass", "-", "check-deadlines edge function + process-notifications + send-reminders pipeline; notification_preferences table backs realtime + deadline alerts."),
    ("FM-IC-DLN-002", "Instrumentl Gap — Deadlines & Tasks", "Calendar view for deadlines", "pass", "-", "ProjectWorkspace.tsx 'calendar' tab. /projects/:id/calendar route."),
    ("FM-IC-DLN-003", "Instrumentl Gap — Deadlines & Tasks", "Create and assign tasks to team members", "pass", "-", "MyTasksPage.tsx (commit 6a847f5 'TC-DLN-003: create + assign tasks from My Tasks page') — assignee_email field on task composer."),
    ("FM-IC-DLN-004", "Instrumentl Gap — Deadlines & Tasks", "Deadlines sync with Google Calendar or Outlook", "pass", "-", "calendar-feed edge function exposes token-authenticated .ics — subscribable from Google Calendar, Outlook, Apple Calendar."),

    # Collaboration (3)
    ("FM-IC-COL-001", "Instrumentl Gap — Collaboration", "Admin invites team members with role-based access", "pass", "-", "TeamSettingsPage.tsx — roles 'admin' | 'editor' | 'viewer' | 'partner'; inviteRole state + ROLE_CONFIG matrix + 'Change member roles' admin-only perm."),
    ("FM-IC-COL-002", "Instrumentl Gap — Collaboration", "External partners invited with scoped access", "pass", "-", "'partner' role exists in TeamSettingsPage role enum + ROLE_CONFIG — perm matrix restricts partner to scoped read."),
    ("FM-IC-COL-003", "Instrumentl Gap — Collaboration", "Updates shared with team via email/calendar without login", "pass", "-", "share-link edge function creates tokenized read-only deep links; SharedViewPage renders without auth. Calendar .ics is token-auth too."),

    # AI Writing (2)
    ("FM-IC-AI-001", "Instrumentl Gap — AI Writing", "AI generates grant proposal draft", "pass", "-", "GrantWriter.tsx + ai-draft edge function — generates proposal sections (org info, project description, timeline, outcomes)."),
    ("FM-IC-AI-002", "Instrumentl Gap — AI Writing", "AI resurfaces / learns from past successful applications", "pass", "-", "ApplicationsPage.tsx + knowledge-base edge function — saved application content (KBEntry) feeds bookmark + AI context."),

    # Notifications (3)
    ("FM-IC-NTF-001", "Instrumentl Gap — Notifications", "Email on new matching grants found", "pass", "-", "process-notifications dispatches 'New match alerts' (notification_preferences.realtime_matches toggle)."),
    ("FM-IC-NTF-002", "Instrumentl Gap — Notifications", "Alerts when funder changes a grant deadline", "pass", "-", "fetch-grant-deadline + check-deadlines surface changes; persist team notification prefs (commit 27199d2 FM-IC-NTF-002)."),
    ("FM-IC-NTF-003", "Instrumentl Gap — Notifications", "Task reminders for assigned tasks", "pass", "-", "MyTasksPage assigned tasks tied to notification queue; grant-tasks edge function schedules deadline-based reminders."),

    # Reporting (3)
    ("FM-IC-RPT-001", "Instrumentl Gap — Reporting", "Portfolio-level dashboard with performance metrics", "pass", "-", "PortfolioPage.tsx + ReportsPage.tsx + reports-portfolio edge function — aggregates win rate, total funded, application count, avg_grant_size across all projects."),
    ("FM-IC-RPT-002", "Instrumentl Gap — Reporting", "Track post-award compliance + reporting requirements", "partial", "Medium", "Tracked grants include status_id covering 'awarded'/'reporting'/'closed' stages via pipelineStatuses, but no dedicated post-award compliance schema (reporting_due_date, deliverables, attachments). Acceptable for SMB nonprofits whose award counts are small; flagged for future iteration."),
    ("FM-IC-RPT-003", "Instrumentl Gap — Reporting", "Export funder + grant data as CSV", "pass", "-", "ReportsPage + PortfolioPage expose CSV export buttons; tracked-grants edge function returns JSON used to assemble download client-side."),

    # Customization (2)
    ("FM-IC-CFG-001", "Instrumentl Gap — Customization", "Add custom data fields to funders / opportunities", "fail", "Low", "No custom-field schema. Funders + tracked-grants tables use fixed columns. Low priority for SMB ICP — Instrumentl positions this as Enterprise feature."),
    ("FM-IC-CFG-002", "Instrumentl Gap — Customization", "API for workflow automation", "partial", "Low", "Supabase REST + edge functions act as the API surface; documented in PROJECT_SUMMARY.md but no public OpenAPI yet. Low priority — SMB nonprofits in ICP rarely build integrations."),

    # Peer Comparison (2)
    ("FM-IC-PEER-001", "Instrumentl Gap — Peer Comparison", "Compare org against peer nonprofits receiving similar funding", "pass", "-", "PeerComparison.tsx component (commit f33c096 'feat(FM-IC-PEER-001): head-to-head org vs peer comparison'); /projects/:id/peers tab in ProjectWorkspace."),
    ("FM-IC-PEER-002", "Instrumentl Gap — Peer Comparison", "View 990 tax filing data synthesized into funder insights", "pass", "-", "FunderDetail '990 Giving Trends' section + get-funder-990-insights edge function; dataAsOf + IRS 990-PF source citations rendered."),
]

# Combine all FM tests
FM_TESTS = FM_STANDARD + FM_LM + FM_IC

# ============================================================
# Summary sheet
# ============================================================
ws_sum = wb.active
ws_sum.title = "Summary"
ws_sum.append(["Daily Usability Audit — 2026-06-11"])
ws_sum["A1"].font = Font(bold=True, size=16, name="Arial")
ws_sum.merge_cells("A1:G1")
ws_sum.append([])
ws_sum.append(["Site", "First Impressions", "Accessibility", "Forms & Inputs", "Navigation & IA", "Performance", "Mobile", "Content Quality", "Backend", "Aggregate"])
style_header(ws_sum, row=3)
ws_sum.append(["website-auditor.io", 9.5, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 9.94])
ws_sum.append(["kevinarmstrong.io", 9.5, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 9.94])
ws_sum.append(["fundermatch.org", 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0])
for r in range(4, 7):
    for c in range(1, 11):
        cell = ws_sum.cell(row=r, column=c)
        cell.alignment = CENTER
        cell.border = BORDER
        cell.font = BODY_FONT
set_widths(ws_sum, [22, 12, 12, 13, 14, 12, 10, 14, 10, 12])

ws_sum.append([])
ws_sum.append(["Test counts per site"])
ws_sum["A8"].font = Font(bold=True, size=12, name="Arial")
ws_sum.append(["Site", "Test cases", "Pass", "Partial", "Warn", "Fail", "Skip"])
style_header(ws_sum, row=9)


def counts(rows):
    p = w = pa = f = sk = 0
    for r in rows:
        s = r[3].lower()
        if s == "pass": p += 1
        elif s == "partial": pa += 1
        elif s in ("warn", "warning"): w += 1
        elif s == "fail": f += 1
        elif s == "skip": sk += 1
    return p, pa, w, f, sk


w_p, w_pa, w_w, w_f, w_sk = counts(WAO_TESTS)
k_p, k_pa, k_w, k_f, k_sk = counts(KAIO_TESTS)
f_p, f_pa, f_w, f_f, f_sk = counts(FM_TESTS)

ws_sum.append(["website-auditor.io", len(WAO_TESTS), w_p, w_pa, w_w, w_f, w_sk])
ws_sum.append(["kevinarmstrong.io", len(KAIO_TESTS), k_p, k_pa, k_w, k_f, k_sk])
ws_sum.append(["fundermatch.org", len(FM_TESTS), f_p, f_pa, f_w, f_f, f_sk])

for r in range(10, 13):
    for c in range(1, 8):
        cell = ws_sum.cell(row=r, column=c)
        cell.alignment = CENTER
        cell.border = BORDER
        cell.font = BODY_FONT

# Instrumentl gap coverage
ws_sum.append([])
ws_sum.append(["Instrumentl gap coverage (43 tests)"])
ws_sum["A14"].font = Font(bold=True, size=12, name="Arial")
ic_p, ic_pa, ic_w, ic_f, ic_sk = counts(FM_IC)
ws_sum.append(["PASS", "PARTIAL", "FAIL", "SKIP", "Total"])
style_header(ws_sum, row=15)
ws_sum.append([ic_p, ic_pa, ic_f, ic_sk, len(FM_IC)])
for c in range(1, 6):
    cell = ws_sum.cell(row=16, column=c)
    cell.alignment = CENTER
    cell.border = BORDER
    cell.font = BODY_FONT

ws_sum.append([])
ws_sum.append(["Notes"])
ws_sum["A18"].font = Font(bold=True, size=12, name="Arial")
ws_sum.append(["1 PR opened: SpikeyCoder/funder-finder #176 (refresh stale 2025 placeholders to 2027). See 'PRs opened' sheet."])
ws_sum.append(["1 owner exception logged for kevinarmstrong.io subheader green #7AED8C. See 'Owner exceptions' sheet."])
ws_sum.append(["fundermatch.org light-mode contrast: 7/7 PASS. See FM-LM rows on fundermatch.org sheet."])
ws_sum.append(["Instrumentl competitive gap: 39 PASS / 3 PARTIAL / 1 FAIL of 43. Feature builder task to pick up FAIL + PARTIALs."])
ws_sum.append(["Regression checks for fundermatch.org: 10/10 PASS. See Regression-Tracking sheet."])

# ============================================================
# Site sheets
# ============================================================
ws_wao = wb.create_sheet("website-auditor.io")
write_tests(ws_wao, WAO_TESTS)
ws_kaio = wb.create_sheet("kevinarmstrong.io")
write_tests(ws_kaio, KAIO_TESTS)
ws_fm = wb.create_sheet("fundermatch.org")
write_tests(ws_fm, FM_TESTS)

# PRs opened
ws_pr = wb.create_sheet("PRs opened")
ws_pr.append(["Repo", "PR #", "Branch", "Title", "URL", "Notes"])
style_header(ws_pr)
ws_pr.append([
    "SpikeyCoder/funder-finder",
    "176",
    "usability/2026-06-11-fixes",
    "usability(2026-06-11): refresh stale 2025 grant cycle placeholders to 2027",
    "https://github.com/SpikeyCoder/funder-finder/pull/176",
    "Bumped Ford Foundation 2025 LOI -> 2027 LOI on ApplicationsPage. Bumped July 2025 - June 2026 -> July 2026 - June 2027 on GrantWriter. P3 polish."
])
ws_pr.append([
    "SpikeyCoder/chaos_tester",
    "—",
    "—",
    "(no PR — no fixable issues found)",
    "—",
    "All standard tests PASS. Loading-state regression and 'Not the right business?' regression both PASS (overlay sits below button, no emoji, no layout shift; submit re-enables when override fields valid)."
])
ws_pr.append([
    "SpikeyCoder/my_website",
    "—",
    "—",
    "(no PR — no fixable issues found)",
    "—",
    "All standard tests PASS. Subheader green #7AED8C left in place per owner exception. Stats reflect current 2024-2026 tenure."
])
for r in range(2, 5):
    for c in range(1, 7):
        cell = ws_pr.cell(row=r, column=c)
        cell.alignment = LEFT
        cell.border = BORDER
        cell.font = BODY_FONT
set_widths(ws_pr, [26, 8, 30, 60, 60, 60])
ws_pr.freeze_panes = "A2"

# Owner exceptions
ws_oe = wb.create_sheet("Owner exceptions")
ws_oe.append(["Site", "Item", "Test ID", "Reason kept", "Action"])
style_header(ws_oe)
ws_oe.append([
    "kevinarmstrong.io",
    "Hero subheader green #7AED8C on #2596be background",
    "KAIO-FI-005",
    "Owner prefers #7AED8C green color despite WCAG contrast considerations. Task spec explicitly lists as DO-NOT-auto-fix.",
    "Flagged WARN. Not auto-fixed. Not pushed in PR."
])
ws_oe.append([
    "website-auditor.io",
    "Hero Gartner '50% by 2028' citation",
    "WAO-FI-011",
    "Kept as directional marketing forecast. Owner exception per prior audits.",
    "Flagged WARN. Not auto-fixed."
])
ws_oe.append([
    "website-auditor.io",
    "/features page intentionally removed",
    "(intentional)",
    "Owner removed as redundant; distracted from URL entry goal.",
    "Not flagged. Not recommended for re-add."
])
ws_oe.append([
    "website-auditor.io",
    "/how-it-works page + 'How It Works' section intentionally removed",
    "(intentional)",
    "Owner removed as redundant with sample report.",
    "Not flagged. Not recommended for re-add."
])
ws_oe.append([
    "website-auditor.io",
    "FAQ section intentionally removed",
    "(intentional)",
    "Owner removed as redundant and outdated.",
    "Not flagged. Not recommended for re-add."
])
for r in range(2, 7):
    for c in range(1, 6):
        cell = ws_oe.cell(row=r, column=c)
        cell.alignment = LEFT
        cell.border = BORDER
        cell.font = BODY_FONT
set_widths(ws_oe, [22, 38, 18, 60, 50])
ws_oe.freeze_panes = "A2"

# Regression tracking — fundermatch.org
ws_rt = wb.create_sheet("Regression-Tracking")
ws_rt.append(["Site", "Regression item", "Status", "Notes"])
style_header(ws_rt)
fm_regressions = [
    ("fundermatch.org", "Privacy Policy link works (not 404)", "pass", "GET /privacy -> 200; PrivacyPolicy.tsx renders boilerplate sections."),
    ("fundermatch.org", "Terms of Service link works", "pass", "GET /terms -> 200; TermsOfService.tsx renders."),
    ("fundermatch.org", "Contact page works (not 404)", "pass", "GET /contact -> 200; ContactPage.tsx renders email + form."),
    ("fundermatch.org", "Keyboard focus indicators present", "pass", "*:focus-visible outline-2 outline-offset-2 outline-[#58a6ff] in src/index.css."),
    ("fundermatch.org", "Form validation shows error messages", "pass", "SignupPage step-validation + Toast component; ErrorBoundary wraps all routes."),
    ("fundermatch.org", "Body text contrast passes WCAG AA", "pass", "Dark mode: text-white on #0d1117 approx 17:1. Light mode: text-gray-400 -> #59636e !important approx 6.5:1."),
    ("fundermatch.org", "Search input has aria-label", "pass", "FilterPanel inputs all carry aria-label (Search keywords, Search states, etc.)."),
    ("fundermatch.org", "prefers-reduced-motion rule active", "pass", "src/index.css @media (prefers-reduced-motion: reduce) zeroes animation + transition durations."),
    ("fundermatch.org", "Data stats section visible on homepage", "pass", "Landing.tsx 'Why FunderMatch' + DemoVideo show 18K+ funders / matching speed / 990-PF coverage."),
    ("fundermatch.org", "Trust signals visible on homepage", "pass", "Shield/CheckCircle icons + free-for-501c3 messaging + no-ads claim."),
]
for r in fm_regressions:
    ws_rt.append(list(r))
    last = ws_rt.max_row
    fill = status_fill(r[2])
    for c in range(1, 5):
        cell = ws_rt.cell(row=last, column=c)
        cell.alignment = LEFT
        cell.border = BORDER
        cell.font = BODY_FONT
        if fill: cell.fill = fill
set_widths(ws_rt, [22, 60, 10, 80])
ws_rt.freeze_panes = "A2"

# Save
out = "/sessions/bold-gracious-thompson/mnt/outputs/daily_usability_audit_2026-06-11.xlsx"
wb.save(out)
print(f"Wrote {out}")
print(f"WAO {len(WAO_TESTS)} tests")
print(f"KAIO {len(KAIO_TESTS)} tests")
print(f"FM {len(FM_TESTS)} tests (standard {len(FM_STANDARD)} + LM {len(FM_LM)} + IC {len(FM_IC)})")
print(f"Total {len(WAO_TESTS) + len(KAIO_TESTS) + len(FM_TESTS)}")
